package com.wanda.member.countermgt.data;

import com.wanda.member.countermgt.data.TMemberRepair;
import com.wanda.member.countermgt.data.TMemberRepairExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberRepairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int countByExample(TMemberRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int deleteByExample(TMemberRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int insert(TMemberRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int insertSelective(TMemberRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    List<TMemberRepair> selectByExample(TMemberRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int updateByExampleSelective(@Param("record") TMemberRepair record, @Param("example") TMemberRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_REPAIR
     *
     * @mbggenerated Sun Nov 24 15:04:44 CST 2013
     */
    int updateByExample(@Param("record") TMemberRepair record, @Param("example") TMemberRepairExample example);
}