package com.wanda.member.countermgt.data;

import com.wanda.member.countermgt.data.TMemberInfo;
import com.wanda.member.countermgt.data.TMemberInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int countByExample(TMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int deleteByExample(TMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal memberInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int insert(TMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int insertSelective(TMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    List<TMemberInfo> selectByExample(TMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    TMemberInfo selectByPrimaryKey(BigDecimal memberInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int updateByExampleSelective(@Param("record") TMemberInfo record, @Param("example") TMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int updateByExample(@Param("record") TMemberInfo record, @Param("example") TMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int updateByPrimaryKeySelective(TMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO
     *
     * @mbggenerated Mon Nov 11 23:12:43 CST 2013
     */
    int updateByPrimaryKey(TMemberInfo record);
}