package com.wanda.member.countermgt.data;

import com.wanda.member.countermgt.data.TMemberInfoHistory;
import com.wanda.member.countermgt.data.TMemberInfoHistoryExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int countByExample(TMemberInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int deleteByExample(TMemberInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int insert(TMemberInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int insertSelective(TMemberInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    List<TMemberInfoHistory> selectByExample(TMemberInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    TMemberInfoHistory selectByPrimaryKey(BigDecimal seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int updateByExampleSelective(@Param("record") TMemberInfoHistory record, @Param("example") TMemberInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int updateByExample(@Param("record") TMemberInfoHistory record, @Param("example") TMemberInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int updateByPrimaryKeySelective(TMemberInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_INFO_HISTORY
     *
     * @mbggenerated Mon Nov 18 16:49:18 CST 2013
     */
    int updateByPrimaryKey(TMemberInfoHistory record);
}