<%@ page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>jQuery UI Example Page</title>
	<jsp:include page="../header.jsp"><jsp:param name="groups" value="jquery,jquery-ui,jqgrid,validation,common"/></jsp:include>

	<script type="text/javascript">
		$(function(){
			$('button').button();
			
			$('#infoBox').click(function() {
				$.msgBox('info', 'title', 'content content content content content content content content!');
			});
			
			$('#checkedBox').click(function() {
				$.msgBox('checked', 'title', 'content content content content content content content content!');
			});
			
			$('#warnBox').click(function() {
				$.msgBox('warn', 'title', 'content content content content content content content content!');
			});
			
			$('#errorBox').click(function() {
				$.msgBox('error', 'title', 'content content content content content content content content!', function() { alert('Message Box closed!')});
			}); 
			
			$('#confirmBox').click(function() {
				$.msgBox('confirm', 'title', 'content content content content content content content content!', function(result) { alert('You selected:' + (result ? 'OK' : 'Cancel')); });
			});
			
			$('#yesnoBox').click(function() {
				$.msgBox('yesno', 'title', 'content content content content content content content content!', function(result) { alert('You selected:' + (result ? 'Yes' : 'No')); });
			});
			
			
		});
	</script>
	<style type="text/css">
		body{ font: 68% "Trebuchet MS", sans-serif; margin: 50px;}
	</style>
</head>
<body>

	<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
	<h2 class="demoHeaders">Dialog</h2>
	

	<button id="infoBox">Information Message Box</button>
	<button id="warnBox">Warning Message Box</button>
	<button id="errorBox">Error Message Box</button>
	<button id="checkedBox">Checked Message Box</button>
	
	<button id="confirmBox">Confirmation Message Box</button>
	<button id="yesnoBox">Yes/No Message Box</button>

</body>
</html>


