package com.wanda.member.countermgt.data;

import java.math.BigDecimal;

import com.wanda.member.ObjectType;

public class TCinemaTicket extends ObjectType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.MEMBER_ID
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    private BigDecimal memberId;
    
    private String cinemaKey;
    
    private int ticketNum;    
    

    public String getCinemaKey() {
		return cinemaKey;
	}

	public void setCinemaKey(String cinemaKey) {
		this.cinemaKey = cinemaKey;
	}

	public int getTicketNum() {
		return ticketNum;
	}

	public void setTicketNum(int ticketNum) {
		this.ticketNum = ticketNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.MEMBER_ID
     *
     * @return the value of T_MEMBER.MEMBER_ID
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public BigDecimal getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.MEMBER_ID
     *
     * @param memberId the value for T_MEMBER.MEMBER_ID
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public void setMemberId(BigDecimal memberId) {
        this.memberId = memberId;
    }
}