package com.wanda.member.countermgt.data;

import java.math.BigDecimal;
import java.util.Date;

public class TCinema {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.SEQID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.SHORT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Object shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.PIN_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String pinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.INNER_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String innerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.ISOPEN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String isopen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.OPEN_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CONTRACT_BEGIN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date contractBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CONTRACT_END
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date contractEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal hallCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.SEAT_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal seatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.ADDRESS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Object address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.POST_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CINEMA_LEVEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String cinemaLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CINEMA_ATTR
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String cinemaAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.SUPP_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String suppType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.MKT_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String mktType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.PROVINCE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CITY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.AREA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CINEMA_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String cinemaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CREATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CREATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.UPDATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.DELETED
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.DELETE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Date deleteDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.DELETE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String deleteBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.VERSION
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CINEMA_CONTACT_ID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal cinemaContactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.DIGIT_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal digitHallCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.TRID_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal tridHallCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.IMAX_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private BigDecimal imaxHallCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.INNER_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String innerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.OUT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String outName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.WORK_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String workStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.WORK_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String workEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.WORKEND_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String workendStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.WORKEND_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String workendEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.IS_FEEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String isFeel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.PRINT_NUM
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String printNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.TOTAL_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Long totalSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.NOTE_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Long noteSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CODE_OF_CFS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String codeOfCfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.CODE_OF_BCS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private String codeOfBcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CINEMA.GROUP_ACCOUNT_RATIO
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    private Long groupAccountRatio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.SEQID
     *
     * @return the value of T_CINEMA.SEQID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.SEQID
     *
     * @param seqid the value for T_CINEMA.SEQID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setSeqid(BigDecimal seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.SHORT_NAME
     *
     * @return the value of T_CINEMA.SHORT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Object getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.SHORT_NAME
     *
     * @param shortName the value for T_CINEMA.SHORT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setShortName(Object shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.PIN_CODE
     *
     * @return the value of T_CINEMA.PIN_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getPinCode() {
        return pinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.PIN_CODE
     *
     * @param pinCode the value for T_CINEMA.PIN_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.INNER_CODE
     *
     * @return the value of T_CINEMA.INNER_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.INNER_CODE
     *
     * @param innerCode the value for T_CINEMA.INNER_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setInnerCode(String innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CODE
     *
     * @return the value of T_CINEMA.CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CODE
     *
     * @param code the value for T_CINEMA.CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.ISOPEN
     *
     * @return the value of T_CINEMA.ISOPEN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.ISOPEN
     *
     * @param isopen the value for T_CINEMA.ISOPEN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setIsopen(String isopen) {
        this.isopen = isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.OPEN_DATE
     *
     * @return the value of T_CINEMA.OPEN_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.OPEN_DATE
     *
     * @param openDate the value for T_CINEMA.OPEN_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CONTRACT_BEGIN
     *
     * @return the value of T_CINEMA.CONTRACT_BEGIN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getContractBegin() {
        return contractBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CONTRACT_BEGIN
     *
     * @param contractBegin the value for T_CINEMA.CONTRACT_BEGIN
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setContractBegin(Date contractBegin) {
        this.contractBegin = contractBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CONTRACT_END
     *
     * @return the value of T_CINEMA.CONTRACT_END
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getContractEnd() {
        return contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CONTRACT_END
     *
     * @param contractEnd the value for T_CINEMA.CONTRACT_END
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setContractEnd(Date contractEnd) {
        this.contractEnd = contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.HALL_COUNT
     *
     * @return the value of T_CINEMA.HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getHallCount() {
        return hallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.HALL_COUNT
     *
     * @param hallCount the value for T_CINEMA.HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setHallCount(BigDecimal hallCount) {
        this.hallCount = hallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.SEAT_COUNT
     *
     * @return the value of T_CINEMA.SEAT_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getSeatCount() {
        return seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.SEAT_COUNT
     *
     * @param seatCount the value for T_CINEMA.SEAT_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setSeatCount(BigDecimal seatCount) {
        this.seatCount = seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.ADDRESS
     *
     * @return the value of T_CINEMA.ADDRESS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Object getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.ADDRESS
     *
     * @param address the value for T_CINEMA.ADDRESS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setAddress(Object address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.POST_CODE
     *
     * @return the value of T_CINEMA.POST_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.POST_CODE
     *
     * @param postCode the value for T_CINEMA.POST_CODE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CINEMA_LEVEL
     *
     * @return the value of T_CINEMA.CINEMA_LEVEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCinemaLevel() {
        return cinemaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CINEMA_LEVEL
     *
     * @param cinemaLevel the value for T_CINEMA.CINEMA_LEVEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCinemaLevel(String cinemaLevel) {
        this.cinemaLevel = cinemaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CINEMA_ATTR
     *
     * @return the value of T_CINEMA.CINEMA_ATTR
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCinemaAttr() {
        return cinemaAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CINEMA_ATTR
     *
     * @param cinemaAttr the value for T_CINEMA.CINEMA_ATTR
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCinemaAttr(String cinemaAttr) {
        this.cinemaAttr = cinemaAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.SUPP_TYPE
     *
     * @return the value of T_CINEMA.SUPP_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getSuppType() {
        return suppType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.SUPP_TYPE
     *
     * @param suppType the value for T_CINEMA.SUPP_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setSuppType(String suppType) {
        this.suppType = suppType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.MKT_TYPE
     *
     * @return the value of T_CINEMA.MKT_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getMktType() {
        return mktType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.MKT_TYPE
     *
     * @param mktType the value for T_CINEMA.MKT_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setMktType(String mktType) {
        this.mktType = mktType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.PROVINCE
     *
     * @return the value of T_CINEMA.PROVINCE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.PROVINCE
     *
     * @param province the value for T_CINEMA.PROVINCE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setProvince(BigDecimal province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CITY
     *
     * @return the value of T_CINEMA.CITY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CITY
     *
     * @param city the value for T_CINEMA.CITY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCity(BigDecimal city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.AREA
     *
     * @return the value of T_CINEMA.AREA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.AREA
     *
     * @param area the value for T_CINEMA.AREA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CINEMA_TYPE
     *
     * @return the value of T_CINEMA.CINEMA_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCinemaType() {
        return cinemaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CINEMA_TYPE
     *
     * @param cinemaType the value for T_CINEMA.CINEMA_TYPE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCinemaType(String cinemaType) {
        this.cinemaType = cinemaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CREATE_DATE
     *
     * @return the value of T_CINEMA.CREATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CREATE_DATE
     *
     * @param createDate the value for T_CINEMA.CREATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CREATE_BY
     *
     * @return the value of T_CINEMA.CREATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CREATE_BY
     *
     * @param createBy the value for T_CINEMA.CREATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.UPDATE_DATE
     *
     * @return the value of T_CINEMA.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.UPDATE_DATE
     *
     * @param updateDate the value for T_CINEMA.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.UPDATE_BY
     *
     * @return the value of T_CINEMA.UPDATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.UPDATE_BY
     *
     * @param updateBy the value for T_CINEMA.UPDATE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.DELETED
     *
     * @return the value of T_CINEMA.DELETED
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.DELETED
     *
     * @param deleted the value for T_CINEMA.DELETED
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.DELETE_DATE
     *
     * @return the value of T_CINEMA.DELETE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.DELETE_DATE
     *
     * @param deleteDate the value for T_CINEMA.DELETE_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.DELETE_BY
     *
     * @return the value of T_CINEMA.DELETE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.DELETE_BY
     *
     * @param deleteBy the value for T_CINEMA.DELETE_BY
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.VERSION
     *
     * @return the value of T_CINEMA.VERSION
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.VERSION
     *
     * @param version the value for T_CINEMA.VERSION
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CINEMA_CONTACT_ID
     *
     * @return the value of T_CINEMA.CINEMA_CONTACT_ID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getCinemaContactId() {
        return cinemaContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CINEMA_CONTACT_ID
     *
     * @param cinemaContactId the value for T_CINEMA.CINEMA_CONTACT_ID
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCinemaContactId(BigDecimal cinemaContactId) {
        this.cinemaContactId = cinemaContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.DIGIT_HALL_COUNT
     *
     * @return the value of T_CINEMA.DIGIT_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getDigitHallCount() {
        return digitHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.DIGIT_HALL_COUNT
     *
     * @param digitHallCount the value for T_CINEMA.DIGIT_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setDigitHallCount(BigDecimal digitHallCount) {
        this.digitHallCount = digitHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.TRID_HALL_COUNT
     *
     * @return the value of T_CINEMA.TRID_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getTridHallCount() {
        return tridHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.TRID_HALL_COUNT
     *
     * @param tridHallCount the value for T_CINEMA.TRID_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setTridHallCount(BigDecimal tridHallCount) {
        this.tridHallCount = tridHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.IMAX_HALL_COUNT
     *
     * @return the value of T_CINEMA.IMAX_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public BigDecimal getImaxHallCount() {
        return imaxHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.IMAX_HALL_COUNT
     *
     * @param imaxHallCount the value for T_CINEMA.IMAX_HALL_COUNT
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setImaxHallCount(BigDecimal imaxHallCount) {
        this.imaxHallCount = imaxHallCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.INNER_NAME
     *
     * @return the value of T_CINEMA.INNER_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getInnerName() {
        return innerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.INNER_NAME
     *
     * @param innerName the value for T_CINEMA.INNER_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setInnerName(String innerName) {
        this.innerName = innerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.OUT_NAME
     *
     * @return the value of T_CINEMA.OUT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getOutName() {
        return outName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.OUT_NAME
     *
     * @param outName the value for T_CINEMA.OUT_NAME
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setOutName(String outName) {
        this.outName = outName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.WORK_START_DATE
     *
     * @return the value of T_CINEMA.WORK_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getWorkStartDate() {
        return workStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.WORK_START_DATE
     *
     * @param workStartDate the value for T_CINEMA.WORK_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setWorkStartDate(String workStartDate) {
        this.workStartDate = workStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.WORK_END_DATE
     *
     * @return the value of T_CINEMA.WORK_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getWorkEndDate() {
        return workEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.WORK_END_DATE
     *
     * @param workEndDate the value for T_CINEMA.WORK_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setWorkEndDate(String workEndDate) {
        this.workEndDate = workEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.WORKEND_START_DATE
     *
     * @return the value of T_CINEMA.WORKEND_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getWorkendStartDate() {
        return workendStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.WORKEND_START_DATE
     *
     * @param workendStartDate the value for T_CINEMA.WORKEND_START_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setWorkendStartDate(String workendStartDate) {
        this.workendStartDate = workendStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.WORKEND_END_DATE
     *
     * @return the value of T_CINEMA.WORKEND_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getWorkendEndDate() {
        return workendEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.WORKEND_END_DATE
     *
     * @param workendEndDate the value for T_CINEMA.WORKEND_END_DATE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setWorkendEndDate(String workendEndDate) {
        this.workendEndDate = workendEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.IS_FEEL
     *
     * @return the value of T_CINEMA.IS_FEEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getIsFeel() {
        return isFeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.IS_FEEL
     *
     * @param isFeel the value for T_CINEMA.IS_FEEL
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setIsFeel(String isFeel) {
        this.isFeel = isFeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.PRINT_NUM
     *
     * @return the value of T_CINEMA.PRINT_NUM
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getPrintNum() {
        return printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.PRINT_NUM
     *
     * @param printNum the value for T_CINEMA.PRINT_NUM
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setPrintNum(String printNum) {
        this.printNum = printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.TOTAL_SIZE
     *
     * @return the value of T_CINEMA.TOTAL_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Long getTotalSize() {
        return totalSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.TOTAL_SIZE
     *
     * @param totalSize the value for T_CINEMA.TOTAL_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.NOTE_SIZE
     *
     * @return the value of T_CINEMA.NOTE_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Long getNoteSize() {
        return noteSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.NOTE_SIZE
     *
     * @param noteSize the value for T_CINEMA.NOTE_SIZE
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setNoteSize(Long noteSize) {
        this.noteSize = noteSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CODE_OF_CFS
     *
     * @return the value of T_CINEMA.CODE_OF_CFS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCodeOfCfs() {
        return codeOfCfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CODE_OF_CFS
     *
     * @param codeOfCfs the value for T_CINEMA.CODE_OF_CFS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCodeOfCfs(String codeOfCfs) {
        this.codeOfCfs = codeOfCfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.CODE_OF_BCS
     *
     * @return the value of T_CINEMA.CODE_OF_BCS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public String getCodeOfBcs() {
        return codeOfBcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.CODE_OF_BCS
     *
     * @param codeOfBcs the value for T_CINEMA.CODE_OF_BCS
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setCodeOfBcs(String codeOfBcs) {
        this.codeOfBcs = codeOfBcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CINEMA.GROUP_ACCOUNT_RATIO
     *
     * @return the value of T_CINEMA.GROUP_ACCOUNT_RATIO
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public Long getGroupAccountRatio() {
        return groupAccountRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CINEMA.GROUP_ACCOUNT_RATIO
     *
     * @param groupAccountRatio the value for T_CINEMA.GROUP_ACCOUNT_RATIO
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    public void setGroupAccountRatio(Long groupAccountRatio) {
        this.groupAccountRatio = groupAccountRatio;
    }
}