package com.wanda.member.countermgt.data;

import com.wanda.member.countermgt.data.TCinema;
import com.wanda.member.countermgt.data.TCinemaExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCinemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int countByExample(TCinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int deleteByExample(TCinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int insert(TCinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int insertSelective(TCinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    List<TCinema> selectByExample(TCinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    TCinema selectByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") TCinema record, @Param("example") TCinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int updateByExample(@Param("record") TCinema record, @Param("example") TCinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int updateByPrimaryKeySelective(TCinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CINEMA
     *
     * @mbggenerated Tue Nov 26 17:25:11 CST 2013
     */
    int updateByPrimaryKey(TCinema record);
}