package com.wanda.member.countermgt.data;

import com.wanda.member.countermgt.data.TDConMember;
import com.wanda.member.countermgt.data.TDConMemberExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDConMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int countByExample(TDConMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int deleteByExample(TDConMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal memberKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int insert(TDConMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int insertSelective(TDConMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    List<TDConMember> selectByExample(TDConMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    TDConMember selectByPrimaryKey(BigDecimal memberKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int updateByExampleSelective(@Param("record") TDConMember record, @Param("example") TDConMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int updateByExample(@Param("record") TDConMember record, @Param("example") TDConMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int updateByPrimaryKeySelective(TDConMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_D_CON_MEMBER
     *
     * @mbggenerated Wed Nov 13 12:16:22 CST 2013
     */
    int updateByPrimaryKey(TDConMember record);
}