package com.wanda.ccs.model;

// Generated 2011-11-29 14:55:15 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TAuthRight generated by hbm2java
 * 系统功能模块
 */
@Entity
@Table(name = "T_AUTH_MODULE")
public class TAuthModule extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -7667869829753211738L;
	
	private Long id;  //功能模块Id
	private String moduleName; //功能模块名称
	private TAuthSystem tAuthSystem;//所属系统
	private Long authSystemId;
	
	private Set<TAuthRight> tAuthRights = new HashSet<TAuthRight>(0);


	public TAuthModule() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_AUTH_MODULE")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "AUTH_MODULE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "MODULE_NAME", length=500)
	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTH_SYSTEM_ID", insertable = false, updatable = false)
	public TAuthSystem gettAuthSystem() {
		return tAuthSystem;
	}

	public void settAuthSystem(TAuthSystem tAuthSystem) {
		this.tAuthSystem = tAuthSystem;
	}
	
	@Column(name = "AUTH_SYSTEM_ID")
	public Long getAuthSystemId() {
		return authSystemId;
	}

	public void setAuthSystemId(Long authSystemId) {
		this.authSystemId = authSystemId;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tAuthModule")
	@Fetch(FetchMode.SUBSELECT)
	public Set<TAuthRight> gettAuthRights() {
		return tAuthRights;
	}
	
	public void settAuthRights(Set<TAuthRight> tAuthRights) {
		this.tAuthRights = tAuthRights;
	}
}
