package com.wanda.ccs.model;

// Generated 2011-11-29 14:55:15 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TAuthRight generated by hbm2java
 * 系统功能模块
 */
@Entity
@Table(name = "T_AUTH_SYSTEM")
public class TAuthSystem extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -4090183816846929538L;
	
	private Long id;  //功能模块Id
	private String systemName; //系统名称
	private String systemId;
	private String systemIp;
	
	private Set<TAuthModule> tAuthModules = new HashSet<TAuthModule>(0);
	private Set<TAuthRight> tAuthRights = new HashSet<TAuthRight>(0);
	

	public TAuthSystem() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_AUTH_SYSTEM")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "AUTH_SYSTEM_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "SYSTEM_NAME", length=500)
	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}
	
	@Column(name = "SYSTEM_ID", length=50)
	public String getSystemId() {
		return systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "SYSTEM_IP", length=500)
	public String getSystemIp() {
		return systemIp;
	}


	public void setSystemIp(String systemIp) {
		this.systemIp = systemIp;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tAuthSystem")
	@Fetch(FetchMode.SUBSELECT)
	public Set<TAuthModule> gettAuthModules() {
		return tAuthModules;
	}

	public void settAuthModules(Set<TAuthModule> tAuthModules) {
		this.tAuthModules = tAuthModules;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tAuthSystem")
	@Fetch(FetchMode.SUBSELECT)
	public Set<TAuthRight> gettAuthRights() {
		return tAuthRights;
	}

	public void settAuthRights(Set<TAuthRight> tAuthRights) {
		this.tAuthRights = tAuthRights;
	}
}
