package com.wanda.ccs.model;

// Generated 2011-11-29 14:55:15 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TAuthRight generated by hbm2java
 * 可授予用户的权限
 */
@Entity
@Table(name = "T_AUTH_RIGHT")
public class TAuthRight extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -114543070695031638L;
	
	private Long id;  //权限Id
	private String rightCode; //权限代码
	private String rightName; //权限名称
	private String forGroup; //Y表示可以赋予院线级用户
	private String forRegion; //Y表示可以赋予区域级用户
	private String forCinema; //Y表示可以赋予影城级用户
	private TAuthModule tAuthModule; //系统功能模块
	private TAuthSystem tAuthSystem;//系统
	private Long authModuleId;
	private Long authSystemId;
	private Set<TAuthUserRight> tAuthUserRights = new HashSet<TAuthUserRight>(0);
	private Set<TAuthRgroupRight> tAuthRgroupRights = new HashSet<TAuthRgroupRight>(
			0);
	private Set<TAuthDeptRight> tAuthDeptRights = new HashSet<TAuthDeptRight>(0);

	public TAuthRight() {
	}

	public TAuthRight(String forGroup, String forRegion, String forCinema) {
		this.forGroup = forGroup;
		this.forRegion = forRegion;
		this.forCinema = forCinema;
	}

	public TAuthRight(String rightCode, String rightName, String forGroup,
			String forRegion, String forCinema,
			Set<TAuthUserRight> tAuthUserRights,
			Set<TAuthRgroupRight> tAuthRgroupRights,
			Set<TAuthDeptRight> tAuthDeptRights) {
		this.rightCode = rightCode;
		this.rightName = rightName;
		this.forGroup = forGroup;
		this.forRegion = forRegion;
		this.forCinema = forCinema;
		this.tAuthUserRights = tAuthUserRights;
		this.tAuthRgroupRights = tAuthRgroupRights;
		this.tAuthDeptRights = tAuthDeptRights;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_AUTH_RIGHT")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "AUTH_RIGHT_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RIGHT_CODE", length = 30)
	public String getRightCode() {
		return this.rightCode;
	}

	public void setRightCode(String rightCode) {
		this.rightCode = rightCode;
	}

	@Column(name = "RIGHT_NAME",length=500)
	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	@Column(name = "FOR_GROUP", nullable = false, length = 1)
	public String getForGroup() {
		return this.forGroup;
	}

	public void setForGroup(String forGroup) {
		this.forGroup = forGroup;
	}

	@Column(name = "FOR_REGION", nullable = false, length = 1)
	public String getForRegion() {
		return this.forRegion;
	}

	public void setForRegion(String forRegion) {
		this.forRegion = forRegion;
	}

	@Column(name = "FOR_CINEMA", nullable = false, length = 1)
	public String getForCinema() {
		return this.forCinema;
	}

	public void setForCinema(String forCinema) {
		this.forCinema = forCinema;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTH_MODULE_ID", insertable = false, updatable = false)
	public TAuthModule gettAuthModule() {
		return tAuthModule;
	}

	public void settAuthModule(TAuthModule tAuthModule) {
		this.tAuthModule = tAuthModule;
	}
	
	@Column(name = "AUTH_MODULE_ID")
	public Long getAuthModuleId() {
		return authModuleId;
	}

	public void setAuthModuleId(Long authModuleId) {
		this.authModuleId = authModuleId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTH_SYSTEM_ID", insertable = false, updatable = false)
	public TAuthSystem gettAuthSystem() {
		return tAuthSystem;
	}

	public void settAuthSystem(TAuthSystem tAuthSystem) {
		this.tAuthSystem = tAuthSystem;
	}
	
	@Column(name = "AUTH_SYSTEM_ID")
	public Long getAuthSystemId() {
		return authSystemId;
	}

	public void setAuthSystemId(Long authSystemId) {
		this.authSystemId = authSystemId;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tAuthRight")
	public Set<TAuthUserRight> gettAuthUserRights() {
		return this.tAuthUserRights;
	}

	public void settAuthUserRights(Set<TAuthUserRight> tAuthUserRights) {
		this.tAuthUserRights = tAuthUserRights;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tAuthRight")
	public Set<TAuthRgroupRight> gettAuthRgroupRights() {
		return this.tAuthRgroupRights;
	}

	public void settAuthRgroupRights(Set<TAuthRgroupRight> tAuthRgroupRights) {
		this.tAuthRgroupRights = tAuthRgroupRights;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tAuthRight")
	public Set<TAuthDeptRight> gettAuthDeptRights() {
		return this.tAuthDeptRights;
	}

	public void settAuthDeptRights(Set<TAuthDeptRight> tAuthDeptRights) {
		this.tAuthDeptRights = tAuthDeptRights;
	}

}
