package com.wanda.ccs.model;

// Generated 2013-5-21 18:55:28 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.BlameableEntity;
import com.xcesys.extras.core.util.StringUtil;

/**
 * TCampaign generated by hbm2java
 * 活动
 */
@Entity
@Table(name = "T_CAMPAIGN")
public class TCampaign extends BlameableEntity implements java.io.Serializable {
	private static final long serialVersionUID = -7682546835058562310L;
	
	private Long id;
	private String code;//编码
	private String name;//名称
	private Date startDate;//开始日期
	private Date endDate;//结束日期
	private String status;//活动状态-DIM1001
	private String type;//活动类型-DIM1004
	private String channel;//活动渠道-DIM1003
	private String description;//描述
	private Long creationCinemaId;//创建方-影城ID
	private TCinema tCinema;
	private String creationAreaId;//创建方-区域ID
	private boolean allCinema;//包含所有影城
	private String creationLevel;//创建方级别-DIM1013
	private String allowModifier;//授权修改人(用户名)
	private String settlementType;// 结算方式 10院线 20影城
	private Set<TCmnPhase> tCmnPhases = new HashSet<TCmnPhase>(0);
	private Set<TCmnActivity> tCmnActivities = new HashSet<TCmnActivity>(0);
	private Set<TCampaignCinema> tCampaignCinemas = new HashSet<TCampaignCinema>(
			0);
	
	private String strStartDate;
	private String strEndDate;
	
	private String cinemas;
	private String phaseAndActivitys;



	public TCampaign() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_CAMPAIGN", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CAMPAIGN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "START_DATE")
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE")
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TYPE", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "CHANNEL", nullable = false, length = 20)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATION_CINEMA_ID", precision = 22, scale = 0)
	public Long getCreationCinemaId() {
		return this.creationCinemaId;
	}

	public void setCreationCinemaId(Long creationCinemaId) {
		this.creationCinemaId = creationCinemaId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATION_CINEMA_ID", updatable = false, insertable = false)
	public TCinema gettCinema() {
		return tCinema;
	}
	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "CREATION_AREA_ID", nullable = false, length = 20)
	public String getCreationAreaId() {
		return this.creationAreaId;
	}

	public void setCreationAreaId(String creationAreaId) {
		this.creationAreaId = creationAreaId;
	}

	@Column(name = "ALL_CINEMA", nullable = false, length = 1)
	public boolean getAllCinema() {
		return this.allCinema;
	}

	public void setAllCinema(boolean allCinema) {
		this.allCinema = allCinema;
	}

	@Column(name = "CREATION_LEVEL", length = 20)
	public String getCreationLevel() {
		return this.creationLevel;
	}

	public void setCreationLevel(String creationLevel) {
		this.creationLevel = creationLevel;
	}

	@Column(name = "ALLOW_MODIFIER", length = 40)
	public String getAllowModifier() {
		return this.allowModifier;
	}

	public void setAllowModifier(String allowModifier) {
		this.allowModifier = allowModifier;
	}
	
	@Column(name = "SETTLEMENT_TYPE")
	public String getSettlementType() {
		return settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCampaign")
	@OrderBy(value="startDate,name asc")
	public Set<TCmnPhase> gettCmnPhases() {
		return this.tCmnPhases;
	}

	public void settCmnPhases(Set<TCmnPhase> tCmnPhases) {
		this.tCmnPhases = tCmnPhases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCampaign")
	public Set<TCmnActivity> gettCmnActivities() {
		return this.tCmnActivities;
	}

	public void settCmnActivities(Set<TCmnActivity> tCmnActivities) {
		this.tCmnActivities = tCmnActivities;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCampaign", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<TCampaignCinema> gettCampaignCinemas() {
		return this.tCampaignCinemas;
	}

	public void settCampaignCinemas(Set<TCampaignCinema> tCampaignCinemas) {
		this.tCampaignCinemas = tCampaignCinemas;
	}
	
	
	@Transient
	public String getStrStartDate() {
		if(startDate != null)
			strStartDate = new SimpleDateFormat("yyyy-MM-dd").format(startDate);
		return strStartDate;
	}

	public void setStrStartDate(String strStartDate) {
		try {
			if(!StringUtil.isNullOrBlank(strStartDate))
				startDate = new SimpleDateFormat("yyyy-MM-dd").parse(strStartDate);
			else
				startDate = null;
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.strStartDate = strStartDate;
	}

	@Transient
	public String getStrEndDate() {
		if(endDate != null)
			strEndDate = new SimpleDateFormat("yyyy-MM-dd").format(endDate);
		return strEndDate;
	}

	public void setStrEndDate(String strEndDate) {
		try {
			if(!StringUtil.isNullOrBlank(strEndDate))
				endDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(strEndDate+" 23:59:59");
			else
				endDate = null;
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.strEndDate = strEndDate;
	}
	
	
	@Transient
	public String getCinemas() {
		return cinemas;
	}

	public void setCinemas(String cinemas) {
		this.cinemas = cinemas;
	}


	@Transient
	public String getPhaseAndActivitys() {
		return phaseAndActivitys;
	}

	public void setPhaseAndActivitys(String phaseAndActivitys) {
		this.phaseAndActivitys = phaseAndActivitys;
	}
}
