package com.wanda.ccs.model;

// Generated 2011-11-2 12:36:06 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCardTrans generated by hbm2java
 */
@Entity
@Table(name = "T_CARD_TRANS")
public class TCardTrans extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 466418307103765537L;
	
	private Long id;
	private TCard tCard; //卡
	private TCard dCard; //对打折卡功能的补充(优享卡)
	private TCinema tCinema;  //卖品所在影城
	private String orderId;   //订单号码（由前端POS或网站）生成
	private String channel;   //购买品渠道
	private Float balBefore = 0f;   //购前卡余额
	private Float balAfter = 0f;    //购后卡余额
	private Float balChange = 0f;  //余额变化
	private String remarks;   //备注
	private String operatorName;    //售卖品的服务员
	private Date transTime;    //售卖品时间
	private String transType;  //销售类型，S售，R退
	private String transContType;  //交易内容 T-购票，G-购卖品，A-既购票也购卖品
	private Set<TCardTransGood> tCardTransGoods = new HashSet<TCardTransGood>(
			0);
	private Set<TCardTransRound> tCardTransRounds = new HashSet<TCardTransRound>(
			0);
	private Long cardId;
	private Long discountCardId;

	public TCardTrans() {
	}

	public TCardTrans(TCard tCard, TCinema tCinema, String orderId,
			String channel, Float balBefore, Float balAfter, Float balChange,
			Date transTime, Long cardId) {
		this.tCard = tCard;
		this.tCinema = tCinema;
		this.orderId = orderId;
		this.channel = channel;
		this.balBefore = balBefore;
		this.balAfter = balAfter;
		this.balChange = balChange;
		this.transTime = transTime;
		this.cardId =cardId;
	}

	public TCardTrans(TCard tCard, TCinema tCinema, String orderId,
			String channel, Float balBefore, Float balAfter, Float balChange,
			String remarks, String operatorName, Date transTime, String transType,
			String transContType,
			Set<TCardTransGood> tCardTransGoods,Set<TCardTransRound> tCardTransRounds, Long cardId) {
		this.tCard = tCard;
		this.tCinema = tCinema;
		this.orderId = orderId;
		this.channel = channel;
		this.balBefore = balBefore;
		this.balAfter = balAfter;
		this.balChange = balChange;
		this.remarks = remarks;
		this.operatorName = operatorName;
		this.transTime = transTime;
		this.transType = transType;
		this.transContType = transContType;
		this.tCardTransGoods = tCardTransGoods;
		this.tCardTransRounds = tCardTransRounds;
		this.cardId =cardId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CARD_TRANS", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CARD_TRANS_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_ID", insertable = false, updatable = false)
	public TCard gettCard() {
		return this.tCard;
	}

	public void settCard(TCard tCard) {
		this.tCard = tCard;
	}
	
	@Column(name = "CARD_ID")
	public Long getCardId() {
		return cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISCOUNT_CARD_ID", insertable = false, updatable = false)
	public TCard getdCard() {
		return dCard;
	}

	public void setdCard(TCard dCard) {
		this.dCard = dCard;
	}
	
	@Column(name = "DISCOUNT_CARD_ID")
	public long getDiscountCardId() {
		return discountCardId;
	}

	public void setDiscountCardId(Long discountCardId) {
		this.discountCardId = discountCardId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA", nullable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "CHANNEL", nullable = false, length = 100)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	@Column(name = "BAL_BEFORE", nullable = false, precision = 10)
	public Float getBalBefore() {
		return this.balBefore;
	}

	public void setBalBefore(Float balBefore) {
		this.balBefore = balBefore;
	}

	@Column(name = "BAL_AFTER", nullable = false, precision = 10)
	public Float getBalAfter() {
		return this.balAfter;
	}

	public void setBalAfter(Float balAfter) {
		this.balAfter = balAfter;
	}

	@Column(name = "BAL_CHANGE", nullable = false, precision = 10)
	public Float getBalChange() {
		return this.balChange;
	}

	public void setBalChange(Float balChange) {
		this.balChange = balChange;
	}

	@Column(name = "REMARKS", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "OPERATOR_NAME", length = 100)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "TRANS_TIME", nullable = false, length = 11)
	public Date getTransTime() {
		return transTime;
	}

	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	@Column(name = "TRANS_TYPE", length = 1)
	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}
	
	@Column(name = "TRANS_CONT_TYPE",nullable = false, length = 1)
	public String getTransContType() {
		return this.transContType;
	}

	public void setTransContType(String transContType) {
		this.transContType = transContType;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCardTrans", cascade = CascadeType.ALL)
	public Set<TCardTransGood> gettCardTransGoods() {
		return this.tCardTransGoods;
	}

	public void settCardTransGoods(
			Set<TCardTransGood> tCardTransGoods) {
		this.tCardTransGoods = tCardTransGoods;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCardTrans", cascade = CascadeType.ALL)
	public Set<TCardTransRound> gettCardTransRounds() {
		return this.tCardTransRounds;
	}

	public void settCardTransRounds(
			Set<TCardTransRound> tCardTransRounds) {
		this.tCardTransRounds = tCardTransRounds;
	}
}
