package com.wanda.ccs.model;

// Generated 2011-11-2 12:36:06 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCardTransTicket generated by hbm2java
 */
@Entity
@Table(name = "T_CARD_TRANS_TICKET")
public class TCardTransTicket extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 8894634561273533585L;
	
	private Long id;
	private TCard tCard;  //卡
	private TCinema tCinema; //影片上映影院
	private String orderId;	 //
	private String channel;
	private Date showTime;   //影片上映时间
	private String filmCode;  //影片代码
	private String filmName;  //影片名称
	private Long balBefore;   //购票前卡余额
	private Long balAfter;	  //购票后卡余额
	private Long balChange;   //余额变化
	private String remarks;   //备注
	private Long ticketNum;   //购票张数
	private Long ticketTypeId; //购票使用的票类编码
	private String soldBy;     //
	private Date soldTime;     //售票时间
	private String transType; //交易类型，S售票，R退票

	public TCardTransTicket() {
	}
	private long cardId;
	
	public TCardTransTicket(TCard tCard, TCinema tCinema, String orderId,
			String channel, Date showTime, String filmCode, String filmName,
			Long ticketNum, Long ticketTypeId, Date soldTime, Long cardId) {
		this.tCard = tCard;
		this.tCinema = tCinema;
		this.orderId = orderId;
		this.channel = channel;
		this.showTime = showTime;
		this.filmCode = filmCode;
		this.filmName = filmName;
		this.ticketNum = ticketNum;
		this.ticketTypeId = ticketTypeId;
		this.soldTime = soldTime;
		this.cardId =cardId;
	}

	public TCardTransTicket(TCard tCard, TCinema tCinema, String orderId,
			String channel, Date showTime, String filmCode, String filmName,
			Long balBefore, Long balAfter, Long balChange, String remarks,
			Long ticketNum, Long ticketTypeId, String soldBy, Date soldTime,
			String transType, Long cardId) {
		this.tCard = tCard;
		this.tCinema = tCinema;
		this.orderId = orderId;
		this.channel = channel;
		this.showTime = showTime;
		this.filmCode = filmCode;
		this.filmName = filmName;
		this.balBefore = balBefore;
		this.balAfter = balAfter;
		this.balChange = balChange;
		this.remarks = remarks;
		this.ticketNum = ticketNum;
		this.ticketTypeId = ticketTypeId;
		this.soldBy = soldBy;
		this.soldTime = soldTime;
		this.transType = transType;
		this.cardId =cardId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CARD_TRANS_TICKET", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CARD_TRANS_TICKET_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_ID", nullable = false, insertable = false, updatable = false)
	public TCard gettCard() {
		return this.tCard;
	}

	public void settCard(TCard tCard) {
		this.tCard = tCard;
	}
	
	@Column(name = "CARD_ID", nullable = false)
	public Long getCardId() {
		return cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA", nullable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "CHANNEL", nullable = false, length = 100)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "SHOW_TIME", nullable = false, length = 11)
	public Date getShowTime() {
		return this.showTime;
	}

	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}

	@Column(name = "FILM_CODE", nullable = false, length = 20)
	public String getFilmCode() {
		return this.filmCode;
	}

	public void setFilmCode(String filmCode) {
		this.filmCode = filmCode;
	}

	@Column(name = "FILM_NAME", nullable = false, length = 1024)
	public String getFilmName() {
		return this.filmName;
	}

	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}

	@Column(name = "BAL_BEFORE", precision = 10)
	public Long getBalBefore() {
		return this.balBefore;
	}

	public void setBalBefore(Long balBefore) {
		this.balBefore = balBefore;
	}

	@Column(name = "BAL_AFTER", precision = 10)
	public Long getBalAfter() {
		return this.balAfter;
	}

	public void setBalAfter(Long balAfter) {
		this.balAfter = balAfter;
	}

	@Column(name = "BAL_CHANGE", precision = 10)
	public Long getBalChange() {
		return this.balChange;
	}

	public void setBalChange(Long balChange) {
		this.balChange = balChange;
	}

	@Column(name = "REMARKS", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "TICKET_NUM", nullable = false, precision = 38, scale = 0)
	public Long getTicketNum() {
		return this.ticketNum;
	}

	public void setTicketNum(Long ticketNum) {
		this.ticketNum = ticketNum;
	}

	@Column(name = "TICKET_TYPE_ID", nullable = false, precision = 38, scale = 0)
	public Long getTicketTypeId() {
		return this.ticketTypeId;
	}

	public void setTicketTypeId(Long ticketTypeId) {
		this.ticketTypeId = ticketTypeId;
	}

	@Column(name = "SOLD_BY", length = 100)
	public String getSoldBy() {
		return this.soldBy;
	}

	public void setSoldBy(String soldBy) {
		this.soldBy = soldBy;
	}

	@Column(name = "SOLD_TIME", nullable = false, length = 11)
	public Date getSoldTime() {
		return this.soldTime;
	}

	public void setSoldTime(Date soldTime) {
		this.soldTime = soldTime;
	}

	@Column(name = "TRANS_TYPE", length = 1)
	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

}
