package com.wanda.ccs.model;

// Generated 2011-11-2 12:36:06 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TCardOrder generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "T_CARD_ORDER", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CARD_ORDER_ID", "CARD_TYPE_ID" }))
public class TCardOrder extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -3651051562470625626L;

	private Long id; // 制卡单的序列
	private TCinema tCinema; // 发起请求的影院
	private TCardType tCardType; // 卡类 ，与对应的票类相同
	private String startNo; // 开始卡号
	private String endNo; // 结束卡号
	private Long numOfCards; // 卡的数量
	private String regionCode;// 发起请求的影院所在区域
	private String status;// 制卡单申请状态
	private String description;// 说明
	private Long tCinemaId;// 发起请求的影院Id
	private Long tCardTypeId; // 卡类
	private String approvedBy;// 审核人
	private Date approvedDate;// 审核时间
	private String submitBy;// 提交人
	private Date submitDate;// 提交时间
	private Long numOfInitialized; // 已预制卡的数量
	private String submitById;
	private String approveById;
	private String oaId;
	
	private String isVirtual; // 是否为虚拟卡，Y:虚拟卡，N:实物卡
	
	public TCardOrder() {
	}

	public TCardOrder(TCardType tCardType, Long numOfCards, String status) {
		this.tCardType = tCardType;
		this.numOfCards = numOfCards;
		this.status = status;
	}

	public TCardOrder(TCinema tCinema, TCardType tCardType, Long numOfCards,
			String regionCode, String status, Long numOfInitialized) {
		this.tCinema = tCinema;
		this.tCardType = tCardType;
		this.numOfCards = numOfCards;
		this.regionCode = regionCode;
		this.status = status;
		this.numOfInitialized = numOfInitialized;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQUEST", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CARD_ORDER_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "START_NO")
	public String getStartNo() {
		return startNo;
	}

	public void setStartNo(String startNo) {
		this.startNo = startNo;
	}

	@Column(name = "END_NO")
	public String getEndNo() {
		return endNo;
	}

	public void setEndNo(String endNo) {
		this.endNo = endNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TCardType gettCardType() {
		return this.tCardType;
	}

	public void settCardType(TCardType tCardType) {
		this.tCardType = tCardType;
	}

	@Column(name = "CINEMA")
	public Long gettCinemaId() {
		return tCinemaId;
	}

	public void settCinemaId(Long tCinemaId) {
		this.tCinemaId = tCinemaId;
	}

	@Column(name = "CARD_TYPE_ID", nullable = false)
	public Long gettCardTypeId() {
		return tCardTypeId;
	}

	public void settCardTypeId(Long tCardTypeId) {
		this.tCardTypeId = tCardTypeId;
	}

	@Column(name = "NUM_OF_CARDS", nullable = false, precision = 38, scale = 0)
	public Long getNumOfCards() {
		return this.numOfCards;
	}

	public void setNumOfCards(Long numOfCards) {
		this.numOfCards = numOfCards;
	}

	@Column(name = "REGION_CODE", length = 20)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "APPROVE_BY", length = 40)
	public String getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Column(name = "APPROVE_DATE")
	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "SUBMIT_BY", length = 40)
	public String getSubmitBy() {
		return submitBy;
	}

	public void setSubmitBy(String submitBy) {
		this.submitBy = submitBy;
	}

	@Column(name = "SUBMIT_DATE")
	public Date getSubmitDate() {
		return submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	@Column(name = "NUM_OF_INITIALIZED", nullable = false, precision = 38, scale = 0)
	public Long getNumOfInitialized() {
		return numOfInitialized;
	}

	public void setNumOfInitialized(Long numOfInitialized) {
		this.numOfInitialized = numOfInitialized;
	}

	@Column(name = "SUBMIT_BY_ID", length = 100)
	public String getSubmitById() {
		return submitById;
	}

	public void setSubmitById(String submitById) {
		this.submitById = submitById;
	}

	@Column(name = "APPROVE_BY_ID", length = 100)
	public String getApproveById() {
		return approveById;
	}

	public void setApproveById(String approveById) {
		this.approveById = approveById;
	}

	@Column(name = "OA_ID", length = 100)
	public String getOaId() {
		return oaId;
	}

	public void setOaId(String oaId) {
		this.oaId = oaId;
	}
	@Override
	public String toString() {
		return "制卡申请单[" + getId() 
				+ "," + (gettCardType() == null ? "" : gettCardType().getTypeName()) 
				+ "," + getNumOfCards() + "张" 
				+ (startNo != null ? ("," + startNo + " - " + endNo + "]") : "]");
	}

	@Column(name = "IS_VIRTUAL",length=1)
	public String getIsVirtual() {
		return isVirtual;
	}

	public void setIsVirtual(String isVirtual) {
		this.isVirtual = isVirtual;
	}
	
	@Transient
	public Boolean getIsMaterial() {
		return getIsVirtual() == null 
				|| "N".equalsIgnoreCase(getIsVirtual());
	}
}
