package com.wanda.ccs.model;

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TCardTrans generated by hbm2java
 */
@Entity
@Table(name = "T_CARD_TRANS_ROUND")
public class TCardTransRound extends AbstractEntity implements java.io.Serializable{
	private static final long serialVersionUID = -7638834518475689141L;
	
	private Long id;
	private TCardTrans tCardTrans; //卡服务ID
	private Long hallId;     //POS需要影厅编号
	private String hallName; //POS需要影厅名称
	private String roundNo;  //POS需要场次
	private Date showTime;   //影片上映时间
	private String filmCode;  //影片代码
	private String filmName;  //影片名称
	private Long ticketNum;   //购票张数
	private String ticketTypeCode; //购票使用的票类编码
	private String ticketTypeName; //购票使用的票类名称
	private Long charge;    //用于支付该场次的总金额
	private Long discountTicketNum; //使用了折扣卡的票数
	private Long discountTotal;   //折扣卡相关的支付（或退款）总金额

	private long cardTransId;

	public TCardTransRound() {
	}

	public TCardTransRound(TCardTrans tCardTrans) {
		this.tCardTrans = tCardTrans;
	}

	public TCardTransRound(TCardTrans tCardTrans,Date showTime, String filmCode, String filmName,
			Long ticketNum, String ticketTypeCode, String ticketTypeName, Long charge) {
		this.tCardTrans = tCardTrans;
		this.showTime = showTime;
		this.filmCode = filmCode;
		this.filmName = filmName;
		this.ticketNum = ticketNum;
		this.ticketTypeCode = ticketTypeCode;
		this.ticketTypeName = ticketTypeName;
		this.charge =charge;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CARD_TRANS_ROUND", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CARD_TRANS_ROUND_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_TRANS_ID", insertable = false, updatable = false)
	public TCardTrans gettCardTrans() {
		return this.tCardTrans;
	}

	public void settCardTrans(TCardTrans tCardTrans) {
		this.tCardTrans = tCardTrans;
	}
	
	@Column(name = "CARD_TRANS_ID" )
	public Long getCardTransId() {
		return this.cardTransId;
	}

	public void setCardTransId(Long cardTransId) {
		this.cardTransId = cardTransId;
	}

	@Column(name = "SHOW_TIME", nullable = false, length = 11)
	public Date getShowTime() {
		return this.showTime;
	}

	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}

	@Column(name = "FILM_CODE", nullable = false, length = 20)
	public String getFilmCode() {
		return this.filmCode;
	}

	public void setFilmCode(String filmCode) {
		this.filmCode = filmCode;
	}

	@Column(name = "FILM_NAME", nullable = false, length = 1024)
	public String getFilmName() {
		return this.filmName;
	}

	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}
	
	@Column(name = "TICKET_NUM", nullable = false, precision = 38, scale = 0)
	public Long getTicketNum() {
		return this.ticketNum;
	}

	public void setTicketNum(Long ticketNum) {
		this.ticketNum = ticketNum;
	}

	@Column(name = "TICKET_TYPE_CODE", length = 50)
	public String getTicketTypeCode() {
		return this.ticketTypeCode;
	}

	public void setTicketTypeCode(String ticketTypeCode) {
		this.ticketTypeCode = ticketTypeCode;
	}
	
	@Column(name = "TICKET_TYPE_NAME", length = 1024)
	public String getTicketTypeName() {
		return ticketTypeName;
	}

	public void setTicketTypeName(String ticketTypeName) {
		this.ticketTypeName = ticketTypeName;
	}
	
	@Column(name = "HALL_ID", precision = 38, scale = 0)
	public Long getHallId() {
		return this.hallId;
	}

	public void setHallId(Long hallId) {
		this.hallId = hallId;
	}
	
	@Column(name = "HALL_NAME", length = 50)
	public String getHallName() {
		return this.hallName;
	}

	public void setHallName(String hallName) {
		this.hallName = hallName;
	}
	
	@Column(name = "ROUND_NO", length = 20)
	public String getRoundNo() {
		return this.roundNo;
	}

	public void setRoundNo(String roundNo) {
		this.roundNo = roundNo;
	}
	
	@Column(name = "CHARGE", precision = 10 )
	public Long getCharge() {
		return charge;
	}

	public void setCharge(Long charge) {
		this.charge = charge;
	}
	
	@Column(name = "DISCOUNT_TICKET_NUM", precision = 38, scale = 0)
	public Long getDiscountTicketNum() {
		return discountTicketNum;
	}

	public void setDiscountTicketNum(Long discountTicketNum) {
		this.discountTicketNum = discountTicketNum;
	}

	@Column(name = "DISCOUNT_TOTAL", precision = 10 )
	public Long getDiscountTotal() {
		return discountTotal;
	}

	public void setDiscountTotal(Long discountTotal) {
		this.discountTotal = discountTotal;
	}
}
