package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCinemaContact generated by hbm2java
 */
@Entity
@Table(name = "T_CINEMA_CONTACT")
public class TCinemaContact extends VersionableEntity implements
		java.io.Serializable {

	private Long id;
	private TCinema tCinema;
	private String name;
	private String phone;
	private String email;
	private String duty;
	private String address;
	private String postCode;
	private Long isdelete;
	private Date updateTime;
	private String sex;
	private String mobile;
	private Long cinemaId;

	public TCinemaContact() {
	}

	public TCinemaContact(TCinema tCinema, String name, String phone,
			String email, String duty, String address, String postCode,
			Long isdelete, Date updateTime, String sex, String mobile,Long cinemaId) {
		this.tCinema = tCinema;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.duty = duty;
		this.address = address;
		this.postCode = postCode;
		this.isdelete = isdelete;
		this.updateTime = updateTime;
		this.sex = sex;
		this.mobile = mobile;
		this.cinemaId = cinemaId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CINEMA_CONTACT")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_ID", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}
	@Column(name = "CINEMA_ID", length = 20)
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "NAME", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DUTY", length = 50)
	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "POST_CODE", length = 10)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "ISDELETE", precision = 38, scale = 0)
	public Long getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Long isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "SEX", precision = 38, scale = 0)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
