package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Where;

import com.xcesys.extras.core.dao.model.BlameableEntity;

/**
 * TCinema generated by hbm2java
 */
@Entity
@Table(name = "T_CINEMA", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "SHORT_NAME" }),
		@UniqueConstraint(columnNames = "OUT_NAME") })
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class TCinema extends BlameableEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String shortName;// 简称
	private String innerName;// 内部名称
	private String outName;// 外部名称
	private String pinCode;// 拼码
	private String innerCode;// 内码
	private String code;// 编码
	private String codeOfCFS;//客流系统中的影城编码
	private String codeOfBCS;//预算管控系统中的影城编码
	private String isOpen;// 是否开业
	private Date openDate;// 开业时间
	private Date contractBegin;// 合同起始时间
	private Date contractEnd;// 合同结束时间
	private Long hallCount;// 总厅数
	private Long digitHallCount;// 数字影厅数
	private Long tridHallCount;// 3D影厅数
	private Long imaxHallCount;// IMAX影厅数
	private Long seatCount;// 座位数
	private String address;// 地址
	private String postCode;// 邮编
	private String cinemaLevel;// 影院级别
	private String cinemaAttr;// 影院属性
	private String suppType;// 影院供片状态
	private String mktType; // 影院市场类型
	private TProvince province;// 省
	private Long provinceId;// 省ID
	private TCity city;// 城市
	private Long cityId;// 城市ID
	private String area;// 区域
	private TCinemaContact cinemaContact;// 联系人
	private Long cinemaContactId;// 联系人Id
	private String cinemaType;
	private Set<THall> tHalls = new HashSet<THall>(0);
	private Set<TCinemaContact> tCinemaContacts = new HashSet<TCinemaContact>(0);
	private Set<TScheduleInfoB> tScheduleInfoBs = new HashSet<TScheduleInfoB>(0);
	private String workStartDate;// 工作日的黄金时间的起始时间
	private String workEndDate;// 工作日的黄金时间的结束时间
	private String workendStartDate;// 休息日的黄金时间的起始时间
	private String workendEndDate;// 休息日的黄金时间的结束时间

	private boolean hasChild;
	private String pkCorp;
	//add by Chenxm 2012-04-11
	private Boolean isFeel;//是否使用触摸屏
	private String printNum = "1";//小票打印张数 0代表不打印，1代表打印一张，2代表打印两张
	private Long totalSize;
	private Long noteSize;
	
	private Float groupAccountRatio; // 院线分账比例
	
	public TCinema() {
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	@Column(name = "AREA", length = 20)
	public String getArea() {
		return this.area;
	}

	@Column(name = "CINEMA_ATTR", length = 20)
	public String getCinemaAttr() {
		return this.cinemaAttr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_CONTACT_ID", insertable = false, updatable = false)
	public TCinemaContact getCinemaContact() {
		return cinemaContact;
	}

	@Column(name = "CINEMA_CONTACT_ID", length = 20)
	public Long getCinemaContactId() {
		return cinemaContactId;
	}

	@Column(name = "CINEMA_LEVEL", length = 20)
	public String getCinemaLevel() {
		return this.cinemaLevel;
	}

	@Column(name = "CINEMA_TYPE", length = 20)
	public String getCinemaType() {
		return this.cinemaType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY", insertable = false, updatable = false)
	public TCity getCity() {
		return this.city;
	}

	@Column(name = "CITY", length = 20)
	public Long getCityId() {
		return cityId;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	@Column(name = "CONTRACT_BEGIN")
	public Date getContractBegin() {
		return this.contractBegin;
	}

	@Column(name = "CONTRACT_END")
	public Date getContractEnd() {
		return this.contractEnd;
	}

	@Column(name = "DIGIT_HALL_COUNT", precision = 38, scale = 0)
	public Long getDigitHallCount() {
		return digitHallCount;
	}

	@Column(name = "HALL_COUNT", precision = 38, scale = 0)
	public Long getHallCount() {
		return this.hallCount;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CINEMA")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	@Column(name = "IMAX_HALL_COUNT", precision = 38, scale = 0)
	public Long getImaxHallCount() {
		return imaxHallCount;
	}

	@Column(name = "INNER_CODE", length = 20)
	public String getInnerCode() {
		return this.innerCode;
	}

	@Column(name = "ISOPEN", length = 2)
	public String getIsOpen() {
		return this.isOpen;
	}

	@Column(name = "MKT_TYPE", length = 20)
	public String getMktType() {
		return this.mktType;
	}

	@Column(name = "INNER_NAME", length = 150)
	public String getInnerName() {
		return this.innerName;
	}

	@Column(name = "OUT_NAME", length = 150)
	public String getOutName() {
		return outName;
	}

	@Column(name = "OPEN_DATE", length = 7)
	public Date getOpenDate() {
		return this.openDate;
	}

	@Column(name = "PIN_CODE", length = 20)
	public String getPinCode() {
		return this.pinCode;
	}

	@Column(name = "POST_CODE", length = 10)
	public String getPostCode() {
		return this.postCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROVINCE", insertable = false, updatable = false)
	public TProvince getProvince() {
		return this.province;
	}

	@Column(name = "PROVINCE", length = 20)
	public Long getProvinceId() {
		return provinceId;
	}

	@Column(name = "SEAT_COUNT", precision = 38, scale = 0)
	public Long getSeatCount() {
		return this.seatCount;
	}

	@Column(name = "SHORT_NAME", length = 60)
	public String getShortName() {
		return this.shortName;
	}

	@Column(name = "SUPP_TYPE", length = 20)
	public String getSuppType() {
		return this.suppType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCinema")
	public Set<TCinemaContact> gettCinemaContacts() {
		return this.tCinemaContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCinema")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	@OrderBy(value = "name")
	@Where(clause="deleted!='1'")
	public Set<THall> gettHalls() {
		return this.tHalls;
	}

	@Column(name = "TRID_HALL_COUNT", precision = 38, scale = 0)
	public Long getTridHallCount() {
		return tridHallCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCinema")
	public Set<TScheduleInfoB> gettScheduleInfoBs() {
		return this.tScheduleInfoBs;
	}

	@Column(name = "WORK_START_DATE", precision = 10, scale = 0)
	public String getWorkStartDate() {
		return workStartDate;
	}

	public void setWorkStartDate(String workStartDate) {
		this.workStartDate = workStartDate;
	}

	@Column(name = "WORK_END_DATE", precision = 10, scale = 0)
	public String getWorkEndDate() {
		return workEndDate;
	}

	public void setWorkEndDate(String workEndDate) {
		this.workEndDate = workEndDate;
	}

	@Column(name = "WORKEND_START_DATE", precision = 10, scale = 0)
	public String getWorkendStartDate() {
		return workendStartDate;
	}

	public void setWorkendStartDate(String workendStartDate) {
		this.workendStartDate = workendStartDate;
	}

	@Column(name = "WORKEND_END_DATE", precision = 10, scale = 0)
	public String getWorkendEndDate() {
		return workendEndDate;
	}
	//add by Chenxm 2012-04-11
	@Column(name = "IS_FEEL")
	public Boolean getIsFeel() {
		return isFeel;
	}
	//add by Chenxm 2012-04-11
	public void setIsFeel(Boolean isFeel) {
		this.isFeel = isFeel;
	}
	
	@Column(name = "PRINT_NUM")
	public String getPrintNum() {
		return printNum;
	}

	public void setPrintNum(String printNum) {
		this.printNum = printNum;
	}
	
	@Column(name = "TOTAL_SIZE")
	public Long getTotalSize() {
		return totalSize;
	}

	public void setTotalSize(Long totalSize) {
		this.totalSize = totalSize;
	}
	
	@Column(name = "NOTE_SIZE")
	public Long getNoteSize() {
		return noteSize;
	}

	public void setNoteSize(Long noteSize) {
		this.noteSize = noteSize;
	}

	public void setWorkendEndDate(String workendEndDate) {
		this.workendEndDate = workendEndDate;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setOutName(String outName) {
		this.outName = outName;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public void setCinemaAttr(String cinemaAttr) {
		this.cinemaAttr = cinemaAttr;
	}

	public void setCinemaContact(TCinemaContact cinemaContact) {
		this.cinemaContact = cinemaContact;
	}

	public void setCinemaContactId(Long cinemaContactId) {
		this.cinemaContactId = cinemaContactId;
	}

	public void setCinemaLevel(String cinemaLevel) {
		this.cinemaLevel = cinemaLevel;
	}

	public void setCinemaType(String cinemaType) {
		this.cinemaType = cinemaType;
	}

	public void setCity(TCity city) {
		this.city = city;
	}

	public void setCityId(Long cityId) {
		this.cityId = cityId;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setContractBegin(Date contractBegin) {
		this.contractBegin = contractBegin;
	}

	public void setContractEnd(Date contractEnd) {
		this.contractEnd = contractEnd;
	}

	public void setDigitHallCount(Long digitHallCount) {
		this.digitHallCount = digitHallCount;
	}

	public void setHallCount(Long hallCount) {
		this.hallCount = hallCount;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setImaxHallCount(Long imaxHallCount) {
		this.imaxHallCount = imaxHallCount;
	}

	public void setInnerCode(String innerCode) {
		this.innerCode = innerCode;
	}

	public void setIsOpen(String isopen) {
		this.isOpen = isopen;
	}

	public void setMktType(String mktType) {
		this.mktType = mktType;
	}

	public void setInnerName(String name) {
		this.innerName = name;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public void setProvince(TProvince province) {
		this.province = province;
	}

	public void setProvinceId(Long provinceId) {
		this.provinceId = provinceId;
	}

	public void setSeatCount(Long seatCount) {
		this.seatCount = seatCount;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public void setSuppType(String suppType) {
		this.suppType = suppType;
	}

	public void settCinemaContacts(Set<TCinemaContact> tCinemaContacts) {
		this.tCinemaContacts = tCinemaContacts;
	}

	public void settHalls(Set<THall> tHalls) {
		this.tHalls = tHalls;
	}

	public void setTridHallCount(Long tridHallCount) {
		this.tridHallCount = tridHallCount;
	}

	public void settScheduleInfoBs(Set<TScheduleInfoB> tScheduleInfoBs) {
		this.tScheduleInfoBs = tScheduleInfoBs;
	}

	@Override
	public String toString() {
		return "影院[shortName=" + shortName + "]";
	}

	@Transient
	public boolean getHasChild() {
		return hasChild;
	}

	public void setHasChild(boolean hasChild) {
		this.hasChild = hasChild;
	}
	
	@Transient
	public String getPkCorp() {
		return pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "CODE_OF_CFS", length = 20)
	public String getCodeOfCFS() {
		return codeOfCFS;
	}

	@Column(name = "CODE_OF_BCS", length = 20)
	public String getCodeOfBCS() {
		return codeOfBCS;
	}

	public void setCodeOfCFS(String codeOfCFS) {
		this.codeOfCFS = codeOfCFS;
	}

	public void setCodeOfBCS(String codeOfBCS) {
		this.codeOfBCS = codeOfBCS;
	}
	
	@Column(name="GROUP_ACCOUNT_RATIO", precision = 22, scale = 0)
	public Float getGroupAccountRatio() {
		return groupAccountRatio;
	}

	public void setGroupAccountRatio(Float groupAccountRatio) {
		this.groupAccountRatio = groupAccountRatio;
	}
}
