package com.wanda.ccs.model;

// Generated 2013-5-21 18:55:28 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.BlameableEntity;
import com.xcesys.extras.core.util.StringUtil;

/**
 * TCmnPhase generated by hbm2java
 * 活动阶段
 */
@Entity
@Table(name = "T_CMN_PHASE")
public class TCmnPhase extends BlameableEntity implements java.io.Serializable {
	private static final long serialVersionUID = -5648026991583076675L;
	
	private Long id;
	private TCampaign tCampaign;//活动
	private Long campaignId;//活动id
	private String name;//名称
	private String code;//编码
	private Date startDate;//开始日期
	private Date endDate;//结束日期
	private String status;//阶段状态
	private String description;//描述
	private Set<TCmnActivity> tCmnActivities = new HashSet<TCmnActivity>(0);
	
	private String strStartDate;
	private String strEndDate;
	public TCmnPhase() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_CMN_PHASE", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CMN_PHAISE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAMPAIGN_ID", nullable = false, insertable = false, updatable = false)
	public TCampaign gettCampaign() {
		return this.tCampaign;
	}

	public void settCampaign(TCampaign tCampaign) {
		this.tCampaign = tCampaign;
	}
	
	@Column(name = "CAMPAIGN_ID")
	public Long getCampaignId() {
		return campaignId;
	}

	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}
	
	@Column(name = "NAME", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "START_DATE")
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE")
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tCmnPhase")
	@OrderBy(value="startDtime, name asc")
	public Set<TCmnActivity> gettCmnActivities() {
		return this.tCmnActivities;
	}

	public void settCmnActivities(Set<TCmnActivity> tCmnActivities) {
		this.tCmnActivities = tCmnActivities;
	}
	
	
	@Transient
	public String getStrStartDate() {
		if(startDate != null)
			strStartDate = new SimpleDateFormat("yyyy-MM-dd").format(startDate);
		return strStartDate;
	}

	public void setStrStartDate(String strStartDate) {
		try {
			if(!StringUtil.isNullOrBlank(strStartDate))
				startDate = new SimpleDateFormat("yyyy-MM-dd").parse(strStartDate);
			else
				startDate = null;
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.strStartDate = strStartDate;
	}

	@Transient
	public String getStrEndDate() {
		if(endDate != null)
			strEndDate = new SimpleDateFormat("yyyy-MM-dd").format(endDate);
		return strEndDate;
	}

	public void setStrEndDate(String strEndDate) {
		try {
			if(!StringUtil.isNullOrBlank(strEndDate))
				endDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(strEndDate+" 23:59:59");
			else
				endDate = null;
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.strEndDate = strEndDate;
	}
	
	@Override
	public String toString(){
//		${phase.code}|${phase.name}|${DIMS[m.DIMTYPE_CAMPAIGN_STATUS][phase.status]}
		return code + "|" + name ;
	}
}
