package com.wanda.ccs.model;

// Generated Jan 17, 2013 9:23:33 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TConProvider generated by hbm2java
 */
@Entity
@Table(name = "T_CON_PROVIDER")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConProvider extends ConAbstractStateEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String providerCode;
	private String providerName;
	private String shortName;
	private String abbreviation; // 外文简称
	private String regCode;	// 工商注册号
	private String orgCode;		// 组织机构代码
	private String legalRep;	//  法人代表
	private String telphoneNo;
	private String fax;	// 传真
	private String postcode; // 邮编
	private String address;	// 地址
	private String postAddress; // 邮寄地址
	private Long orgConProviderId;
	private Boolean valid;
	private String taxCode;	// 税务登记号
	private Integer regCapital;	// 注册资金
	private String comments;	// 备注
	private String oaProcessNo;	// OA流程
	private Long submitCinemaId; // 提交影城
	private TCinema submitTCinema;
	
	/**
	 * 是否适用于本影城
	 */
	private Boolean includeMe;
	/**
	 * 供应范围
	 */
	private Set<TConPa> tConPas = new HashSet<TConPa>(0);
	
	
	/**
	 * 主干版本
	 */
	private TConProvider trunk;
	/**
	 * 分支版本
	 */
	private Set<TConProvider> branches = new HashSet<TConProvider>(0);


	public TConProvider() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_PROVIDER",allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_PROVIDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PROVIDER_NAME", nullable = false, length = 300)
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "SHORT_NAME", length = 80)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "VALID", nullable = false, length = 1)
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Column(name = "ORG_CODE", length = 100)
	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	@Column(name = "LEGAL_REP", length = 200)
	public String getLegalRep() {
		return this.legalRep;
	}

	public void setLegalRep(String legalRep) {
		this.legalRep = legalRep;
	}

	@Column(name = "TELPHONE_NO", length = 100)
	public String getTelphoneNo() {
		return this.telphoneNo;
	}

	public void setTelphoneNo(String telphoneNo) {
		this.telphoneNo = telphoneNo;
	}

	@Column(name = "FAX", length = 100)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "POSTCODE", length = 20)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "ADDRESS", length = 2048)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "POST_ADDRESS", length = 2048)
	public String getPostAddress() {
		return this.postAddress;
	}

	public void setPostAddress(String postAddress) {
		this.postAddress = postAddress;
	}

	@Column(name = "PROVIDER_CODE", nullable = false, length = 40)
	public String getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(String providerCode) {
		this.providerCode = providerCode;
	}


	@Column(name = "ORG_CON_PROVIDER_ID", precision = 22, scale = 0)
	public Long getOrgConProviderId() {
		return this.orgConProviderId;
	}

	public void setOrgConProviderId(Long orgConProviderId) {
		this.orgConProviderId = orgConProviderId;
	}

	@Column(name = "REG_CODE", nullable = false, length = 30)
	public String getRegCode() {
		return this.regCode;
	}

	public void setRegCode(String regCode) {
		this.regCode = regCode;
	}

	@Column(name = "TAX_CODE", length = 30)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "REG_CAPITAL", precision = 18)
	public Integer getRegCapital() {
		return this.regCapital;
	}

	public void setRegCapital(Integer regCapital) {
		this.regCapital = regCapital;
	}

	@Column(name = "COMMENTS", length = 2048)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "OA_PROCESS_NO", length = 100)
	public String getOaProcessNo() {
		return this.oaProcessNo;
	}

	public void setOaProcessNo(String oaProcessNo) {
		this.oaProcessNo = oaProcessNo;
	}

	@Override
	@Transient
	public String getEntityName() {
		return "供应商";
	}

	@Column(name = "ABBREVIATION", length = 40)
	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "ORG_CON_PROVIDER_ID",updatable=false,insertable=false)
	public TConProvider getTrunk() {
		return trunk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trunk")
	@OrderBy("updatedDate desc")
	public Set<TConProvider> getBranches() {
		return branches;
	}

	public void setBranches(Set<TConProvider> branches) {
		this.branches = branches;
	}

	public void setTrunk(TConProvider trunk) {
		this.trunk = trunk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConProvider")
	public Set<TConPa> gettConPas() {
		return tConPas;
	}

	public void settConPas(Set<TConPa> tConPas) {
		this.tConPas = tConPas;
	}
	
	@Transient
	public Boolean getIncludeMe() {
		return includeMe;
	}

	public void setIncludeMe(Boolean includeMe) {
		this.includeMe = includeMe;
	}
	
	@Column(name="SUBMIT_CINEMA_ID", precision = 38, scale = 0)
	public Long getSubmitCinemaId() {
		return submitCinemaId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SUBMIT_CINEMA_ID" , insertable = false , updatable = false)
	public TCinema getSubmitTCinema() {
		return submitTCinema;
	}

	public void setSubmitCinemaId(Long submitCinemaId) {
		this.submitCinemaId = submitCinemaId;
	}

	public void setSubmitTCinema(TCinema submitTCinema) {
		this.submitTCinema = submitTCinema;
	}
}
