package com.wanda.ccs.model;

// Generated Jan 25, 2013 9:54:35 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TConTaskOutRealtime generated by hbm2java
 */
@Entity
@Table(name = "T_CON_TASK_OUT_REALTIME")
public class TConTaskOutRealtime extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String cinemaCode;
	private String taskStatus;
	private Date createDate;
	private Date updateDate;

	public TConTaskOutRealtime() {
	}
	
	public TConTaskOutRealtime(String code,Date date) {
		this.cinemaCode = code;
		this.taskStatus = "0";
		this.createDate = date;
		this.updateDate = date;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_TASK_OUT_REALTIME",allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CINEMA_CODE", length = 20)
	public String getCinemaCode() {
		return this.cinemaCode;
	}

	public void setCinemaCode(String cinemaCode) {
		this.cinemaCode = cinemaCode;
	}

	@Column(name = "TASK_STATUS", length = 10)
	public String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	@Column(name = "CREATE_DATE")
	public Date getCreateDate() {
		return createDate;
	}

	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
