package com.wanda.ccs.model;

// Generated Dec 5, 2012 10:35:22 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.aggrepoint.adk.FileParameter;
import com.xcesys.extras.core.dao.model.VersionableEntity;
import com.xcesys.extras.util.BlobFieldUtil;

/**
 * TConBrand generated by hbm2java
 */
@Entity
@Table(name = "T_CON_FILE_ATTACH")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConFileAttach extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -6829798087973777379L;
	
	private Long id;
	private Long refObjectId;
	private String refObjectType;
	private String fileName;
	private Blob fileData;
	private Long fileSize;
	private String fileDesc;
	private String contentType;
	
	
	
	public TConFileAttach() {
	}
	public TConFileAttach(String refObjectType) {
		this.refObjectType = refObjectType;
	}
	
	public void copy(TConFileAttach fileAttach) {
		if(fileAttach == null)
			return ;
		this.refObjectType = fileAttach.getRefObjectType();
		this.fileName = fileAttach.getFileName();
		this.fileData = fileAttach.getFileData();
		this.fileSize = fileAttach.getFileSize();
		this.fileDesc = fileAttach.getFileDesc();
		this.contentType = fileAttach.getContentType();
	}
	
	
	public TConFileAttach(TConFileAttach fileAttach) {
		if(fileAttach == null)
			return ;
		this.refObjectType = fileAttach.getRefObjectType();
		this.fileName = fileAttach.getFileName();
		this.fileData = fileAttach.getFileData();
		this.fileSize = fileAttach.getFileSize();
		this.fileDesc = fileAttach.getFileDesc();
		this.contentType = fileAttach.getContentType();
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_FILE_ATTACH", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_FILE_ATTACH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "REF_OBJECT_ID")
	public Long getRefObjectId() {
		return refObjectId;
	}

	public void setRefObjectId(Long refObjectId) {
		this.refObjectId = refObjectId;
	}

	@Column(name = "REF_OBJECT_TYPE")
	public String getRefObjectType() {
		return refObjectType;
	}

	public void setRefObjectType(String refObjectType) {
		this.refObjectType = refObjectType;
	}
	
	@Column(name = "FILE_NAME")
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_DATA")
	public Blob getFileData() {
		return fileData;
	}

	public void setFileData(Blob fileData) {
		this.fileData = fileData;
	}

	@Column(name = "FILE_SIZE")
	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}
	
	@Column(name = "FILE_DESC")
	public String getFileDesc() {
		return fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

	@Column(name = "CONTENT_TYPE")
	public String getContentType() {
		return contentType;
	}


	public void setContentType(String contentType) {
		this.contentType = contentType;
	}
	
	public void copyFile(FileParameter file)
			throws Exception {
		if(file == null)
			return;
			
		if (file.m_lSize < 0) {
			throw new Exception("文件最大大小为10M");
		}
		// 输入文件
		File contrFile = new File(file.m_strFullPath);

		if (contrFile.exists()) {
			byte[] bytes = new byte[(int) file.m_lSize];
			int offset = 0;
			int numRead = 0;
			InputStream is = new FileInputStream(contrFile);
			try {
				while (offset < bytes.length
						&& (numRead = is.read(bytes, offset, bytes.length
								- offset)) >= 0) {
					offset += numRead;
				}
				if (offset < bytes.length) {
					throw new IOException("Could not completely read file "
							+ file.getFileName());
				}
			} catch (Exception e) {
				throw new Exception(e);
			} finally {
				is.close();
			}
			
			this.setFileData(BlobFieldUtil.bytesToBlob(bytes));
			this.setFileSize(file.m_lSize);
			this.setFileName(file.getFileName());
			this.setContentType(file.m_strContentType);
		}
	}

}
