package com.wanda.ccs.model;

// Generated Nov 30, 2012 1:59:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.BlameableEntity;

/**
 * TConCompoundDefDetail generated by hbm2java
 */
@Entity
@Table(name = "T_CON_COMPOUND_DEF_DETAIL")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConCompoundDefDetail extends BlameableEntity implements
		java.io.Serializable{
	private static final long serialVersionUID = 1420338053292590595L;
	
	private Long id;
	private TConCompoundDef tConCompoundDef;
	private TConItem tConItem;
	private Float quantityTop;
	private Float quantityLower;
//	private String unit;
	private String detailType = IConDimType.CON_COMPOUND_DEF_DETAIL_TYPE_ORDINARY;//1普通  2中间品  3中间品成份
	private Set<TConCompoundDetail> tConCompoundDetails = new HashSet<TConCompoundDetail>(
			0);

	public TConCompoundDefDetail() {
	}
	
	public void copy(TConCompoundDefDetail detail){
		if(detail == null)
			return;
		this.quantityLower = detail.getQuantityLower();
		this.quantityTop = detail.getQuantityTop();
	}
	
	public TConCompoundDefDetail(TConCompoundDefDetail defDetail, TConCompoundDef conCompoundDef) {
		this.tConItem = defDetail.gettConItem();
		this.quantityLower = defDetail.getQuantityLower();
		this.quantityTop = defDetail.getQuantityTop();
		this.tConCompoundDef = conCompoundDef;
	}
	
	public TConCompoundDefDetail(Float quantityTop) {
		this.quantityTop = quantityTop;
	}

	public TConCompoundDefDetail(TConCompoundDef tConCompoundDef,
			Float quantityTop, Float quantityLower, 
			Set<TConCompoundDetail> tConCompoundDetails) {
		this.tConCompoundDef = tConCompoundDef;
		this.quantityTop = quantityTop;
		this.quantityLower = quantityLower;
		this.tConCompoundDetails = tConCompoundDetails;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_COMPOUND_DEF_DETAIL")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_COMPOUND_DEF_DETAIL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_COMPOUND_DEF_ID")
	public TConCompoundDef gettConCompoundDef() {
		return this.tConCompoundDef;
	}

	public void settConCompoundDef(TConCompoundDef tConCompoundDef) {
		this.tConCompoundDef = tConCompoundDef;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_ITEM_ID")
	public TConItem gettConItem() {
		return tConItem;
	}

	public void settConItem(TConItem tConItem) {
		this.tConItem = tConItem;
	}

	@Column(name = "QUANTITY_TOP", nullable = false, precision = 10)
	public Float getQuantityTop() {
		return this.quantityTop;
	}

	public void setQuantityTop(Float quantityTop) {
		this.quantityTop = quantityTop;
	}

	@Column(name = "QUANTITY_LOWER", precision = 10)
	public Float getQuantityLower() {
		return this.quantityLower;
	}

	public void setQuantityLower(Float quantityLower) {
		this.quantityLower = quantityLower;
	}

//	@Column(name = "UNIT", nullable = false, length = 20)
//	public String getUnit() {
//		return this.unit;
//	}
//
//	public void setUnit(String unit) {
//		this.unit = unit;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConCompoundDefDetail")
	public Set<TConCompoundDetail> gettConCompoundDetails() {
		return this.tConCompoundDetails;
	}

	public void settConCompoundDetails(
			Set<TConCompoundDetail> tConCompoundDetails) {
		this.tConCompoundDetails = tConCompoundDetails;
	}
	
	@Column(name = "DETAIL_TYPE")
	public String getDetailType() {
		return detailType;
	}

	public void setDetailType(String detailType) {
		this.detailType = detailType;
	}
}
