package com.wanda.ccs.model;

// Generated 2013-3-21 14:32:10 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Where;

import com.xcesys.extras.core.dao.model.BlameableEntity;
import com.xcesys.extras.core.util.StringUtil;

/**
 * TConSaleUnitGroup generated by hbm2java
 */
@Entity
@Table(name = "T_CON_SALE_UNIT_GROUP", uniqueConstraints = @UniqueConstraint(columnNames = "SALE_UNIT_GROUP_CODE"))
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConSaleUnitGroup extends BlameableEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 4170142582960314705L;
	
	private Long id;
	private String groupDesc;
	private String groupName;
	private Long cinemaId;
	private TCinema tCinema;
	private String saleUnitGroupCode;
	private Boolean valid = true;
	private Set<TConSaleUnit> tConSaleUnits = new HashSet<TConSaleUnit>(0);
	private String strValid;


	public TConSaleUnitGroup() {
		
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_SALE_UNIT_GROUP" , allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_SALE_UNIT_GROUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "GROUP_DESC", length = 2048)
	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	@Column(name = "GROUP_NAME", nullable = false, length = 300)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "CINEMA_ID", nullable = false, precision = 22, scale = 0)
	public Long getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "SALE_UNIT_GROUP_CODE", unique = true, nullable = false, length = 40)
	public String getSaleUnitGroupCode() {
		return this.saleUnitGroupCode;
	}

	public void setSaleUnitGroupCode(String saleUnitGroupCode) {
		this.saleUnitGroupCode = saleUnitGroupCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_ID", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "VALID", nullable = false)
	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConSaleUnitGroup")
	@Where(clause="valid='1'")
	public Set<TConSaleUnit> gettConSaleUnits() {
		return tConSaleUnits;
	}

	public void settConSaleUnits(Set<TConSaleUnit> tConSaleUnits) {
		this.tConSaleUnits = tConSaleUnits;
	}
	
	@Override
	public String toString() {
		return this.getSaleUnitGroupCode() + "," + this.getGroupName();
	}
	
	@Transient
	public String getStrValid() {
		if(this.valid){
			strValid = "Y";
		}else{
			strValid = "N";
		}
		return strValid;
	}

	public void setStrValid(String strValid) {
		this.strValid = strValid;
		if(StringUtil.isNullOrBlank(strValid) || strValid.equals("Y"))
			this.valid = true;
		else
			this.valid = false;
	}
}
