package com.wanda.ccs.model;

// Generated Feb 1, 2013 11:23:05 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TConSaleUnitLog generated by hbm2java
 */
@Entity
@Table(name = "T_CON_SALE_UNIT_LOG")
public class TConSaleUnitLog extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 3815421233310071036L;
	
	private Long id;
	private TConSaleUnit tConSaleUnit;
	private String saleUnitCode;
	private Long conItemId;
	private String comments;
	private String saleUnitName;
	private String saleChannel;
	private Boolean allowPrepaidCardDiscount;
	private Boolean allowSaleCategoryDiscount;
	private Boolean allowOnlineSale;
	private Boolean bindPrepaidCard;
	private Boolean allowAuthorizedSale;
	private Boolean valid;
	private Float unitPrice;
	private Long cinemaId;
	private String status;
	private String timeBegin;
	private String timeEnd;
	private String dateBegin;
	private String dateEnd;
	private String timeRuleType;
	private String saleType;
	private String promotionType;
	private Long conSaleUnitGroupId;

	public TConSaleUnitLog() {
	}
	
	public TConSaleUnitLog(TConSaleUnit tConSaleUnit) {
		this.tConSaleUnit = tConSaleUnit;
		this.saleUnitCode = tConSaleUnit.getSaleUnitCode();
		this.conItemId = tConSaleUnit.getConItemId();
		this.comments = tConSaleUnit.getComments();
		this.saleUnitName = tConSaleUnit.getSaleUnitName();
		this.saleChannel = tConSaleUnit.getSaleChannel();
		this.allowPrepaidCardDiscount = tConSaleUnit.getAllowPrepaidCardDiscount();
		this.allowSaleCategoryDiscount = tConSaleUnit.getAllowSaleCategoryDiscount();
		this.allowOnlineSale = tConSaleUnit.getAllowOnlineSale();
		this.bindPrepaidCard = tConSaleUnit.getBindPrepaidCard();
		this.allowAuthorizedSale = tConSaleUnit.getAllowAuthorizedSale();
		this.valid = tConSaleUnit.getValid();
		this.unitPrice = tConSaleUnit.getUnitPrice();
		this.cinemaId = tConSaleUnit.getCinemaId();
		this.status = tConSaleUnit.getStatus();
		this.timeBegin = tConSaleUnit.getTimeBegin();
		this.timeEnd = tConSaleUnit.getTimeEnd();
		this.dateBegin = tConSaleUnit.getDateBegin();
		this.dateEnd = tConSaleUnit.getDateEnd();
		this.timeRuleType = tConSaleUnit.getTimeRuleType();
		this.saleType = tConSaleUnit.getSaleType();
		this.promotionType = tConSaleUnit.getPromotionType();
		this.conSaleUnitGroupId = tConSaleUnit.getConSaleUnitGroupId();
	}

	public TConSaleUnitLog(TConSaleUnit tConSaleUnit, String saleUnitCode,
			Long conItemId, String saleUnitName, String saleChannel,
			Boolean allowPrepaidCardDiscount,
			Boolean allowSaleCategoryDiscount, Boolean allowOnlineSale,
			Boolean bindPrepaidCard, Boolean allowAuthorizedSale,
			Boolean valid, Float unitPrice, Long cinemaId, String status,
			String timeRuleType) {
		this.tConSaleUnit = tConSaleUnit;
		this.saleUnitCode = saleUnitCode;
		this.conItemId = conItemId;
		this.saleUnitName = saleUnitName;
		this.saleChannel = saleChannel;
		this.allowPrepaidCardDiscount = allowPrepaidCardDiscount;
		this.allowSaleCategoryDiscount = allowSaleCategoryDiscount;
		this.allowOnlineSale = allowOnlineSale;
		this.bindPrepaidCard = bindPrepaidCard;
		this.allowAuthorizedSale = allowAuthorizedSale;
		this.valid = valid;
		this.unitPrice = unitPrice;
		this.cinemaId = cinemaId;
		this.status = status;
		this.timeRuleType = timeRuleType;
	}

	public TConSaleUnitLog(TConSaleUnit tConSaleUnit, String saleUnitCode,
			Long conItemId, String comments, String saleUnitName,
			String saleChannel, Boolean allowPrepaidCardDiscount,
			Boolean allowSaleCategoryDiscount, Boolean allowOnlineSale,
			Boolean bindPrepaidCard, Boolean allowAuthorizedSale,
			Boolean valid, Float unitPrice, Long cinemaId, String status,
			String timeBegin, String timeEnd, String dateBegin, String dateEnd,
			String timeRuleType, String saleType, String promotionType) {
		this.tConSaleUnit = tConSaleUnit;
		this.saleUnitCode = saleUnitCode;
		this.conItemId = conItemId;
		this.comments = comments;
		this.saleUnitName = saleUnitName;
		this.saleChannel = saleChannel;
		this.allowPrepaidCardDiscount = allowPrepaidCardDiscount;
		this.allowSaleCategoryDiscount = allowSaleCategoryDiscount;
		this.allowOnlineSale = allowOnlineSale;
		this.bindPrepaidCard = bindPrepaidCard;
		this.allowAuthorizedSale = allowAuthorizedSale;
		this.valid = valid;
		this.unitPrice = unitPrice;
		this.cinemaId = cinemaId;
		this.status = status;
		this.timeBegin = timeBegin;
		this.timeEnd = timeEnd;
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.timeRuleType = timeRuleType;
		this.saleType = saleType;
		this.promotionType = promotionType;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_SALE_UNIT_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_SALE_UNIT_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_SALE_UNIT_ID", nullable = false)
	public TConSaleUnit gettConSaleUnit() {
		return this.tConSaleUnit;
	}

	public void settConSaleUnit(TConSaleUnit tConSaleUnit) {
		this.tConSaleUnit = tConSaleUnit;
	}

	@Column(name = "SALE_UNIT_CODE", nullable = false, length = 40)
	public String getSaleUnitCode() {
		return this.saleUnitCode;
	}

	public void setSaleUnitCode(String saleUnitCode) {
		this.saleUnitCode = saleUnitCode;
	}
	
	@Column(name = "CON_ITEM_ID", nullable = false, precision = 22, scale = 0)
	public Long getConItemId() {
		return this.conItemId;
	}

	public void setConItemId(Long conItemId) {
		this.conItemId = conItemId;
	}

	@Column(name = "COMMENTS", length = 2048)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "SALE_UNIT_NAME", nullable = false, length = 300)
	public String getSaleUnitName() {
		return this.saleUnitName;
	}

	public void setSaleUnitName(String saleUnitName) {
		this.saleUnitName = saleUnitName;
	}

	@Column(name = "SALE_CHANNEL", nullable = false, length = 20)
	public String getSaleChannel() {
		return this.saleChannel;
	}

	public void setSaleChannel(String saleChannel) {
		this.saleChannel = saleChannel;
	}

	@Column(name = "ALLOW_PREPAID_CARD_DISCOUNT", nullable = false, length = 1)
	public Boolean getAllowPrepaidCardDiscount() {
		return this.allowPrepaidCardDiscount;
	}

	public void setAllowPrepaidCardDiscount(Boolean allowPrepaidCardDiscount) {
		this.allowPrepaidCardDiscount = allowPrepaidCardDiscount;
	}

	@Column(name = "ALLOW_SALE_CATEGORY_DISCOUNT", nullable = false, length = 1)
	public Boolean getAllowSaleCategoryDiscount() {
		return this.allowSaleCategoryDiscount;
	}

	public void setAllowSaleCategoryDiscount(Boolean allowSaleCategoryDiscount) {
		this.allowSaleCategoryDiscount = allowSaleCategoryDiscount;
	}

	@Column(name = "ALLOW_ONLINE_SALE", nullable = false, length = 1)
	public Boolean getAllowOnlineSale() {
		return this.allowOnlineSale;
	}

	public void setAllowOnlineSale(Boolean allowOnlineSale) {
		this.allowOnlineSale = allowOnlineSale;
	}

	@Column(name = "BIND_PREPAID_CARD", nullable = false, length = 1)
	public Boolean getBindPrepaidCard() {
		return this.bindPrepaidCard;
	}

	public void setBindPrepaidCard(Boolean bindPrepaidCard) {
		this.bindPrepaidCard = bindPrepaidCard;
	}

	@Column(name = "ALLOW_AUTHORIZED_SALE", nullable = false, length = 1)
	public Boolean getAllowAuthorizedSale() {
		return this.allowAuthorizedSale;
	}

	public void setAllowAuthorizedSale(Boolean allowAuthorizedSale) {
		this.allowAuthorizedSale = allowAuthorizedSale;
	}

	@Column(name = "VALID", nullable = false, length = 1)
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 10)
	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "CINEMA_ID", nullable = false, precision = 22, scale = 0)
	public Long getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TIME_BEGIN", length = 7)
	public String getTimeBegin() {
		return this.timeBegin;
	}

	public void setTimeBegin(String timeBegin) {
		this.timeBegin = timeBegin;
	}

	@Column(name = "TIME_END", length = 7)
	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	@Column(name = "DATE_BEGIN", length = 7)
	public String getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(String dateBegin) {
		this.dateBegin = dateBegin;
	}

	@Column(name = "DATE_END", length = 7)
	public String getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(String dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "TIME_RULE_TYPE", nullable = false, length = 20)
	public String getTimeRuleType() {
		return this.timeRuleType;
	}

	public void setTimeRuleType(String timeRuleType) {
		this.timeRuleType = timeRuleType;
	}

	@Column(name = "SALE_TYPE", length = 20)
	public String getSaleType() {
		return this.saleType;
	}

	public void setSaleType(String saleType) {
		this.saleType = saleType;
	}

	@Column(name = "PROMOTION_TYPE", length = 20)
	public String getPromotionType() {
		return this.promotionType;
	}

	public void setPromotionType(String promotionType) {
		this.promotionType = promotionType;
	}

	@Column(name = "CON_SALE_UNIT_GROUP_ID", length = 20)
	public Long getConSaleUnitGroupId() {
		return conSaleUnitGroupId;
	}

	public void setConSaleUnitGroupId(Long conSaleUnitGroupId) {
		this.conSaleUnitGroupId = conSaleUnitGroupId;
	}

}
