package com.wanda.ccs.model;

// Generated Dec 5, 2012 1:48:48 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TConPa generated by hbm2java
 */
@Entity
@Table(name = "T_CON_PA")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConPa extends ConAbstractStateEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 6757576617040411697L;

	private Long id;
	private Long providerId;
	private TConProvider tConProvider;
	private Boolean valid;
	private String paCode;
	private String paName;
	private String paType;
	private Date effectiveDayBegin;
	private Date effectiveDayEnd;
	private Boolean applyAllCinema;
	private Date signedDay;
	private Long orgConPaId;
	private String oaProcessNo;
	private Long submitCinemaId;
	private TCinema submitTCinema;
	
	private Set<TConPaCinema> tConPaCinemas = new HashSet<TConPaCinema>(0);
	private Set<TConPaItem> tConPaItems = new HashSet<TConPaItem>(0);
	private List<TConFileAttach> tConFileAttachs;
	
	
	/**
	 * 是否适用于本影城
	 */
	private Boolean includeMe;

	/**
	 * 主干版本
	 */
	private TConPa trunk;
	/**
	 * 分支版本
	 */
	private Set<TConPa> branches = new HashSet<TConPa>(0);

	public TConPa() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_PA", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_PA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_PROVIDER_ID", insertable = false, updatable = false)
	public TConProvider gettConProvider() {
		return this.tConProvider;
	}

	public void settConProvider(TConProvider tConProvider) {
		this.tConProvider = tConProvider;
	}

	@Column(name = "VALID", length = 1)
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Column(name = "PA_CODE", nullable = false, length = 40)
	public String getPaCode() {
		return this.paCode;
	}

	public void setPaCode(String paCode) {
		this.paCode = paCode;
	}

	@Column(name = "PA_NAME", length = 2048)
	public String getPaName() {
		return this.paName;
	}

	public void setPaName(String paName) {
		this.paName = paName;
	}

	@Column(name = "PA_TYPE", nullable = false, length = 20)
	public String getPaType() {
		return this.paType;
	}

	public void setPaType(String paType) {
		this.paType = paType;
	}

	@Column(name = "EFFECTIVE_DAY_BEGIN", nullable = false, length = 7)
	public Date getEffectiveDayBegin() {
		return this.effectiveDayBegin;
	}

	public void setEffectiveDayBegin(Date effectiveDayBegin) {
		this.effectiveDayBegin = effectiveDayBegin;
	}

	@Column(name = "EFFECTIVE_DAY_END", nullable = false, length = 7)
	public Date getEffectiveDayEnd() {
		return this.effectiveDayEnd;
	}

	public void setEffectiveDayEnd(Date effectiveDayEnd) {
		this.effectiveDayEnd = effectiveDayEnd;
	}

	@Column(name = "SIGNED_DAY", length = 7)
	public Date getSignedDay() {
		return this.signedDay;
	}

	public void setSignedDay(Date signedDay) {
		this.signedDay = signedDay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConPa", cascade = CascadeType.ALL, orphanRemoval = true)
//	@Where(clause="deleted='0'")
	public Set<TConPaCinema> gettConPaCinemas() {
		return this.tConPaCinemas;
	}

	public void settConPaCinemas(Set<TConPaCinema> tConPaCinemas) {
		this.tConPaCinemas = tConPaCinemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConPa", cascade = CascadeType.ALL, orphanRemoval = true)
//	@Where(clause="deleted='0'")
	public Set<TConPaItem> gettConPaItems() {
		return this.tConPaItems;
	}

	public void settConPaItems(Set<TConPaItem> tConPaItems) {
		this.tConPaItems = tConPaItems;
	}

	@Transient
	@Override
	public String getEntityName() {
		return "供货范围";
	}

	@Column(name = "CON_PROVIDER_ID")
	public Long getProviderId() {
		return providerId;
	}

	public void setProviderId(Long providerId) {
		this.providerId = providerId;
	}

	@Column(name = "ORG_CON_PA_ID")
	public Long getOrgConPaId() {
		return orgConPaId;
	}

	public void setOrgConPaId(Long orgConPaId) {
		this.orgConPaId = orgConPaId;
	}

	@Column(name = "APPLY_ALL_CINEMA")
	public Boolean getApplyAllCinema() {
		return applyAllCinema;
	}

	public void setApplyAllCinema(Boolean applyAllCinema) {
		this.applyAllCinema = applyAllCinema;
	}

	@Column(name = "OA_PROCESS_NO", length = 100)
	public String getOaProcessNo() {
		return this.oaProcessNo;
	}

	public void setOaProcessNo(String oaProcessNo) {
		this.oaProcessNo = oaProcessNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_CON_PA_ID", updatable = false, insertable = false)
	public TConPa getTrunk() {
		return trunk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trunk")
	@OrderBy("updatedDate desc")
	public Set<TConPa> getBranches() {
		return branches;
	}

	public void setTrunk(TConPa trunk) {
		this.trunk = trunk;
	}

	public void setBranches(Set<TConPa> branches) {
		this.branches = branches;
	}

	@Transient
	public Boolean getIncludeMe() {
		return includeMe;
	}

	public void setIncludeMe(Boolean includeMe) {
		this.includeMe = includeMe;
	}

	@Transient
	public List<TConFileAttach> gettConFileAttachs() {
		return tConFileAttachs;
	}

	public void settConFileAttachs(List<TConFileAttach> tConFileAttachs) {
		this.tConFileAttachs = tConFileAttachs;
	}

	@Column(name="SUBMIT_CINEMA_ID", precision = 38, scale = 0)
	public Long getSubmitCinemaId() {
		return submitCinemaId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SUBMIT_CINEMA_ID" , insertable = false , updatable = false)
	public TCinema getSubmitTCinema() {
		return submitTCinema;
	}

	public void setSubmitCinemaId(Long submitCinemaId) {
		this.submitCinemaId = submitCinemaId;
	}

	public void setSubmitTCinema(TCinema submitTCinema) {
		this.submitTCinema = submitTCinema;
	}
	
	@Override
	public String toString() {
		try {
			return this.paName != null ? this.paName : 
				"[" + this.paCode + "," + this.tConProvider.getShortName() + "]";
		} catch (Exception e) {
		}
		return null;
	}
}
