package com.wanda.ccs.model;

// Generated Mar 3, 2013 6:35:25 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TConSearchScheme generated by hbm2java
 */
@Entity
@Table(name = "T_CON_SEARCH_SCHEME")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConSearchScheme extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 7855260887707388266L;
	
	private Long schemeId;
	private String userId;
	private String link;
	private String formId;
	private String schemeName;
	private String schemeData;
	private Date lastVisitTime;
	private Date lastModifyTime;

	public TConSearchScheme() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_SEARCH_SCHEME" , allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SCHEME_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getSchemeId() {
		return this.schemeId;
	}

	public void setSchemeId(Long schemeId) {
		this.schemeId = schemeId;
	}

	@Column(name = "USER_ID", nullable = false, length = 40)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "LINK", nullable = false, length = 500)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "FORM_ID", nullable = false, length = 50)
	public String getFormId() {
		return this.formId;
	}

	public void setFormId(String formId) {
		this.formId = formId;
	}

	@Column(name = "SCHEME_NAME", nullable = false, length = 50)
	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	@Column(name = "SCHEME_DATA", nullable = false, length = 1000)
	public String getSchemeData() {
		return this.schemeData;
	}

	public void setSchemeData(String schemeData) {
		this.schemeData = schemeData;
	}

	@Column(name = "LAST_VISIT_TIME")
	public Date getLastVisitTime() {
		return this.lastVisitTime;
	}

	public void setLastVisitTime(Date lastVisitTime) {
		this.lastVisitTime = lastVisitTime;
	}

	@Column(name = "LAST_MODIFY_TIME")
	public Date getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	@Override
	@Transient
	public Long getId() {
		return this.schemeId;
	}

	@Override
	public void setId(Long id) {
		this.schemeId = id;
	}

}
