package com.wanda.ccs.model;

// Generated Nov 30, 2012 1:59:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TConSetDetail generated by hbm2java
 */
@Entity
@Table(name = "T_CON_SET_DETAIL")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConSetDetail extends VersionableEntity implements
		java.io.Serializable ,Comparable<TConSetDetail>{
	private static final long serialVersionUID = 1L;

	private Long id;
	private TConSet tConSet;
	private TConItem tConItem;
	private Boolean defaultItem; // 是否默认
	private Integer groupIndex;
	private Float priceGap; // 差价
	private Integer groupSaleCount; // 组售卖数量
	
	public TConSetDetail() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_SET_DETAIL",allocationSize = 10)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_SET_DETAIL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_SET_ID")
	public TConSet gettConSet() {
		return this.tConSet;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_ITEM_ID")
	public TConItem gettConItem() {
		return tConItem;
	}

	public void settConItem(TConItem tConItem) {
		this.tConItem = tConItem;
	}
	public void settConSet(TConSet tConSet) {
		this.tConSet = tConSet;
	}

	@Column(name = "DEFAULT_ITEM", nullable = false, length = 1)
	public Boolean getDefaultItem() {
		return this.defaultItem;
	}

	public void setDefaultItem(Boolean defaultItem) {
		this.defaultItem = defaultItem;
	}

	@Column(name = "GROUP_INDEX", nullable = false, precision = 8, scale = 0)
	public Integer getGroupIndex() {
		return this.groupIndex;
	}

	public void setGroupIndex(Integer groupIndex) {
		this.groupIndex = groupIndex;
	}

	@Column(name = "PRICE_GAP", nullable = false, precision = 10, scale = 2)
	public Float getPriceGap() {
		return this.priceGap;
	}

	public void setPriceGap(Float priceGap) {
		this.priceGap = priceGap;
	}

	@Override
	public int compareTo(TConSetDetail o) {
		int groupIndex1 = this.getGroupIndex();
		int groupIndex2 = o.getGroupIndex();
		
		if(groupIndex1 >= groupIndex2){
			return 1;
		}else if(groupIndex1 == groupIndex2){
			return this.gettConItem().getId().compareTo(o.gettConItem().getId());
		}else{
			return -1;
		}
	}

	@Column(name = "GROUP_SALE_COUNT")
	public Integer getGroupSaleCount() {
		return groupSaleCount;
	}

	public void setGroupSaleCount(Integer groupSaleCount) {
		this.groupSaleCount = groupSaleCount;
	}

}
