package com.wanda.ccs.model;

// Generated Nov 30, 2012 1:59:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.OrderBy;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TConCompound generated by hbm2java
 */
@Entity
@Table(name = "T_CON_COMPOUND_LOG")
public class TConCompoundLog extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private TConCompound tConCompound;
	private Boolean valid = true;//是否有效
	private List<TConCompoundDetailLog> tConCompoundDetailLogs = new ArrayList<TConCompoundDetailLog>();

	public TConCompoundLog() {
	}
	
	public TConCompoundLog(TConCompound compound) {
		this.settConCompound(compound);
		this.setValid(compound.getValid());
		for(TConCompoundDetail detail : compound.gettConCompoundDetails()){
			TConCompoundDetailLog detailLog = new TConCompoundDetailLog();
			detailLog.settConCompoundLog(this);
			detailLog.settConCompoundDefDetail(detail.gettConCompoundDefDetail());
			detailLog.setQuantity(detail.getQuantity());
			tConCompoundDetailLogs.add(detailLog);
		}
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_COMPOUND_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_COMPOUND_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_COMPOUND_ID")
	public TConCompound gettConCompound() {
		return this.tConCompound;
	}

	public void settConCompound(TConCompound tConCompound) {
		this.tConCompound = tConCompound;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConCompoundLog", cascade = CascadeType.ALL, orphanRemoval = true)
	@OrderBy(clause = "tConCompoundDefDetail")
	public List<TConCompoundDetailLog> gettConCompoundDetailLogs() {
		return this.tConCompoundDetailLogs;
	}

	public void settConCompoundDetailLogs(
			List<TConCompoundDetailLog> tConCompoundDetailLogs) {
		this.tConCompoundDetailLogs = tConCompoundDetailLogs;
	}
	
	@Column(name = "VALID", nullable = false, length = 1)
	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}
}
