package com.wanda.ccs.model;

// Generated Feb 19, 2013 1:40:24 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TConItemStorage generated by hbm2java
 */
@Entity
@Table(name = "T_CON_ITEM_STORAGE")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TConItemStorage extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -233271215105424956L;
	
	private Long id;
	private Long conWarehouseId;
	private TConWarehouse tConWarehouse;
	private Long conItemId;
	private TConSingleItem tConSingleItem;
	private Long whWarningQuanitity; // 仓库缺货通知数量
	private Long sfWarningQuantity; // 货架缺货通知数量
	private String deduceType;
	private Long cinemaId;
	private String status; // '状态（0:未下发，1:修改未下发，2:正在下发,3:已下发）'
	private String tranFn; // 卖品数据下发文件名称
	private String tranMsg;// 卖品数据下发异常信息
	private String tranSts; // 卖品数据下发状态 0：POS端已经将下发到DET上的文件取走,1：卖品数据已经下发到DET，等待POS取走,2：卖品数据已经生成，还没下发到DET
	private Date tranTime;// 卖品数据下发状态更改时间

	public TConItemStorage() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_ITEM_STORAGE",allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_ITEM_STORAGE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_WAREHOUSE_ID" , insertable = false , updatable = false)
	public TConWarehouse gettConWarehouse() {
		return this.tConWarehouse;
	}

	public void settConWarehouse(TConWarehouse tConWarehouse) {
		this.tConWarehouse = tConWarehouse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_ITEM_ID")
	public TConSingleItem gettConSingleItem() {
		return this.tConSingleItem;
	}

	public void settConSingleItem(TConSingleItem tConSingleItem) {
		this.tConSingleItem = tConSingleItem;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "WH_WARNING_QUANITITY", precision = 10, scale = 4)
	public Long getWhWarningQuanitity() {
		return this.whWarningQuanitity;
	}

	public void setWhWarningQuanitity(Long whWarningQuanitity) {
		this.whWarningQuanitity = whWarningQuanitity;
	}

	@Column(name = "SF_WARNING_QUANTITY", precision = 10, scale = 4)
	public Long getSfWarningQuantity() {
		return this.sfWarningQuantity;
	}

	public void setSfWarningQuantity(Long sfWarningQuantity) {
		this.sfWarningQuantity = sfWarningQuantity;
	}

	@Column(name = "DEDUCE_TYPE", nullable = false, length = 20)
	public String getDeduceType() {
		return this.deduceType;
	}

	public void setDeduceType(String deduceType) {
		this.deduceType = deduceType;
	}

	@Column(name = "CINEMA_ID", nullable = false, precision = 22, scale = 0)
	public Long getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "CON_WAREHOUSE_ID")
	public Long getConWarehouseId() {
		return conWarehouseId;
	}

	public void setConWarehouseId(Long conWarehouseId) {
		this.conWarehouseId = conWarehouseId;
	}
	
	@Column(name = "TRAN_STS", length = 1)
	public String getTranSts() {
		return tranSts;
	}

	@Column(name = "TRAN_FN", length = 20)
	public String getTranFn() {
		return tranFn;
	}
	
	@Column(name = "TRAN_MSG", length = 80)
	public String getTranMsg() {
		return tranMsg;
	}
	
	@Column(name = "TRAN_TIME")
	public Date getTranTime() {
		return tranTime;
	}

	public void setTranFn(String tranFn) {
		this.tranFn = tranFn;
	}

	public void setTranMsg(String tranMsg) {
		this.tranMsg = tranMsg;
	}

	public void setTranSts(String tranSts) {
		this.tranSts = tranSts;
	}

	public void setTranTime(Date tranTime) {
		this.tranTime = tranTime;
	}

	@Column(name = "CON_ITEM_ID" , insertable = false , updatable = false)
	public Long getConItemId() {
		return conItemId;
	}

	public void setConItemId(Long conItemId) {
		this.conItemId = conItemId;
	}
}
