package com.wanda.ccs.model;

// Generated Nov 30, 2012 1:59:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.OrderBy;

import com.xcesys.extras.core.dao.model.VersionableEntity;
import com.xcesys.extras.core.util.StringUtil;

/**
 * TConCompound generated by hbm2java
 */
@Entity
@Table(name = "T_CON_COMPOUND")
public class TConCompound extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private TConCompoundDef tConCompoundDef;
	private Long conCompoundDefId;
	private Long cinemaId;
	private TCinema tCinema;
	private Boolean valid = true;//是否有效
	private String status;//状态（0未下发、1修改未下发、2正在下发、3下发完成）
	private String tranSts;//下发状态值
	private String tranFn;//下发文件
	private String tranMsg;//下发状态说明
	private Date tranTime;//下发时间
	private List<TConCompoundDetail> tConCompoundDetails = new ArrayList<TConCompoundDetail>();
	private String materialStorage;//合成品中包含的物料库存
	private String strValid;
	private List<TConCompoundLog> tConCompoundLogs = new ArrayList<TConCompoundLog>();
	private List<TConCompound> tConCompounds = new ArrayList<TConCompound>();

	public TConCompound() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_CON_COMPOUND")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CON_COMPOUND_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_ITEM_ID", updatable = false, insertable = false)
	public TConCompoundDef gettConCompoundDef() {
		return this.tConCompoundDef;
	}

	public void settConCompoundDef(TConCompoundDef tConCompoundDef) {
		this.tConCompoundDef = tConCompoundDef;
	}
	
	@Column(name = "CON_ITEM_ID")
	public Long getConCompoundDefId() {
		return conCompoundDefId;
	}

	public void setConCompoundDefId(Long conCompoundDefId) {
		this.conCompoundDefId = conCompoundDefId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_ID", updatable = false, insertable = false)
	public TCinema gettCinema() {
		return tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}
	
	@Column(name = "CINEMA_ID", precision = 22, scale = 0)
	public Long getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConCompound", cascade = CascadeType.ALL, orphanRemoval = true)
	@OrderBy(clause = "tConCompoundDefDetail")
	public List<TConCompoundDetail> gettConCompoundDetails() {
		return this.tConCompoundDetails;
	}

	public void settConCompoundDetails(
			List<TConCompoundDetail> tConCompoundDetails) {
		this.tConCompoundDetails = tConCompoundDetails;
	}
	
	@Column(name = "VALID", nullable = false, length = 1)
	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TRAN_STS")
	public String getTranSts() {
		return tranSts;
	}

	public void setTranSts(String tranSts) {
		this.tranSts = tranSts;
	}

	@Column(name = "TRAN_FN")
	public String getTranFn() {
		return tranFn;
	}

	public void setTranFn(String tranFn) {
		this.tranFn = tranFn;
	}

	@Column(name = "TRAN_MSG")
	public String getTranMsg() {
		return tranMsg;
	}

	public void setTranMsg(String tranMsg) {
		this.tranMsg = tranMsg;
	}
	
	@Column(name = "TRAN_TIME")
	public Date getTranTime() {
		return tranTime;
	}

	public void setTranTime(Date tranTime) {
		this.tranTime = tranTime;
	}

	@Transient
	public String getMaterialStorage() {
		return materialStorage;
	}

	public void setMaterialStorage(String materialStorage) {
		this.materialStorage = materialStorage;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tConCompound")
	@OrderBy(clause="createdDate desc")
	public List<TConCompoundLog> gettConCompoundLogs() {
		return tConCompoundLogs;
	}

	public void settConCompoundLogs(List<TConCompoundLog> tConCompoundLogs) {
		this.tConCompoundLogs = tConCompoundLogs;
	}


	@Transient
	public String getStrValid() {
		if(valid)
			this.strValid = "Y";
		else
			this.strValid = "N";
		return strValid;
	}

	public void setStrValid(String strValid) {
		this.strValid = strValid;
		if(StringUtil.isNullOrBlank(strValid) || strValid.equals("Y"))
			this.valid = true;
		else
			this.valid = false;
	}
	
	@Transient
	public List<TConCompound> gettConCompounds() {
		return tConCompounds;
	}


	public void settConCompounds(List<TConCompound> tConCompounds) {
		this.tConCompounds = tConCompounds;
	}
}
