package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.xcesys.extras.core.dao.model.AbstractEntity;
import com.xcesys.extras.util.PinYinUtil;

/**
 * TDimdef generated by hbm2java
 */
@Entity
@Table(name = "T_DIMDEF", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TYPEID", "CODE" }))
public class TDimDef extends AbstractEntity implements java.io.Serializable,
		Comparable<TDimDef> {

	private static final long serialVersionUID = 2686192087873020923L;
	private Long id;
	private TDimTypeDef tDimtypedef;
	private Long typeId;
	private String code;
	private String name;
	private Long parent;
	private Date validstart;
	private Date validend;
	private Long isdelete;
	private Date updatetime;

	public TDimDef() {
	}

	public TDimDef(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public TDimDef(TDimTypeDef tDimtypedef, String code, String name,
			Long parent, Date validstart, Date validend, Long isdelete,
			Date updatetime) {
		this.tDimtypedef = tDimtypedef;
		this.code = code;
		this.name = name;
		this.parent = parent;
		this.validstart = validstart;
		this.validend = validend;
		this.isdelete = isdelete;
		this.updatetime = updatetime;
	}

	@Override
	public int compareTo(TDimDef o) {
//		if ((o.getTypeId().equals(IDimType.LDIMTYPE_AREA) || o.getTypeId().equals(IConDimType.LDIMTYPE_CON_UNIT))
//				&& this.getTypeId().longValue() == o.getTypeId().longValue()) {
			String py1 = PinYinUtil.toPinYin(this.getName().substring(0, 1));
			String py2 = PinYinUtil.toPinYin(o.getName().substring(0, 1));
			if("重庆".equalsIgnoreCase(this.getName()))
				py1 = "c";
			else if("重庆".equalsIgnoreCase(o.getName()))
				py2 = "c";
			return py1.compareToIgnoreCase(py2);
//		}
//		return 0;
	}

	@Column(name = "CODE", nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_DIMDEF")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	@Column(name = "ISDELETE", precision = 38, scale = 0)
	public Long getIsdelete() {
		return this.isdelete;
	}

	@Column(name = "NAME", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "PARENT", precision = 38, scale = 0)
	public Long getParent() {
		return this.parent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPEID", insertable = false, updatable = false)
	public TDimTypeDef gettDimtypedef() {
		return this.tDimtypedef;
	}

	@Column(name = "TYPEID")
	public Long getTypeId() {
		return typeId;
	}

	@Column(name = "UPDATETIME")
	public Date getUpdatetime() {
		return this.updatetime;
	}

	@Column(name = "VALIDEND", length = 7)
	public Date getValidend() {
		return this.validend;
	}

	@Column(name = "VALIDSTART", length = 7)
	public Date getValidstart() {
		return this.validstart;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setIsdelete(Long isdelete) {
		this.isdelete = isdelete;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setParent(Long parent) {
		this.parent = parent;
	}

	public void settDimtypedef(TDimTypeDef tDimtypedef) {
		this.tDimtypedef = tDimtypedef;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public void setValidend(Date validend) {
		this.validend = validend;
	}

	public void setValidstart(Date validstart) {
		this.validstart = validstart;
	}

	@Override
	public String toString() {
		return "TDimDef [code=" + code + ", name=" + name + "]";
	}

}
