package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

/**
 * TFilmCopyTrackLog generated by hbm2java
 */
@Entity
@Table(name = "T_FILM_COPY_TRACK_LOG")
public class TFilmCopyTrackLog extends VersionableEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private TFilmCopy tFilmCopy;
	private Date sendDate;
	private Date receiveDate;
	private String sendOperator;
	private TFilm tFilm;
	private Long filmId;
	
	private Long sendFrom;				//发送方(发行商或影院)
	private Long sendTo;
	
	private TPublisher fromPublisher;
	private TPublisher toPublisher;
	private TCinema fromCinema;
	private TCinema toCinema;
	
	private String fromFlag;	//发送方标记
	private String toFlag;		//接受方标记
	
	private String status;

	// 临时冗余字段
	private String copyType; // 拷贝类型(01:买断,02:普通)
	private String language; // 拷贝语言
	private String[] languages;// 拷贝语言数组
	private String copyFrom; // 拷贝来源
	private String medium; // 介质类型
	private String copyNo; // 拷贝编号
	
	public TFilmCopyTrackLog() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_FILM_COPY_TRACK_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILM_COPY_ID")
	public TFilmCopy gettFilmCopy() {
		return this.tFilmCopy;
	}

	public void settFilmCopy(TFilmCopy tFilmCopy) {
		this.tFilmCopy = tFilmCopy;
	}


	@Column(name = "SEND_DATE", length = 7)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Column(name = "RECEIVE_DATE", length = 7)
	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	@Column(name = "SEND_OPERATOR", length = 100)
	public String getSendOperator() {
		return this.sendOperator;
	}

	public void setSendOperator(String sendOperator) {
		this.sendOperator = sendOperator;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILM_ID", insertable = false, updatable = false)
	public TFilm gettFilm() {
		return tFilm;
	}

	public void settFilm(TFilm tFilm) {
		this.tFilm = tFilm;
	}

	@Column(name = "FROM_FLAG",length = 1)
	public String getFromFlag() {
		return fromFlag;
	}

	public void setFromFlag(String fromFlag) {
		this.fromFlag = fromFlag;
	}

	@Column(name = "TO_FLAG",length = 1)
	public String getToFlag() {
		return toFlag;
	}

	public void setToFlag(String toFlag) {
		this.toFlag = toFlag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_FROM", insertable = false, updatable = false)
	public TCinema getFromCinema() {
		return fromCinema;
	}

	public void setFromCinema(TCinema fromCinema) {
		this.fromCinema = fromCinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_TO", insertable = false, updatable = false)
	public TCinema getToCinema() {
		return toCinema;
	}

	public void setToCinema(TCinema toCinema) {
		this.toCinema = toCinema;
	}

	@Column(name = "SEND_FROM")
	public Long getSendFrom() {
		return sendFrom;
	}

	public void setSendFrom(Long sendFrom) {
		this.sendFrom = sendFrom;
	}

	@Column(name = "SEND_TO")
	public Long getSendTo() {
		return sendTo;
	}

	public void setSendTo(Long sendTo) {
		this.sendTo = sendTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_FROM", insertable = false, updatable = false)
	public TPublisher getFromPublisher() {
		return fromPublisher;
	}

	public void setFromPublisher(TPublisher fromPublisher) {
		this.fromPublisher = fromPublisher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_TO", insertable = false, updatable = false)
	public TPublisher getToPublisher() {
		return toPublisher;
	}

	public void setToPublisher(TPublisher toPublisher) {
		this.toPublisher = toPublisher;
	}

	@Column(name = "FILM_ID")
	public Long getFilmId() {
		return filmId;
	}

	public void setFilmId(Long filmId) {
		this.filmId = filmId;
	}

	@Column(name = "COPY_TYPE", length = 20)
	public String getCopyType() {
		if(this.gettFilmCopy() != null){
			setCopyType(this.gettFilmCopy().getCopyType());
		}
		return copyType;
	}

	public void setCopyType(String copyType) {
		this.copyType = copyType;
	}

	@Column(name = "LANGUAGE", length = 100)
	public String getLanguage() {
		if(this.gettFilmCopy() != null){
			setLanguage(this.gettFilmCopy().getLanguage());
		}
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Transient
	public String[] getLanguages() {
		if (StringUtils.isNotBlank(language)) {
			languages = StringUtils.split(language, ',');
		}
		return languages;
	}

	public void setLanguages(String[] languages) {
		if (languages != null) {
			language = StringUtils.join(languages, ',');
		}
		this.languages = languages;
	}

	@Column(name = "COPY_FROM", length = 20)
	public String getCopyFrom() {
		if(this.gettFilmCopy() != null){
			setCopyFrom(this.gettFilmCopy().getCopyFrom());
		}
		return copyFrom;
	}

	public void setCopyFrom(String copyFrom) {
		this.copyFrom = copyFrom;
	}

	@Column(name = "MEDIUM", length = 20)
	public String getMedium() {
		if(this.gettFilmCopy() != null){
			setMedium(this.gettFilmCopy().getMedium());
		}
		return medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	@Column(name = "COPY_NO", length = 50)
	public String getCopyNo() {
		if(this.gettFilmCopy() != null){
			setCopyNo(this.gettFilmCopy().getCopyNo());
		}
		return copyNo;
	}

	public void setCopyNo(String copyNo) {
		this.copyNo = copyNo;
	}


}
