package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TFilmCopySchedule generated by hbm2java
 */
@Entity
@Table(name = "T_FILM_COPY_SCHEDULE")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TFilmCopySchedule extends VersionableEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private TFilmCopy tFilmCopy;
	private Long sendFrom; // 发送方(发行商或影院)
	private TPublisher fromTPublisher;
	private TCinema fromCinema;
	private Long sendTo; // 接收方(发行商或影院)
	private TPublisher toTPublisher;
	private TCinema toCinema;
	private Date sendDate; // 发送时间
	private Date receiveDate; // 接受时间
	private String sendOperator; // 发送人
	private TFilm tFilm;
	private Long filmId;

	private String fromFlag;// 发送方标记
	private String toFlag;// 接受方标记
	
	private String expressNo;//快递编号

	private String status;

	// 临时冗余字段
	private String copyType; // 拷贝类型(01:买断,02:普通)
	private String language; // 拷贝语言
	private String[] languages;// 拷贝语言数组
	private String copyFrom; // 拷贝来源
	private String medium; // 介质类型
	private String copyNo; // 拷贝编号

	public TFilmCopySchedule() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_FILM_COPY_SCHEDULE")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILM_COPY_ID")
	public TFilmCopy gettFilmCopy() {
		return this.tFilmCopy;
	}

	public void settFilmCopy(TFilmCopy tFilmCopy) {
		this.tFilmCopy = tFilmCopy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_FROM", insertable = false, updatable = false)
	public TPublisher getFromTPublisher() {
		return this.fromTPublisher;
	}

	public void setFromTPublisher(TPublisher fromTPublisher) {
		this.fromTPublisher = fromTPublisher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_TO", insertable = false, updatable = false)
	public TPublisher getToTPublisher() {
		return this.toTPublisher;
	}

	public void setToTPublisher(TPublisher toTPublisher) {
		this.toTPublisher = toTPublisher;
	}

	@Column(name = "SEND_FROM")
	public Long getSendFrom() {
		return this.sendFrom;
	}

	public void setSendFrom(Long sendFrom) {
		this.sendFrom = sendFrom;
	}

	@Column(name = "SEND_TO")
	public Long getSendTo() {
		return this.sendTo;
	}

	public void setSendTo(Long sendTo) {
		this.sendTo = sendTo;
	}

	@Column(name = "SEND_DATE", length = 7)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Column(name = "RECEIVE_DATE", length = 7)
	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	@Column(name = "SEND_OPERATOR", length = 50)
	public String getSendOperator() {
		return this.sendOperator;
	}

	public void setSendOperator(String sendOperator) {
		this.sendOperator = sendOperator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILM_ID", insertable = false, updatable = false)
	public TFilm gettFilm() {
		return this.tFilm;
	}

	public void settFilm(TFilm tFilm) {
		this.tFilm = tFilm;
	}

	@Column(name = "FILM_ID")
	public Long getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Long filmId) {
		this.filmId = filmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_FROM", insertable = false, updatable = false)
	public TCinema getFromCinema() {
		return fromCinema;
	}

	public void setFromCinema(TCinema fromCinema) {
		this.fromCinema = fromCinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_TO", insertable = false, updatable = false)
	public TCinema getToCinema() {
		return toCinema;
	}

	public void setToCinema(TCinema toCinema) {
		this.toCinema = toCinema;
	}

	@Column(name = "FROM_FLAG", length = 1)
	public String getFromFlag() {
		return fromFlag;
	}

	public void setFromFlag(String fromFlag) {
		this.fromFlag = fromFlag;
	}

	@Column(name = "TO_FLAG", length = 1)
	public String getToFlag() {
		return toFlag;
	}

	public void setToFlag(String toFlag) {
		this.toFlag = toFlag;
	}

	@Column(name = "COPY_TYPE", length = 20)
	public String getCopyType() {
		return copyType;
	}

	public void setCopyType(String copyType) {
		this.copyType = copyType;
	}

	@Column(name = "LANGUAGE", length = 100)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Transient
	public String[] getLanguages() {
		if (StringUtils.isNotBlank(language)) {
			languages = StringUtils.split(language, ',');
		}
		return languages;
	}

	public void setLanguages(String[] languages) {
		if (languages != null) {
			language = StringUtils.join(languages, ',');
		}
		this.languages = languages;
	}

	@Column(name = "COPY_FROM", length = 20)
	public String getCopyFrom() {
		return copyFrom;
	}

	public void setCopyFrom(String copyFrom) {
		this.copyFrom = copyFrom;
	}

	@Column(name = "MEDIUM", length = 20)
	public String getMedium() {
		return medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COPY_NO", length = 50)
	public String getCopyNo() {
		return copyNo;
	}

	public void setCopyNo(String copyNo) {
		this.copyNo = copyNo;
	}

	@Column(name = "EXPRESS_NO", length = 100)
	public String getExpressNo() {
		return expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

}
