package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * THolidays generated by hbm2java
 */
@Entity
@Table(name = "T_HOLIDAYS")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class THolidays extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 4812244156276204883L;
	private Long id;
	private String name;
	private Date startdate;
	private Date enddate;
	private Long isdelete;
	private Date updatetime;
	private String holidaytype;

	public THolidays() {
	}

	public THolidays(String name, Date startdate, Date enddate, Long isdelete,
			Date updatetime, String holidaytype) {
		this.name = name;
		this.startdate = startdate;
		this.enddate = enddate;
		this.isdelete = isdelete;
		this.updatetime = updatetime;
		this.holidaytype = holidaytype;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_HOLIDAYS")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "ISDELETE", precision = 38, scale = 0)
	public Long getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Long isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "UPDATETIME")
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "HOLIDAYTYPE", length = 20)
	public String getHolidaytype() {
		return this.holidaytype;
	}

	public void setHolidaytype(String holidaytype) {
		this.holidaytype = holidaytype;
	}

}
