package com.wanda.ccs.model;

// Generated 2013-5-31 11:41:36 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.BlameableEntity;

/**
 * TMackDaddyCard generated by hbm2java
 */
@Entity
@Table(name = "T_MACK_DADDY_CARD")
public class TMackDaddyCard extends BlameableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 4206938388321298854L;
	
	private Long id;
	private TMackDaddyCardOrder tMackDaddyCardOrder;
	private String cardNumber;//前面4位是6+影城编码 中间4位0 和储值卡一样，后8位是序列号。
	private Long cinemaId;
	private String status;//卡状态 I-已预制、O-正常、R-已 换卡不可用
	private TCinema tCinema;
	private TMember tMember;
	private Long memberId;

	public TMackDaddyCard() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_MACK_DADDY_CARD")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "MACK_DADDY_CARD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACK_DADDY_CARD_ORDER_ID")
	public TMackDaddyCardOrder gettMackDaddyCardOrder() {
		return this.tMackDaddyCardOrder;
	}

	public void settMackDaddyCardOrder(TMackDaddyCardOrder tMackDaddyCardOrder) {
		this.tMackDaddyCardOrder = tMackDaddyCardOrder;
	}

	@Column(name = "CARD_NUMBER", length = 128)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "CINEMA_ID", precision = 22, scale = 0)
	public Long getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_ID", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEMBER_ID", nullable = false, insertable = false, updatable = false)
	public TMember gettMember() {
		return this.tMember;
	}

	public void settMember(TMember tMember) {
		this.tMember = tMember;
	}

	@Column(name = "MEMBER_ID")
	public Long getMemberId() {
		return memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}
	
	
}
