package com.wanda.ccs.model;

// Generated 2011-10-26 19:14:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TMarketingCampaign generated by hbm2java
 */
@Entity
@Table(name = "T_MARKETING_CAMPAIGN")
public class TMarketingCampaign extends VersionableEntity implements
		java.io.Serializable {

	private Long id;
	private String campaignName;
	private String campaignLevel;
	private String ownerRegion;
	private TCinema tCinema; // 营销活动的影城
	private Long ownerCinema;
	private String description;
	private Date startDate;
	private Date endDate;
	private String status;
	private Set<TTicketType> tTicketTypes = new HashSet<TTicketType>(0);
	private Set<TTicketTypeUseRule> tTicketTypeUseRules = new HashSet<TTicketTypeUseRule>(
			0);
	private Set<TReqTtypeUseRule> tReqTtypeUseRules = new HashSet<TReqTtypeUseRule>(
			0);
	private Set<TReqTicketType> tReqTicketTypes = new HashSet<TReqTicketType>(0);

	public TMarketingCampaign() {
	}

	public TMarketingCampaign(String campaignName, TCinema tCinema,
			Long ownerCinema, String campaignLevel, String ownerRegion,
			String description, Date startDate, Date endDate, String status,
			Set<TTicketType> tTicketTypes,
			Set<TTicketTypeUseRule> tTicketTypeUseRules,
			Set<TReqTtypeUseRule> tReqTtypeUseRules,
			Set<TReqTicketType> tReqTicketTypes) {
		this.tCinema = tCinema;
		this.ownerCinema = ownerCinema;
		this.campaignName = campaignName;
		this.campaignLevel = campaignLevel;
		this.ownerRegion = ownerRegion;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.tTicketTypes = tTicketTypes;
		this.tTicketTypeUseRules = tTicketTypeUseRules;
		this.tReqTtypeUseRules = tReqTtypeUseRules;
		this.tReqTicketTypes = tReqTicketTypes;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_MARKETING_CAMPAIGN")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "MARKETING_CAMPAIGN_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CAMPAIGN_LEVEL", length = 1)
	public String getCampaignLevel() {
		return this.campaignLevel;
	}

	public void setCampaignLevel(String campaignLevel) {
		this.campaignLevel = campaignLevel;
	}

	@Column(name = "CAMPAIGN_NAME", length = 1024)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Column(name = "OWNER_REGION", length = 20)
	public String getOwnerRegion() {
		return this.ownerRegion;
	}

	public void setOwnerRegion(String ownerRegion) {
		this.ownerRegion = ownerRegion;
	}

	@Column(name = "OWNER_CINEMA", precision = 38, scale = 0)
	public Long getOwnerCinema() {
		return this.ownerCinema;
	}

	public void setOwnerCinema(Long ownerCinema) {
		this.ownerCinema = ownerCinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_CINEMA", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tMarketingCampaign")
	public Set<TTicketType> gettTicketTypes() {
		return this.tTicketTypes;
	}

	public void settTicketTypes(Set<TTicketType> tTicketTypes) {
		this.tTicketTypes = tTicketTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tMarketingCampaign")
	public Set<TTicketTypeUseRule> gettTicketTypeUseRules() {
		return this.tTicketTypeUseRules;
	}

	public void settTicketTypeUseRules(
			Set<TTicketTypeUseRule> tTicketTypeUseRules) {
		this.tTicketTypeUseRules = tTicketTypeUseRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tMarketingCampaign")
	public Set<TReqTtypeUseRule> gettReqTtypeUseRules() {
		return this.tReqTtypeUseRules;
	}

	public void settReqTtypeUseRules(Set<TReqTtypeUseRule> tReqTtypeUseRules) {
		this.tReqTtypeUseRules = tReqTtypeUseRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tMarketingCampaign")
	public Set<TReqTicketType> gettReqTicketTypes() {
		return this.tReqTicketTypes;
	}

	public void settReqTicketTypes(Set<TReqTicketType> tReqTicketTypes) {
		this.tReqTicketTypes = tReqTicketTypes;
	}
}
