package com.wanda.ccs.model;

// Generated 2013-4-26 16:06:19 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TMemCardRel generated by hbm2java
 */
@Entity
@Table(name = "T_MEM_CARD_INFO")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TMemCardInfo extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -2055469252616829601L;
	private Long id;
	private String cardNumber;
	private String cardTypeCode;
	private String cardTypeName;
	private String issueCinema;// 发卡影城 code
	private String cardStatus;
	private Date expiryDate;
	private Long balance;
	private String cardValueType;//M储值，T 计次 D 权益

	public TMemCardInfo() {
	}

	public TMemCardInfo(Long id, TMember tMember) {
		this.id = id;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_MEM_CARD_INFO", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQ_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CARD_NUMBER")
	public String getCardNumber() {
		return cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "CARD_TYPE_CODE")
	public String getCardTypeCode() {
		return cardTypeCode;
	}

	public void setCardTypeCode(String cardTypeCode) {
		this.cardTypeCode = cardTypeCode;
	}

	@Column(name = "CARD_TYPE_NAME")
	public String getCardTypeName() {
		return cardTypeName;
	}

	public void setCardTypeName(String cardTypeName) {
		this.cardTypeName = cardTypeName;
	}

	@Column(name = "ISSUE_CINEMA")
	public String getIssueCinema() {
		return issueCinema;
	}

	public void setIssueCinema(String issueCinema) {
		this.issueCinema = issueCinema;
	}

	@Column(name = "CARD_STATUS")
	public String getCardStatus() {
		return cardStatus;
	}

	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus;
	}

	@Column(name = "EXPIRY_DATE")
	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "BALANCE")
	public Long getBalance() {
		return balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}
	
	@Column(name = "CARD_VALUE_TYPE")
	public String getCardValueType() {
		return cardValueType;
	}

	public void setCardValueType(String cardValueType) {
		this.cardValueType = cardValueType;
	}

}
