package com.wanda.ccs.model;

// Generated 2013-5-21 10:54:02 by Hibernate Tools 3.3.0.GA
import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TMemberLevel generated by hbm2java
 */
@Entity
@Table(name = "T_MEMBER_EXG_POINT")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TMemberExgPoint extends VersionableEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 725213672606454119L;
//	   MEMBER_EXG_POINT_ID  INTEGER              not null,
//	   MEMBER_ID            NUMBER               not null,
//	   POINT_BALANCE        INTEGER              default 0 not null,
//	   GAIN_YEAR            VARCHAR2(20)         not null,
//	   EXPIRE_TIME          TIMESTAMP(6)         not null,
//	   EXPIRED              CHAR(1)              default '0' not null,

	
	private Long id;
	private Long memberId;
	private Long pointBalance;
	private String gainYear;
	private Date expireTime;
	private String expired;
	
//	private String memLevel;
//	private Date expireDate;
//	private String orgLevel;
//	private Date setTime;
//	private String targetLevel;
//	private Long levelPointOffset;
//	private Long ticketOffset;
//	private String changeLeveNo;


	public TMemberExgPoint() {
	}
	
	@Id
	@Column(name = "MEMBER_EXG_POINT_ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {

		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MEMBER_ID", nullable = false, precision = 22, scale = 0)
	public Long getMemberId() {
		return memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	@Column(name = "POINT_BALANCE", nullable = false, precision = 22, scale = 0)
	public Long getPointBalance() {
		return pointBalance;
	}

	public void setPointBalance(Long pointBalance) {
		this.pointBalance = pointBalance;
	}

	@Column(name = "GAIN_YEAR", nullable = false, length = 20)
	public String getGainYear() {
		return gainYear;
	}

	public void setGainYear(String gainYear) {
		this.gainYear = gainYear;
	}

	@Column(name = "EXPIRE_TIME", nullable = false)
	public Date getExpireTime() {
		return expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	@Column(name = "EXPIRED", nullable = false, length = 1)
	public String getExpired() {
		return expired;
	}

	public void setExpired(String expired) {
		this.expired = expired;
	}


//	@Column(name = "MEM_LEVEL", nullable = false, length = 20)
//	public String getMemLevel() {
//		return this.memLevel;
//	}
//
//	public void setMemLevel(String memLevel) {
//		this.memLevel = memLevel;
//	}
//
//	@Column(name = "EXPIRE_DATE")
//	public Date getExpireDate() {
//		return this.expireDate;
//	}
//
//	public void setExpireDate(Date expireDate) {
//		this.expireDate = expireDate;
//	}
//
//	@Column(name = "ORG_LEVEL", nullable = false, length = 20)
//	public String getOrgLevel() {
//		return this.orgLevel;
//	}
//
//	public void setOrgLevel(String orgLevel) {
//		this.orgLevel = orgLevel;
//	}
//
//	@Column(name = "SET_TIME")
//	public Date getSetTime() {
//		return this.setTime;
//	}
//
//	public void setSetTime(Date setTime) {
//		this.setTime = setTime;
//	}
//
//	@Column(name = "TARGET_LEVEL", nullable = false, length = 20)
//	public String getTargetLevel() {
//		return this.targetLevel;
//	}
//
//	public void setTargetLevel(String targetLevel) {
//		this.targetLevel = targetLevel;
//	}
//
//	@Column(name = "LEVEL_POINT_OFFSET", nullable = false, precision = 22, scale = 0)
//	public Long getLevelPointOffset() {
//		return this.levelPointOffset;
//	}
//
//	public void setLevelPointOffset(Long levelPointOffset) {
//		this.levelPointOffset = levelPointOffset;
//	}
//
//	@Column(name = "TICKET_OFFSET", nullable = false, precision = 22, scale = 0)
//	public Long getTicketOffset() {
//		return this.ticketOffset;
//	}
//
//	public void setTicketOffset(Long ticketOffset) {
//		this.ticketOffset = ticketOffset;
//	}
//
//	@Column(name = "CHANGE_LEVEL_NO", length = 128)
//	public String getChangeLeveNo() {
//		return this.changeLeveNo;
//	}
//
//	public void setChangeLeveNo(String changeLeveNo) {
//		this.changeLeveNo = changeLeveNo;
//	}



//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tMemberLevel")
//	public Set<TLevelHistory> gettLevelHistory() {
//		return tLevelHistory;
//	}
//
//	public void settLevelHistory(Set<TLevelHistory> tLevelHistory) {
//		this.tLevelHistory = tLevelHistory;
//	}

}
