package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:19 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TNcBdPsnbasdoc generated by hbm2java
 */
@Entity
@Table(name = "T_NC_BD_PSNBASDOC")
public class TNcBdPsnbasdoc extends AbstractEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -5700154150164807188L;
	
	private String pkPsnbasdoc;
	private Integer dr;
	private String ts;
	private String pkCorp;
	private String psnname;
	private String usedname;
	private String sex;
	private String birthdate;
	private String joinworkdate;
	private String addr;
	private String postalcode;
	private String officephone;
	private String homephone;
	private String mobile;
	private String email;

	public TNcBdPsnbasdoc() {
	}

	public TNcBdPsnbasdoc(String pkCorp, String psnname) {
		this.pkCorp = pkCorp;
		this.psnname = psnname;
	}

	public TNcBdPsnbasdoc(Integer dr, String ts, String pkCorp, String psnname,
			String usedname, String sex, String birthdate, String joinworkdate,
			String addr, String postalcode, String officephone,
			String homephone, String mobile, String email) {
		this.dr = dr;
		this.ts = ts;
		this.pkCorp = pkCorp;
		this.psnname = psnname;
		this.usedname = usedname;
		this.sex = sex;
		this.birthdate = birthdate;
		this.joinworkdate = joinworkdate;
		this.addr = addr;
		this.postalcode = postalcode;
		this.officephone = officephone;
		this.homephone = homephone;
		this.mobile = mobile;
		this.email = email;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_NC_BD_PSNBASDOC")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "PK_PSNBASDOC", unique = true, nullable = false, length = 20)
	public String getPkPsnbasdoc() {
		return this.pkPsnbasdoc;
	}

	public void setPkPsnbasdoc(String pkPsnbasdoc) {
		this.pkPsnbasdoc = pkPsnbasdoc;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public Integer getDr() {
		return this.dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PSNNAME", nullable = false, length = 200)
	public String getPsnname() {
		return this.psnname;
	}

	public void setPsnname(String psnname) {
		this.psnname = psnname;
	}

	@Column(name = "USEDNAME", length = 25)
	public String getUsedname() {
		return this.usedname;
	}

	public void setUsedname(String usedname) {
		this.usedname = usedname;
	}

	@Column(name = "SEX", length = 20)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "BIRTHDATE", length = 10)
	public String getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "JOINWORKDATE", length = 10)
	public String getJoinworkdate() {
		return this.joinworkdate;
	}

	public void setJoinworkdate(String joinworkdate) {
		this.joinworkdate = joinworkdate;
	}

	@Column(name = "ADDR", length = 100)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "POSTALCODE", length = 15)
	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Column(name = "OFFICEPHONE", length = 30)
	public String getOfficephone() {
		return this.officephone;
	}

	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	@Column(name = "HOMEPHONE", length = 50)
	public String getHomephone() {
		return this.homephone;
	}

	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	@Column(name = "MOBILE", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	@Transient
	public Long getId() {
		return null;
	}

	@Override
	public void setId(Long arg0) {
	}

}
