package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:19 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TNcBdCorp generated by hbm2java
 */
@Entity
@Table(name = "T_NC_BD_CORP")
public class TNcBdCorp extends AbstractEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -4871862317095710396L;
	
	private String pkCorp;
	private Integer dr;
	private String ts;
	private String unitcode;
	private String unitname;
	private String fatherCorp;
	private boolean hasChild;

	public TNcBdCorp() {
	}

	public TNcBdCorp(String unitcode, String unitname) {
		this.unitcode = unitcode;
		this.unitname = unitname;
	}

	public TNcBdCorp(Integer dr, String ts, String unitcode, String unitname,
			String fatherCorp) {
		this.dr = dr;
		this.ts = ts;
		this.unitcode = unitcode;
		this.unitname = unitname;
		this.fatherCorp = fatherCorp;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_NC_BD_CORP")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "PK_CORP", unique = true, nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public Integer getDr() {
		return this.dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "UNITCODE", nullable = false, length = 40)
	public String getUnitcode() {
		return this.unitcode;
	}

	public void setUnitcode(String unitcode) {
		this.unitcode = unitcode;
	}

	@Column(name = "UNITNAME", nullable = false, length = 200)
	public String getUnitname() {
		return this.unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	@Column(name = "FATHER_CORP", length = 4)
	public String getFatherCorp() {
		return this.fatherCorp;
	}

	public void setFatherCorp(String fatherCorp) {
		this.fatherCorp = fatherCorp;
	}
	
	@Transient
	public boolean getHasChild() {
		return hasChild;
	}

	public void setHasChild(boolean hasChild) {
		this.hasChild = hasChild;
	}
	
	@Override
	@Transient
	public Long getId() {
		return null;
	}

	@Override
	public void setId(Long arg0) {
		
	}

}
