package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:19 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.AbstractEntity;

/**
 * TNcSmUser generated by hbm2java
 */
@Entity
@Table(name = "T_NC_SM_USER")
public class TNcSmUser extends AbstractEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 7725711397250332343L;
	
	private String cuserid;
	private Integer dr;
	private String ts;
	private String userCode;
	private String userName;
	private String ableTime;
	private String disableTime;
	private Boolean lockedTag;
	private String userNote;
	private String userPassword;
	private String authenType;
	private String langcode;
	private Integer pwdtype;
	private String pwdparam;
	private String pkCorp;

	public TNcSmUser() {
	}

	public TNcSmUser(String userCode, String userName, String pkCorp) {
		this.userCode = userCode;
		this.userName = userName;
		this.pkCorp = pkCorp;
	}

	public TNcSmUser(Integer dr, String ts, String userCode, String userName,
			String ableTime, String disableTime, Boolean lockedTag,
			String userNote, String userPassword, String authenType,
			String langcode, Integer pwdtype, String pwdparam, String pkCorp) {
		this.dr = dr;
		this.ts = ts;
		this.userCode = userCode;
		this.userName = userName;
		this.ableTime = ableTime;
		this.disableTime = disableTime;
		this.lockedTag = lockedTag;
		this.userNote = userNote;
		this.userPassword = userPassword;
		this.authenType = authenType;
		this.langcode = langcode;
		this.pwdtype = pwdtype;
		this.pwdparam = pwdparam;
		this.pkCorp = pkCorp;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_NC_SM_USER")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "CUSERID", unique = true, nullable = false, length = 20)
	public String getCuserid() {
		return this.cuserid;
	}

	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public Integer getDr() {
		return this.dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "USER_CODE", nullable = false, length = 50)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "USER_NAME", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "ABLE_TIME", length = 10)
	public String getAbleTime() {
		return this.ableTime;
	}

	public void setAbleTime(String ableTime) {
		this.ableTime = ableTime;
	}

	@Column(name = "DISABLE_TIME", length = 10)
	public String getDisableTime() {
		return this.disableTime;
	}

	public void setDisableTime(String disableTime) {
		this.disableTime = disableTime;
	}

	@Column(name = "LOCKED_TAG", length = 1)
	public Boolean getLockedTag() {
		return this.lockedTag;
	}

	public void setLockedTag(Boolean lockedTag) {
		this.lockedTag = lockedTag;
	}

	@Column(name = "USER_NOTE", length = 50)
	public String getUserNote() {
		return this.userNote;
	}

	public void setUserNote(String userNote) {
		this.userNote = userNote;
	}

	@Column(name = "USER_PASSWORD", length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "AUTHEN_TYPE", length = 100)
	public String getAuthenType() {
		return this.authenType;
	}

	public void setAuthenType(String authenType) {
		this.authenType = authenType;
	}

	@Column(name = "LANGCODE", length = 20)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "PWDTYPE", precision = 22, scale = 0)
	public Integer getPwdtype() {
		return this.pwdtype;
	}

	public void setPwdtype(Integer pwdtype) {
		this.pwdtype = pwdtype;
	}

	@Column(name = "PWDPARAM", length = 50)
	public String getPwdparam() {
		return this.pwdparam;
	}

	public void setPwdparam(String pwdparam) {
		this.pwdparam = pwdparam;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Override
	@Transient
	public Long getId() {
		return null;
	}

	@Override
	public void setId(Long arg0) {
		
	}

}
