package com.wanda.ccs.model;

// Generated 2011-10-17 18:01:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.xcesys.extras.core.dao.model.DeleteableEntity;

/**
 * TPublisher generated by hbm2java
 */
@Entity
@Table(name = "T_PUBLISHER")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class TPublisher extends DeleteableEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 15955063645264869L;
	private Long id;
	private Long isdelete;
	private Date updatetime;
	private String publishercode;
	private String publishername;
	private String contact;
	private String contactphone;
	private String contactmobile;
	private String contactemail;
	private String publisherphone;
	private String publisherfax;
	private String publisheremail;
	private String publisheraddress;
	private String bank;
	private String bankaccount;
	private String contactemail1;
	private String contactemail2;
	private String contactemail3;
	private String contactemail4;
	private String shortname;
	private String pincode;
	private Boolean isemail;
	private Boolean isemail1;
	private Boolean isemail2;
	private Boolean isemail3;
	private Boolean isemail4;
	private Set<TFilm> tFilms = new HashSet<TFilm>(0);

	public TPublisher() {
	}


	@SequenceGenerator(name = "generator", sequenceName = "S_T_PUBLISHER")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "SEQID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ISDELETE", precision = 38, scale = 0)
	public Long getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Long isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "UPDATETIME")
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "PUBLISHERCODE", length = 20)
	public String getPublishercode() {
		return this.publishercode;
	}

	public void setPublishercode(String publishercode) {
		this.publishercode = publishercode;
	}

	@Column(name = "PUBLISHERNAME", length = 90)
	public String getPublishername() {
		return this.publishername;
	}

	public void setPublishername(String publishername) {
		this.publishername = publishername;
	}

	@Column(name = "CONTACT", length = 60)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "CONTACTPHONE", length = 20)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@Column(name = "CONTACTMOBILE", length = 20)
	public String getContactmobile() {
		return this.contactmobile;
	}

	public void setContactmobile(String contactmobile) {
		this.contactmobile = contactmobile;
	}

	@Column(name = "CONTACTEMAIL", length = 30)
	public String getContactemail() {
		return this.contactemail;
	}

	public void setContactemail(String contactemail) {
		this.contactemail = contactemail;
	}

	@Column(name = "PUBLISHERPHONE", length = 20)
	public String getPublisherphone() {
		return this.publisherphone;
	}

	public void setPublisherphone(String publisherphone) {
		this.publisherphone = publisherphone;
	}

	@Column(name = "PUBLISHERFAX", length = 20)
	public String getPublisherfax() {
		return this.publisherfax;
	}

	public void setPublisherfax(String publisherfax) {
		this.publisherfax = publisherfax;
	}

	@Column(name = "PUBLISHEREMAIL", length = 30)
	public String getPublisheremail() {
		return this.publisheremail;
	}

	public void setPublisheremail(String publisheremail) {
		this.publisheremail = publisheremail;
	}

	@Column(name = "PUBLISHERADDRESS", length = 150)
	public String getPublisheraddress() {
		return this.publisheraddress;
	}

	public void setPublisheraddress(String publisheraddress) {
		this.publisheraddress = publisheraddress;
	}

	@Column(name = "BANK", length = 150)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "BANKACCOUNT", length = 50)
	public String getBankaccount() {
		return this.bankaccount;
	}

	public void setBankaccount(String bankaccount) {
		this.bankaccount = bankaccount;
	}

	@Column(name = "CONTACTEMAIL1", length = 30)
	public String getContactemail1() {
		return this.contactemail1;
	}

	public void setContactemail1(String contactemail1) {
		this.contactemail1 = contactemail1;
	}

	@Column(name = "CONTACTEMAIL2", length = 30)
	public String getContactemail2() {
		return this.contactemail2;
	}

	public void setContactemail2(String contactemail2) {
		this.contactemail2 = contactemail2;
	}

	@Column(name = "CONTACTEMAIL3", length = 30)
	public String getContactemail3() {
		return this.contactemail3;
	}

	public void setContactemail3(String contactemail3) {
		this.contactemail3 = contactemail3;
	}

	@Column(name = "CONTACTEMAIL4", length = 30)
	public String getContactemail4() {
		return this.contactemail4;
	}

	public void setContactemail4(String contactemail4) {
		this.contactemail4 = contactemail4;
	}

	@Column(name = "SHORTNAME", length = 60)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "PINCODE", length = 20)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "ISEMAIL", precision = 38, scale = 0)
	public Boolean getIsemail() {
		return this.isemail;
	}

	public void setIsemail(Boolean isemail) {
		this.isemail = isemail;
	}

	@Column(name = "ISEMAIL1", precision = 38, scale = 0)
	public Boolean getIsemail1() {
		return this.isemail1;
	}

	public void setIsemail1(Boolean isemail1) {
		this.isemail1 = isemail1;
	}

	@Column(name = "ISEMAIL2", precision = 38, scale = 0)
	public Boolean getIsemail2() {
		return this.isemail2;
	}

	public void setIsemail2(Boolean isemail2) {
		this.isemail2 = isemail2;
	}

	@Column(name = "ISEMAIL3", precision = 38, scale = 0)
	public Boolean getIsemail3() {
		return this.isemail3;
	}

	public void setIsemail3(Boolean isemail3) {
		this.isemail3 = isemail3;
	}

	@Column(name = "ISEMAIL4", precision = 38, scale = 0)
	public Boolean getIsemail4() {
		return this.isemail4;
	}

	public void setIsemail4(Boolean isemail4) {
		this.isemail4 = isemail4;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tPublisher")
	public Set<TFilm> gettFilms() {
		return this.tFilms;
	}

	public void settFilms(Set<TFilm> tFilms) {
		this.tFilms = tFilms;
	}

}
