package com.wanda.ccs.model;

// Generated 2011-10-26 19:16:53 by Hibernate Tools 3.4.0.CR1

import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TReqCardTypeRecharge generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_CARD_TYPE_RECHARGE")
public class TReqCardTypeRecharge extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -965488141662527036L;
	
	private Long id;
	private TReqCardType tReqCardType;
	private Long amount;
	private Long addValue;

	public TReqCardTypeRecharge() {
	}

	public TReqCardTypeRecharge(TReqCardType tReqCardType, Long amount) {
		this.tReqCardType = tReqCardType;
		this.amount = amount;
	}

	public TReqCardTypeRecharge(TReqCardType tReqCardType, Long amount,
			Long addValue) {
		this.tReqCardType = tReqCardType;
		this.amount = amount;
		this.addValue = addValue;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_CARD_TYPE_RECHARGE", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_CARD_TYPE_RECHARGE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQ_CARD_TYPE_ID", nullable = false)
	public TReqCardType gettReqCardType() {
		return this.tReqCardType;
	}

	public void settReqCardType(TReqCardType tReqCardType) {
		this.tReqCardType = tReqCardType;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 10)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "ADD_VALUE", precision = 10)
	public Long getAddValue() {
		return this.addValue;
	}

	public void setAddValue(Long addValue) {
		this.addValue = addValue;
	}

}
