package com.wanda.ccs.model;

// Generated 2011-10-26 19:16:53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TReqTtypeUseRule generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_TTYPE_USE_RULE")
public class TReqTtypeUseRule extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 1045981605663686008L;
	
	private Long id;
	private TReqTicketType tReqTicketType;
	private String ruleCondition;
	private String ruleUse;
	private Long ruleOrder;
	private String description;
	private TMarketingCampaign tMarketingCampaign;
	private Long marketingCampaignId; 

	public TReqTtypeUseRule() {
	}

	public TReqTtypeUseRule(String ruleUse, String description, Long ruleOrder) {
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
	}

	public TReqTtypeUseRule(TReqTicketType tReqTicketType,
			TMarketingCampaign tMarketingCampaign, String ruleCondition,
			String ruleUse, String description, Long ruleOrder) {
		this.tReqTicketType = tReqTicketType;
		this.tMarketingCampaign = tMarketingCampaign;
		this.ruleCondition = ruleCondition;
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
	}
	
	public TReqTtypeUseRule(TReqTicketType tReqTicketType,
			TMarketingCampaign tMarketingCampaign, String ruleCondition,
			String ruleUse, String description, Long ruleOrder, Long marketingCampaignId) {
		this.tReqTicketType = tReqTicketType;
		this.tMarketingCampaign = tMarketingCampaign;
		this.ruleCondition = ruleCondition;
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
		this.marketingCampaignId = marketingCampaignId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_TTYPE_USE_RULE", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_TTYPE_USE_RULE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQ_TICKET_TYPE_ID")
	public TReqTicketType gettReqTicketType() {
		return this.tReqTicketType;
	}

	public void settReqTicketType(TReqTicketType tReqTicketType) {
		this.tReqTicketType = tReqTicketType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MARKETING_CAMPAIGN_ID", insertable = false, updatable = false)
	public TMarketingCampaign gettMarketingCampaign() {
		return this.tMarketingCampaign;
	}

	public void settMarketingCampaign(TMarketingCampaign tMarketingCampaign) {
		this.tMarketingCampaign = tMarketingCampaign;
	}

	@Column(name = "RULE_CONDITION", length = 4000)
	public String getRuleCondition() {
		return this.ruleCondition;
	}

	public void setRuleCondition(String ruleCondition) {
		this.ruleCondition = ruleCondition;
	}

	@Column(name = "RULE_USE", nullable = false, length = 4000)
	public String getRuleUse() {
		return this.ruleUse;
	}

	public void setRuleUse(String ruleUse) {
		this.ruleUse = ruleUse;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RULE_ORDER", nullable = false, precision = 38, scale = 0)
	public Long getRuleOrder() {
		return this.ruleOrder;
	}

	public void setRuleOrder(Long ruleOrder) {
		this.ruleOrder = ruleOrder;
	}
	
	@Column(name = "MARKETING_CAMPAIGN_ID")
	public Long getMarketingCampaignId() {
		return marketingCampaignId;
	}

	public void setMarketingCampaignId(Long marketingCampaignId) {
		this.marketingCampaignId = marketingCampaignId;
	}

}
