package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TReqVoucherTypeDef generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_VOUCHER_TYPE_DEF")
public class TReqVoucherTypeDef extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -2190505805282049779L;
	
	private Long id;
	private TReqVoucherType tReqVoucherType; //券类新增、编辑、删除请求序列号
	private Integer showValue; //票面价值，只有代金券使用该字段
	private Integer realValue; //实际价值，兑换券和代金券使用该字段
	private Integer discount; //折扣比例，只有折扣券使用该字段
	private Long seatLimit; //缺省每座可用张数，仅对代金券有效
	private Long expiryMonth; //券按月计算的有效试用期
	private Boolean useDefault;; //是否使用院线的缺省设置
	private Long orderLimit; //缺省每场可用张数，仅对代金券有效
	private String useOnGoods = "Y";//是否可用于卖品
	private Long minPrice = 0l;  //单张票价满多少元可使用

	public TReqVoucherTypeDef() {
	}
	
	public TReqVoucherTypeDef(TVoucherTypeDef def, TReqVoucherType tReqVoucherType){
		this.tReqVoucherType = tReqVoucherType;
		setShowValue(def.getShowValue());
		setRealValue(def.getRealValue());
		setDiscount(def.getDiscount());
		setSeatLimit(def.getSeatLimit());
		setExpiryMonth(def.getExpiryMonth());
		setUseDefault(def.getUseDefault());
		setOrderLimit(def.getOrderLimit());
		setUseOnGoods(def.getUseOnGoods());
		setMinPrice(def.getMinPrice());
	}

	public TReqVoucherTypeDef(TReqVoucherType tReqVoucherType, Long seatLimit,
			Long expiryMonth,Boolean useDefault, Long orderLimit) {
		this.tReqVoucherType = tReqVoucherType;
		this.seatLimit = seatLimit;
		this.expiryMonth = expiryMonth;
		this.useDefault = useDefault;
		this.orderLimit = orderLimit;
	}

	public TReqVoucherTypeDef(TReqVoucherType tReqVoucherType,
			Integer showValue, Integer realValue, Integer discount,
			Long seatLimit, Long expiryMonth, Boolean useDefault,
			Long orderLimit, Long minPrice) {
		this.tReqVoucherType = tReqVoucherType;
		this.showValue = showValue;
		this.realValue = realValue;
		this.discount = discount;
		this.seatLimit = seatLimit;
		this.expiryMonth = expiryMonth;
		this.useDefault = useDefault;
		this.orderLimit = orderLimit;
		this.minPrice = minPrice;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_VOUCHER_TYPE_DEF")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_VOUCHER_TYPE_DEF_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQ_VOUCHER_TYPE_ID", nullable = false)
	public TReqVoucherType gettReqVoucherType() {
		return this.tReqVoucherType;
	}

	public void settReqVoucherType(TReqVoucherType tReqVoucherType) {
		this.tReqVoucherType = tReqVoucherType;
	}

	@Column(name = "SHOW_VALUE", precision = 22, scale = 0)
	public Integer getShowValue() {
		return this.showValue;
	}

	public void setShowValue(Integer showValue) {
		this.showValue = showValue;
	}

	@Column(name = "REAL_VALUE", precision = 22, scale = 0)
	public Integer getRealValue() {
		return this.realValue;
	}

	public void setRealValue(Integer realValue) {
		this.realValue = realValue;
	}

	@Column(name = "DISCOUNT", precision = 5)
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Column(name = "SEAT_LIMIT", nullable = false, precision = 22, scale = 0)
	public Long getSeatLimit() {
		return this.seatLimit;
	}

	public void setSeatLimit(Long seatLimit) {
		this.seatLimit = seatLimit;
	}

	@Column(name = "EXPIRY_MONTH", nullable = false, precision = 22, scale = 0)
	public Long getExpiryMonth() {
		return this.expiryMonth;
	}

	public void setExpiryMonth(Long expiryMonth) {
		this.expiryMonth = expiryMonth;
	}

	@Column(name = "USE_DEFAULT", nullable = false, length = 1)
	public String getUseDefault() {
		return this.useDefault ? "Y" : "N";
	}

	public void setUseDefault(String str) {
		this.useDefault = str.equals("Y");
	}

	@Column(name = "ORDER_LIMIT", nullable = false, precision = 22, scale = 0)
	public Long getOrderLimit() {
		return this.orderLimit;
	}

	public void setOrderLimit(Long orderLimit) {
		this.orderLimit = orderLimit;
	}
	
	@Column(name = "USE_ON_GOODS", nullable = false, length = 1)
	public String getUseOnGoods() {
		return useOnGoods;
	}

	public void setUseOnGoods(String useOnGoods) {
		this.useOnGoods = useOnGoods;
	}
	
	@Column(name = "MIN_PRICE", nullable = true, precision = 22, scale = 0)
	public Long getMinPrice() {
		return minPrice;
	}
	
	public void setMinPrice(Long minPrice) {
		this.minPrice = minPrice;
	}
}
