package com.wanda.ccs.model;

// Generated 2011-10-26 19:16:53 by Hibernate Tools 3.4.0.CR1

import com.wanda.ccs.data.price.Rule;
import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TReqTtypeLimitRule generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_TTYPE_LIMIT_RULE")
public class TReqTtypeLimitRule extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 4788250673096654211L;
	
	private Long id;
	private TReqTicketType tReqTicketType;
	private String rule;
	private String description;
	private Long ruleOrder;

	public TReqTtypeLimitRule() {
	}

	public TReqTtypeLimitRule(TReqTicketType tReqTicketType, String rule,
			String description, Long ruleOrder) {
		this.tReqTicketType = tReqTicketType;
		this.rule = rule;
		this.description = description;
		this.ruleOrder = ruleOrder;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_TTYPE_LIMIT_RULE", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_TTYPE_LIMIT_RULE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQ_TICKET_TYPE_ID", nullable = false)
	public TReqTicketType gettReqTicketType() {
		return this.tReqTicketType;
	}

	public void settReqTicketType(TReqTicketType tReqTicketType) {
		this.tReqTicketType = tReqTicketType;
	}

	@Column(name = "RULE", nullable = false, length = 4000)
	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	@Transient
	public boolean getReverse() {
		return rule != null && rule.startsWith(Rule.REVERSE_PREFIX);
	}
	
	public void setReverse(boolean r) {
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RULE_ORDER", nullable = false, precision = 38, scale = 0)
	public Long getRuleOrder() {
		return this.ruleOrder;
	}

	public void setRuleOrder(Long ruleOrder) {
		this.ruleOrder = ruleOrder;
	}

}
