package com.wanda.ccs.model;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TReqVoucherTicketType generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_VOUCHER_TICKET_TYPE")
public class TReqVoucherTicketType extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 323190854739074341L;

	private Long id;
	private Long voucherTypeId;
	private Long reqTicketTypeId;
	private TVoucherType tVoucherType;
	private TReqTicketType tReqTicketType;
	
	public TReqVoucherTicketType(){
		
	}

	public TReqVoucherTicketType(TReqTicketType tReqTicketType, Long voucherTypeId){
		this.tReqTicketType = tReqTicketType;
		this.voucherTypeId = voucherTypeId;
		this.reqTicketTypeId = tReqTicketType.getId();
	}
	
	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_VOUCHER_TICKET_TYPE")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_VOUCHER_TICKET_TYPE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "VOUCHER_TYPE_ID", nullable = false)
	public Long getVoucherTypeId() {
		return voucherTypeId;
	}

	public void setVoucherTypeId(Long voucherTypeId) {
		this.voucherTypeId = voucherTypeId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return this.tVoucherType;
	}

	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}

	@Column(name = "REQ_TICKET_TYPE_ID", nullable = false)
	public Long getReqTicketTypeId() {
		return reqTicketTypeId;
	}

	public void setReqTicketTypeId(Long reqTicketTypeId) {
		this.reqTicketTypeId = reqTicketTypeId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQ_TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TReqTicketType gettReqTicketType() {
		return tReqTicketType;
	}

	public void settReqTicketType(TReqTicketType tReqTicketType) {
		this.tReqTicketType = tReqTicketType;
	}

}
