package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TReqVoucherType generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_VOUCHER_TYPE")
public class TReqVoucherType extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 6534610868372159265L;
	
	private Long id;
	private TReqTicketType tReqTicketType; //券类新增、编辑、删除请求序列号
	private TVoucherType tVoucherType; //该请求对应的实际券类序列号
	private Long voucherTypeId;
	private String typeName;  //券类型名称
	private String reqStatus; //请求状态 A待审核 P审核通过 E发回返修  F审核不通过 X取消审核
	private String typeCode; //券类型编码
	private String voucherLevel;//券类型级别
	private String ownerRegion; //区域级券的负责区域代码
	private String useType; //券使用方式
	private String description; //备注
	private String reqType; //请求类型 N为新增券类请求  E为编辑券类请求  X为删除券类请求
	private String reqRegion; //发起请求的区域
	private String submitBy; //发起申请的用户姓名
	private Date submitDate;//发起申请时间
	private String approveBy; //审核申请的用户姓名
	private Date approveDate; //审核申请的时间
	private String submitById; //发起申请的用户登录id
	private String approveById; //审核申请的用户登录id
	private Set<TReqVoucherTypeDef> tReqVoucherTypeDefs = new HashSet<TReqVoucherTypeDef>(
			0);

	public TReqVoucherType() {
	}
	public TReqVoucherType(TVoucherType tVoucherType, TReqTicketType tReqTicketType){
		setTypeName(tVoucherType.getTypeName());
		setTypeCode(tVoucherType.getTypeCode());
		setVoucherLevel(tVoucherType.getVoucherLevel());
		setOwnerRegion(tVoucherType.getOwnerRegion());
		setUseType(tVoucherType.getUseType());
		setDescription(tVoucherType.getDescription());
		if (tReqTicketType != null) {
			this.tReqTicketType = tReqTicketType;
			setReqType(tReqTicketType.getReqType());
			setReqStatus(tReqTicketType.getReqStatus());
			setReqRegion(tReqTicketType.getReqRegion());
		}
		if (tVoucherType.getId() != null && tVoucherType.getId() > 0) {
			this.tVoucherType = tVoucherType;
			this.voucherTypeId = tVoucherType.getId();
		}
	}
	public TReqVoucherType(TReqTicketType tReqTicketType, String typeName,
			String reqStatus, String typeCode, String voucherLevel,
			String useType, String reqType) {
		this.tReqTicketType = tReqTicketType;
		this.typeName = typeName;
		this.reqStatus = reqStatus;
		this.typeCode = typeCode;
		this.voucherLevel = voucherLevel;
		this.useType = useType;
		this.reqType = reqType;
	}

	public TReqVoucherType(TReqTicketType tReqTicketType,
			TVoucherType tVoucherType, String typeName, String reqStatus,
			String typeCode, String voucherLevel, String ownerRegion,
			String useType, String description, String reqType,
			String reqRegion, String submitBy, Date submitDate,
			String approveBy, Date approveDate, String submitById,
			String approveById, Set<TReqVoucherTypeDef> tReqVoucherTypeDefs) {
		this.tReqTicketType = tReqTicketType;
		this.tVoucherType = tVoucherType;
		this.typeName = typeName;
		this.reqStatus = reqStatus;
		this.typeCode = typeCode;
		this.voucherLevel = voucherLevel;
		this.ownerRegion = ownerRegion;
		this.useType = useType;
		this.description = description;
		this.reqType = reqType;
		this.reqRegion = reqRegion;
		this.submitBy = submitBy;
		this.submitDate = submitDate;
		this.approveBy = approveBy;
		this.approveDate = approveDate;
		this.submitById = submitById;
		this.approveById = approveById;
		this.tReqVoucherTypeDefs = tReqVoucherTypeDefs;
	}

	@Id
	@Column(name = "REQ_VOUCHER_TYPE_ID")
	@GeneratedValue(generator = "foreigner")
	@GenericGenerator(name = "foreigner", strategy = "foreign", parameters = { @Parameter(name = "property", value = "tReqTicketType") })
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TReqTicketType gettReqTicketType() {
		return this.tReqTicketType;
	}

	public void settReqTicketType(TReqTicketType tReqTicketType) {
		this.tReqTicketType = tReqTicketType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_TYPE_ID", insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return this.tVoucherType;
	}
	
	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}
	
	@Column(name = "VOUCHER_TYPE_ID")
	public Long getVoucherTypeId() {
		return voucherTypeId;
	}
	public void setVoucherTypeId(Long voucherTypeId) {
		this.voucherTypeId = voucherTypeId;
	}
	
	@Column(name = "TYPE_NAME", nullable = false)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "REQ_STATUS", nullable = false, length = 1)
	public String getReqStatus() {
		return this.reqStatus;
	}

	public void setReqStatus(String reqStatus) {
		this.reqStatus = reqStatus;
	}

	@Column(name = "TYPE_CODE", nullable = false, length = 50)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "VOUCHER_LEVEL", nullable = false, length = 1)
	public String getVoucherLevel() {
		return this.voucherLevel;
	}

	public void setVoucherLevel(String voucherLevel) {
		this.voucherLevel = voucherLevel;
	}

	@Column(name = "OWNER_REGION", length = 20)
	public String getOwnerRegion() {
		return this.ownerRegion;
	}

	public void setOwnerRegion(String ownerRegion) {
		this.ownerRegion = ownerRegion;
	}

	@Column(name = "USE_TYPE", nullable = false, length = 1)
	public String getUseType() {
		return this.useType;
	}

	public void setUseType(String useType) {
		this.useType = useType;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "REQ_TYPE", nullable = false, length = 1)
	public String getReqType() {
		return this.reqType;
	}

	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	@Column(name = "REQ_REGION", length = 20)
	public String getReqRegion() {
		return this.reqRegion;
	}

	public void setReqRegion(String reqRegion) {
		this.reqRegion = reqRegion;
	}

	@Column(name = "SUBMIT_BY", length = 40)
	public String getSubmitBy() {
		return this.submitBy;
	}

	public void setSubmitBy(String submitBy) {
		this.submitBy = submitBy;
	}

	@Column(name = "SUBMIT_DATE", length = 11)
	public Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	@Column(name = "APPROVE_BY", length = 40)
	public String getApproveBy() {
		return this.approveBy;
	}

	public void setApproveBy(String approveBy) {
		this.approveBy = approveBy;
	}

	@Column(name = "APPROVE_DATE", length = 11)
	public Date getApproveDate() {
		return this.approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	@Column(name = "SUBMIT_BY_ID", length = 20)
	public String getSubmitById() {
		return this.submitById;
	}

	public void setSubmitById(String submitById) {
		this.submitById = submitById;
	}

	@Column(name = "APPROVE_BY_ID", length = 20)
	public String getApproveById() {
		return this.approveById;
	}

	public void setApproveById(String approveById) {
		this.approveById = approveById;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tReqVoucherType")
	public Set<TReqVoucherTypeDef> gettReqVoucherTypeDefs() {
		return this.tReqVoucherTypeDefs;
	}

	public void settReqVoucherTypeDefs(
			Set<TReqVoucherTypeDef> tReqVoucherTypeDefs) {
		this.tReqVoucherTypeDefs = tReqVoucherTypeDefs;
	}

}
