package com.wanda.ccs.model;

// Generated 2011-10-26 19:16:53 by Hibernate Tools 3.4.0.CR1

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TReqLog generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_LOG")
public class TReqLog extends VersionableEntity implements java.io.Serializable {
	private static final long serialVersionUID = 4680362860156738852L;
	
	private Long id; //请求记录编号
	private Long requestId;//请求记录编号
	private String actionName;//操作名称
	private String actionBy;//执行操作的用户的姓名
	private Date actionTime;//执行操作的时间
	private String comments;//执行操作的用户填写的备注信息
	private String fromStatus;//执行操作前请求的状态
	private String toStatus;//执行操作后请求的状态
	private String actionById;
	

	public TReqLog() {
	}

	public TReqLog(Long requestId, String actionName, String actionBy,
			Date actionTime) {
		this.requestId = requestId;
		this.actionName = actionName;
		this.actionBy = actionBy;
		this.actionTime = actionTime;
	}

	public TReqLog(Long requestId, String actionName, String actionBy,
			Date actionTime, String comments, String fromStatus, String toStatus) {
		this.requestId = requestId;
		this.actionName = actionName;
		this.actionBy = actionBy;
		this.actionTime = actionTime;
		this.comments = comments;
		this.fromStatus = fromStatus;
		this.toStatus = toStatus;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQ_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "REQ_LOG_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "REQUEST_ID", nullable = false, precision = 38, scale = 0)
	public Long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}
	
	
	@Column(name = "ACTION_NAME", nullable = false, length = 600)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "ACTION_BY", nullable = false, length = 100)
	public String getActionBy() {
		return this.actionBy;
	}

	public void setActionBy(String actionBy) {
		this.actionBy = actionBy;
	}

	@Column(name = "ACTION_TIME", nullable = false)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "COMMENTS",length = 2000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "FROM_STATUS", length = 765)
	public String getFromStatus() {
		return this.fromStatus;
	}

	public void setFromStatus(String fromStatus) {
		this.fromStatus = fromStatus;
	}
	
	@Column(name = "TO_STATUS", length = 765)
	public String getToStatus() {
		return this.toStatus;
	}

	public void setToStatus(String toStatus) {
		this.toStatus = toStatus;
	}
	
	@Column(name = "ACTION_BY_ID",length=100)
	public String getActionById() {
		return actionById;
	}

	public void setActionById(String actionById) {
		this.actionById = actionById;
	}
}
