package com.wanda.ccs.model;

// Generated 2011-10-26 19:16:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TReqCardType generated by hbm2java
 */
@Entity
@Table(name = "T_REQ_CARD_TYPE")
public class TReqCardType extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -5289085170269573971L;
	
	private Long id;
	private TReqTicketType tReqTicketType;
	private String reqType;
	private String reqStatus;//请求状态。A - 等待审批，P - 审批通过，E - 发回修改，F - 审批不通过，X - 取消申请
	private String reqRegion;
	private TCardType tCardType;
	private Long cardTypeId;
	private String typeName;
	private String typeCode;
	private String cardLevel;
	private String ownerRegion;
	private String valueType;
	private String endorsement;
	private String description;
	private Long expiryMonth = 0l;// 有效期
	private String approveById; // 审核人
	private String approveBy; // 审核人
	private Date approveDate; // 审核时间
	private String submitById; // 提交人
	private String submitBy; // 提交人
	private Date submitDate; // 提交时间
	private String isRechargeable;
	private Set<TReqCardTypeDef> tReqCardTypeDefs = new HashSet<TReqCardTypeDef>(
			0);
	private Set<TReqCardTypeRecharge> tReqCardTypeRecharges = new HashSet<TReqCardTypeRecharge>(
			0);

	public TReqCardType() {
	}

	public TReqCardType(TCardType type, TReqTicketType reqTicketType) {
		setTypeName(type.getTypeName());
		setTypeCode(type.getTypeCode());
		setCardLevel(type.getCardLevel());
		setOwnerRegion(type.getOwnerRegion());
		setValueType(type.getValueType());
		setEndorsement(type.getEndorsement());
		setDescription(type.getDescription());
		setExpiryMonth(type.getExpiryMonth());
		setIsRechargeable(type.getIsRechargeable());
		if (reqTicketType != null) {
			tReqTicketType = reqTicketType;
			setReqType(reqTicketType.getReqType());
			setReqStatus(reqTicketType.getReqStatus());
			setReqRegion(reqTicketType.getReqRegion());
		}

		if (type.getId() != null && type.getId() > 0) {
			tCardType = type;
			setCardTypeId(type.getId());
		}
	}

	public TReqCardType(TReqTicketType tReqTicketType, String typeName,
			String reqStatus, String typeCode, String cardLevel,
			String valueType, String reqType) {
		this.tReqTicketType = tReqTicketType;
		this.typeName = typeName;
		this.reqStatus = reqStatus;
		this.typeCode = typeCode;
		this.cardLevel = cardLevel;
		this.valueType = valueType;
		this.reqType = reqType;
	}

	public TReqCardType(TReqTicketType tReqTicketType, TCardType tCardType,
			String typeName, String reqStatus, String typeCode,
			String cardLevel, String ownerRegion, String valueType,
			String remarks, String reqType, String reqRegion,
			Set<TReqCardTypeDef> tReqCardTypeDefs,
			Set<TReqCardTypeRecharge> tReqCardTypeRecharges) {
		this.tReqTicketType = tReqTicketType;
		this.tCardType = tCardType;
		this.typeName = typeName;
		this.reqStatus = reqStatus;
		this.typeCode = typeCode;
		this.cardLevel = cardLevel;
		this.ownerRegion = ownerRegion;
		this.valueType = valueType;
		this.description = remarks;
		this.reqType = reqType;
		this.reqRegion = reqRegion;
		this.tReqCardTypeDefs = tReqCardTypeDefs;
		this.tReqCardTypeRecharges = tReqCardTypeRecharges;
	}

	@Id
	@Column(name = "REQ_CARD_TYPE_ID")
	@GeneratedValue(generator = "foreigner")
	@GenericGenerator(name = "foreigner", strategy = "foreign", parameters = { @Parameter(name = "property", value = "tReqTicketType") })
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TReqTicketType gettReqTicketType() {
		return this.tReqTicketType;
	}

	public void settReqTicketType(TReqTicketType tReqTicketType) {
		this.tReqTicketType = tReqTicketType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_TYPE_ID", insertable = false, updatable = false)
	public TCardType gettCardType() {
		return this.tCardType;
	}

	public void settCardType(TCardType tCardType) {
		this.tCardType = tCardType;
	}

	@Column(name = "CARD_TYPE_ID", nullable = false)
	public Long getCardTypeId() {
		return cardTypeId;
	}

	public void setCardTypeId(Long cardTypeId) {
		this.cardTypeId = cardTypeId;
	}

	@Column(name = "TYPE_NAME", nullable = false, length = 3072)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "REQ_STATUS", nullable = false, length = 1)
	public String getReqStatus() {
		return this.reqStatus;
	}

	public void setReqStatus(String reqStatus) {
		this.reqStatus = reqStatus;
	}

	@Column(name = "TYPE_CODE", nullable = false, length = 50)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "CARD_LEVEL", nullable = false, length = 1)
	public String getCardLevel() {
		return this.cardLevel;
	}

	public void setCardLevel(String cardLevel) {
		this.cardLevel = cardLevel;
	}

	@Column(name = "OWNER_REGION", length = 20)
	public String getOwnerRegion() {
		return this.ownerRegion;
	}

	public void setOwnerRegion(String ownerRegion) {
		this.ownerRegion = ownerRegion;
	}

	@Column(name = "VALUE_TYPE", nullable = false, length = 1)
	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	@Column(name = "ENDORSEMENT", length = 2000)
	public String getEndorsement() {
		return endorsement;
	}

	public void setEndorsement(String endorsement) {
		this.endorsement = endorsement;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "REQ_TYPE", nullable = false, length = 1)
	public String getReqType() {
		return this.reqType;
	}

	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	@Column(name = "REQ_REGION", length = 20)
	public String getReqRegion() {
		return this.reqRegion;
	}

	public void setReqRegion(String reqRegion) {
		this.reqRegion = reqRegion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tReqCardType")
	public Set<TReqCardTypeDef> gettReqCardTypeDefs() {
		return this.tReqCardTypeDefs;
	}

	public void settReqCardTypeDefs(Set<TReqCardTypeDef> tReqCardTypeDefs) {
		this.tReqCardTypeDefs = tReqCardTypeDefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tReqCardType")
	public Set<TReqCardTypeRecharge> gettReqCardTypeRecharges() {
		return this.tReqCardTypeRecharges;
	}

	public void settReqCardTypeRecharges(
			Set<TReqCardTypeRecharge> tReqCardTypeRecharges) {
		this.tReqCardTypeRecharges = tReqCardTypeRecharges;
	}

	@Column(name = "APPROVE_BY", length = 40)
	public String getApproveBy() {
		return approveBy;
	}

	public void setApproveBy(String approveBy) {
		this.approveBy = approveBy;
	}

	@Column(name = "APPROVE_DATE")
	public Date getApproveDate() {
		return approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	@Column(name = "SUBMIT_BY", length = 40)
	public String getSubmitBy() {
		return submitBy;
	}

	public void setSubmitBy(String submitBy) {
		this.submitBy = submitBy;
	}

	@Column(name = "SUBMIT_DATE")
	public Date getSubmitDate() {
		return submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	@Column(name = "EXPIRY_MONTH", nullable = false, precision = 38)
	public Long getExpiryMonth() {
		return expiryMonth;
	}

	public void setExpiryMonth(Long expiryMonth) {
		this.expiryMonth = expiryMonth;
	}

	@Column(name = "APPROVE_BY_ID", length = 20)
	public String getApproveById() {
		return approveById;
	}

	public void setApproveById(String approveById) {
		this.approveById = approveById;
	}

	@Column(name = "SUBMIT_BY_ID", length = 20)
	public String getSubmitById() {
		return submitById;
	}

	public void setSubmitById(String submitById) {
		this.submitById = submitById;
	}
	
	@Column(name = "IS_RECHARGEABLE")
	public String getIsRechargeable() {
		return isRechargeable;
	}

	public void setIsRechargeable(String isRechargeable) {
		this.isRechargeable = isRechargeable;
	}
}
