package com.wanda.ccs.model;

// Generated 2011-11-10 19:35:25 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.xcesys.extras.core.dao.model.BlameableEntity;
import com.xcesys.extras.core.util.StringUtil;
import com.xcesys.extras.util.ConvertUtil;

/**
 * TRoundTicketType generated by hbm2java
 */
@Entity
@Table(name = "T_ROUND_TICKET_TYPE")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class TRoundTicketType extends BlameableEntity implements
		Comparable<TRoundTicketType> {

	private static final long serialVersionUID = -6033636611338616600L;
	private Long id;
	private TPriceBase origPrice;
	private Long origPriceId;
	private Long adjustPriceId;
	private TPriceBase adjustPrice;
	private TTicketType tTicketType;
	private TSchedulePlanB tSchedulePlanB;
	private Long exchangeNum;
	private Long adjustAmount;
	private Boolean enabled;
	private String reason;
	private String block;
	/**
	 * 是否二次授权
	 */
	private Boolean needAuthorize;
	
	/** 根据票价规则计算得出的价格 */
	private Integer price;
	/**
	 * 会员优惠
	 */
	private Boolean memberDiscount;
	/**
	 * 会员积分
	 */
	private Long points;
	/**
	 * 市场价
	 */
	private Boolean standardPrice;
	/**
	 * 最低价格
	 */
	private Boolean lowestPrice;

	/**
	 * 开放销售渠道
	 */
	private String channel;
	/**
	 * 销售渠道的数组表现形式
	 */
	private String[] channels;
	/**
	 * 票类名称
	 */
	private String ticketTypeName;

	public TRoundTicketType() {
	}

	@Override
	public int compareTo(TRoundTicketType o) {
		TPriceBase origPrice1 = this.getOrigPrice();
		TPriceBase origPrice2 = o.getOrigPrice();
		if (origPrice1 != null && origPrice2 != null) {
			return origPrice1.getPrice() - origPrice2.getPrice();
		}

		return 0;
	}

	@Column(name = "ADJUST_AMOUNT", precision = 38, scale = 0)
	public Long getAdjustAmount() {
		return this.adjustAmount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADJUST_PRICE_ID", insertable = false, updatable = false)
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public TPriceBase getAdjustPrice() {
		return adjustPrice;
	}

	@Column(name = "ADJUST_PRICE_ID")
	public Long getAdjustPriceId() {
		return adjustPriceId;
	}

	@Column(name = "BLOCK", length = 2)
	public String getBlock() {
		return block;
	}

	@Column(name = "CHANNEL", length = 50)
	public String getChannel() {
		return channel;
	}

	@Transient
	public String[] getChannels() {
		if (!StringUtil.isNullOrBlank(this.channel)) {
			this.channels = this.channel.split(",");
			Arrays.sort(this.channels);
		}
		return channels;
	}

	@Column(name = "ENABLED", length = 1)
	public Boolean getEnabled() {
		return this.enabled;
	}

	@Column(name = "EXCHANGE_NUM", precision = 38, scale = 0)
	public Long getExchangeNum() {
		return this.exchangeNum;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_ROUND_TICKET_TYPE")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "ROUND_TICKET_TYPE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	@Column(name = "LOWEST_PRICE")
	public Boolean getLowestPrice() {
		return lowestPrice;
	}

	@Column(name = "MEMBER_DISCOUNT")
	public Boolean getMemberDiscount() {
		return memberDiscount;
	}
	
	@Column(name = "POINTS")
	public Long getPoints() {
		return points;
	}

	@Column(name = "TICKET_TYPE_NAME", nullable = false, length = 20)
	public String getTicketTypeName() {
		return this.ticketTypeName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORIG_PRICE_ID", insertable = false, updatable = false)
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public TPriceBase getOrigPrice() {
		return this.origPrice;
	}

	@Column(name = "ORIG_PRICE_ID")
	public Long getOrigPriceId() {
		return origPriceId;
	}

	@Transient
	public Integer getPrice() {
		return price;
	}

	/**
	 * 返回表示价格是否被改动的标记。
	 * 
	 * @return
	 */
	@Transient
	public boolean getPriceModified() {
		if (getOrigPrice() != null && getAdjustPrice() != null) {
			return this.origPrice.getPrice() != this.adjustPrice.getPrice();
		}
		return false;
	}

	@Column(name = "REASON", length = 100)
	public String getReason() {
		return this.reason;
	}

	@Column(name = "STANDARD_PRICE")
	public Boolean getStandardPrice() {
		return standardPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_SCHEDULE_PLAN_B_ID")
	public TSchedulePlanB gettSchedulePlanB() {
		return this.tSchedulePlanB;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_TICKET_TYPE_ID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public TTicketType gettTicketType() {
		return this.tTicketType;
	}

	public void setAdjustAmount(Long adjustAmount) {
		this.adjustAmount = adjustAmount;
	}

	public void setAdjustPrice(TPriceBase adjustPrice) {
		this.adjustPrice = adjustPrice;
	}

	public void setAdjustPriceId(Long adjustPriceId) {
		this.adjustPriceId = adjustPriceId;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public void setChannels(String[] channels) {
		this.channels = channels;
		if (this.channels != null) {
			Arrays.sort(channels);
			this.channel = ConvertUtil.convertArrayToCommaString(this.channels);
		}
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public void setExchangeNum(Long exchangeNum) {
		this.exchangeNum = exchangeNum;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setLowestPrice(Boolean lowestPrice) {
		this.lowestPrice = lowestPrice;
	}

	public void setMemberDiscount(Boolean memberDiscount) {
		this.memberDiscount = memberDiscount;
	}

	public void setTicketTypeName(String name) {
		this.ticketTypeName = name;
	}

	public void setOrigPrice(TPriceBase tPriceBase) {
		this.origPrice = tPriceBase;
	}

	public void setOrigPriceId(Long origPriceId) {
		this.origPriceId = origPriceId;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public void setStandardPrice(Boolean standardPrice) {
		this.standardPrice = standardPrice;
	}

	public void settSchedulePlanB(TSchedulePlanB tSchedulePlanB) {
		this.tSchedulePlanB = tSchedulePlanB;
	}

	public void settTicketType(TTicketType tTicketType) {
		this.tTicketType = tTicketType;
	}

	public void setPoints(Long points) {
		this.points = points;
	}

	@Column(name="NEED_AUTHORIZE")
	public Boolean getNeedAuthorize() {
		return needAuthorize;
	}

	public void setNeedAuthorize(Boolean needAuthorize) {
		this.needAuthorize = needAuthorize;
	}
}
