package com.wanda.ccs.model;

// Generated 2011-11-2 12:36:06 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.BlameableEntity;

/**
 * TTicketTypeCinema generated by hbm2java
 */
@Entity
@Table(name = "T_TICKET_TYPE_CINEMA")
public class TTicketTypeCinema extends BlameableEntity implements
		java.io.Serializable, IRegionCode {
	private static final long serialVersionUID = -7232861605545161504L;
	
	private Long id;
	private TCinema tCinema; // 影院Id
	private TTicketType tTicketType;// 票类型
	private TCardType tCardType;// 卡类型
	private TVoucherType tVoucherType; //券类型
	private String regionCode;// 区域代码
	private Long ticketTypeId;// 票类型Id
	private Long cinemaId;// 影院Id
	private boolean delete;
	private Long orderInCinema;

	public TTicketTypeCinema() {
	}

	public TTicketTypeCinema(TTicketType tTicketType, String regionCode,
			Long cinemaId) {
		this.tTicketType = tTicketType;
		this.regionCode = regionCode;
		this.ticketTypeId = tTicketType.getId();
		this.cinemaId = cinemaId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_TICKET_TYPE_CINEMA", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "TICKET_TYPE_CINEMA_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	@Column(name = "REGION_CODE", nullable = false, length = 20)
	public String getRegionCode() {
		return this.regionCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TCardType gettCardType() {
		return tCardType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA", nullable = false, insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	@Column(name = "TICKET_TYPE_ID", nullable = false)
	public Long getTicketTypeId() {
		return ticketTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TTicketType gettTicketType() {
		return this.tTicketType;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public void settCardType(TCardType tCardType) {
		this.tCardType = tCardType;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	public void setTicketTypeId(Long ticketTypeId) {
		this.ticketTypeId = ticketTypeId;
	}

	public void settTicketType(TTicketType tTicketType) {
		this.tTicketType = tTicketType;
	}

	@Column(name = "CINEMA", nullable = false)
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Transient
	public boolean getDelete() {
		return delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return tVoucherType;
	}

	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}
	
	@Column(name = "ORDER_IN_CINEMA")
	public Long getOrderInCinema() {
		return orderInCinema;
	}

	public void setOrderInCinema(Long orderInCinema) {
		this.orderInCinema = orderInCinema;
	}

}
