package com.wanda.ccs.model;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TTicketTypePaymentCard generated by hbm2java
 */
@Entity
@Table(name = "T_TICKET_TYPE_PAYMENT_CARD")
public class TTicketTypePaymentCard extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 8690913195566721597L;
	
	private Long id;
	private String regionCode;
	private Long cardTypeId;
	private Long ticketTypeId;
	private TTicketType tTicketType;
	private TCardType tCardType;
	
	public TTicketTypePaymentCard(){
		
	}
	
	public TTicketTypePaymentCard(TTicketType tTicketType, Long cardTypeId) {
		this.tTicketType = tTicketType;
		this.ticketTypeId = tTicketType.getId();
		this.cardTypeId = cardTypeId;
	}
	
	public TTicketTypePaymentCard(TReqTicketTypePaymentCard req, TTicketType tTicketType, String regionCode){
		setCardTypeId(req.getCardTypeId());
		setTicketTypeId(tTicketType.getId());
		setRegionCode(regionCode);
		this.tTicketType = tTicketType;
	}
	
	@SequenceGenerator(name = "generator", sequenceName = "S_T_TICKET_TYPE_PAYMENT_CARD", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "TICKET_TYPE_PAYMENT_CARD_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "REGION_CODE", length = 20)
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}
	
	@Column(name = "CARD_TYPE_ID", nullable = false)
	public Long getCardTypeId() {
		return cardTypeId;
	}

	public void setCardTypeId(Long cardTypeId) {
		this.cardTypeId = cardTypeId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TCardType gettCardType() {
		return tCardType;
	}

	public void settCardType(TCardType tCardType) {
		this.tCardType = tCardType;
	}

	@Column(name = "TICKET_TYPE_ID", nullable = false)
	public Long getTicketTypeId() {
		return ticketTypeId;
	}

	public void setTicketTypeId(Long ticketTypeId) {
		this.ticketTypeId = ticketTypeId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TTicketType gettTicketType() {
		return tTicketType;
	}

	public void settTicketType(TTicketType tTicketType) {
		this.tTicketType = tTicketType;
	}

}
