package com.wanda.ccs.model;

// Generated 2011-11-2 12:36:06 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TTicketTypeUseRule generated by hbm2java
 */
@Entity
@Table(name = "T_TICKET_TYPE_USE_RULE")
public class TTicketTypeUseRule extends VersionableEntity implements
		java.io.Serializable, IRegionCode {
	private static final long serialVersionUID = 644820495769396948L;
	
	private Long id;
	private TMarketingCampaign tMarketingCampaign;
	private TTicketType tTicketType;
	private Long ticketTypeId;
	private String regionCode;
	private String ruleCondition;
	private String ruleUse;
	private String description;
	private Long ruleOrder;
	private Boolean isDeleted;
	private Long marketingCampaignId;
	
	public TTicketTypeUseRule() {
	}

	public TTicketTypeUseRule(TTicketType tTicketType, Long ticketTypeId,
			String ruleUse, String description, Long ruleOrder,
			Boolean isDeleted) {
		this.tTicketType = tTicketType;
		this.ticketTypeId = ticketTypeId;
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
		this.isDeleted = isDeleted;
	}

	public TTicketTypeUseRule(TMarketingCampaign tMarketingCampaign,
			TTicketType tTicketType, String regionCode, String ruleCondition,
			String ruleUse, String description, Long ruleOrder,
			Boolean isDeleted) {
		this.tMarketingCampaign = tMarketingCampaign;
		this.tTicketType = tTicketType;
		this.ticketTypeId = tTicketType == null ? null : tTicketType.getId();
		this.regionCode = regionCode;
		this.ruleCondition = ruleCondition;
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
		this.isDeleted = isDeleted;
	}
	
	public TTicketTypeUseRule(TTicketType tTicketType, String regionCode, String ruleCondition,
			String ruleUse, String description, Long ruleOrder,
			Boolean isDeleted,Long marketingCampaignId) {
		this.tTicketType = tTicketType;
		this.ticketTypeId = tTicketType == null ? null : tTicketType.getId();
		this.regionCode = regionCode;
		this.ruleCondition = ruleCondition;
		this.ruleUse = ruleUse;
		this.description = description;
		this.ruleOrder = ruleOrder;
		this.isDeleted = isDeleted;
		this.marketingCampaignId = marketingCampaignId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_TICKET_TYPE_USE_RULE", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "TICKET_TYPE_USE_RULE_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MARKETING_CAMPAIGN_ID", insertable = false, updatable = false)
	public TMarketingCampaign gettMarketingCampaign() {
		return this.tMarketingCampaign;
	}

	public void settMarketingCampaign(TMarketingCampaign tMarketingCampaign) {
		this.tMarketingCampaign = tMarketingCampaign;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TTicketType gettTicketType() {
		return this.tTicketType;
	}

	public void settTicketType(TTicketType tTicketType) {
		this.tTicketType = tTicketType;
	}

	@Column(name = "REGION_CODE", length = 20)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "RULE_CONDITION")
	public String getRuleCondition() {
		return this.ruleCondition;
	}

	public void setRuleCondition(String ruleCondition) {
		this.ruleCondition = ruleCondition;
	}

	@Column(name = "RULE_USE", nullable = false, length = 4000)
	public String getRuleUse() {
		return this.ruleUse;
	}

	public void setRuleUse(String ruleUse) {
		this.ruleUse = ruleUse;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RULE_ORDER", nullable = false, precision = 38, scale = 0)
	public Long getRuleOrder() {
		return this.ruleOrder;
	}

	public void setRuleOrder(Long ruleOrder) {
		this.ruleOrder = ruleOrder;
	}

	@Column(name = "IS_DELETED", nullable = false, length = 1)
	public String getIsDeleted() {
		return this.isDeleted ? "Y" : "N";
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted.equals("Y");
	}

	@Column(name = "TICKET_TYPE_ID", nullable = false)
	public Long getTicketTypeId() {
		return ticketTypeId;
	}

	public void setTicketTypeId(Long ticketTypeId) {
		this.ticketTypeId = ticketTypeId;
	}
	
	@Column(name = "MARKETING_CAMPAIGN_ID")
	public Long getMarketingCampaignId() {
		return marketingCampaignId;
	}

	public void setMarketingCampaignId(Long marketingCampaignId) {
		this.marketingCampaignId = marketingCampaignId;
	}
}
