package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TVoucherUseLog generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_USE_LOG")
public class TVoucherUseLog extends VersionableEntity implements
		java.io.Serializable {
	
	private static final long serialVersionUID = -1190829622525410844L;
	
	private Long id;  //回兑ID
	private TCinema tCinema;  // 回兑影院
	private Date useDate;    //回兑日期
	private String orderId;  //购票订单号
	private String operatorId;    //回兑用户ID
	private String operatorName;    //回兑用户姓名
	
	private Set<TVoucherFilmLog> tVoucherFilmLogs = new HashSet<TVoucherFilmLog>(0);
	private Set<TVoucherGoodsLog> tVoucherGoodsLog = new HashSet<TVoucherGoodsLog>(0);

	private Set<TVoucher> tVouchers = new HashSet<TVoucher>(0);

	public TVoucherUseLog() {
	}

	public TVoucherUseLog(TCinema tCinema, Date useDate, String orderId) {
		this.tCinema = tCinema;
		this.useDate = useDate;
		this.orderId = orderId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_USE_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_USE_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USE_CINEMA", nullable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "USE_DATE", nullable = false, length = 7)
	public Date getUseDate() {
		return this.useDate;
	}

	public void setUseDate(Date useDate) {
		this.useDate = useDate;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherUseLog")
	public Set<TVoucher> gettVouchers() {
		return this.tVouchers;
	}

	public void settVouchers(Set<TVoucher> tVouchers) {
		this.tVouchers = tVouchers;
	}
	
	@Column(name = "OPERATOR_ID", length = 50)
	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "OPERATOR_NAME", length = 100)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherUseLog")
	public Set<TVoucherFilmLog> gettVoucherFilmLogs() {
		return tVoucherFilmLogs;
	}
	
	public void settVoucherFilmLogs(Set<TVoucherFilmLog> tVoucherFilmLogs) {
		this.tVoucherFilmLogs = tVoucherFilmLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherUseLog")
	public Set<TVoucherGoodsLog> gettVoucherGoodsLog() {
		return tVoucherGoodsLog;
	}

	public void settVoucherGoodsLog(Set<TVoucherGoodsLog> tVoucherGoodsLog) {
		this.tVoucherGoodsLog = tVoucherGoodsLog;
	}
	

}
