package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TVoucherOrderSettLog generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_ORDER_SETT_LOG")
public class TVoucherOrderSettLog extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = -4646196411951458129L;
	
	private Long id;
	private TVoucherOrder tVoucherOrder;
	private String userId;
	private String userName;
	private Float amount;
	private Date settlementDate;
	private String remarks;
	private Long voucherOrderId;
	private String finalFlag;
	private String payType;
	private String invoiced;
	private String orderSetNum;//结算号
	private Long receiptNum;//发票号
	
	public TVoucherOrderSettLog() {
	}

	public TVoucherOrderSettLog(TVoucherOrder tVoucherOrder, Float amount,
			Date settlementDate) {
		this.tVoucherOrder = tVoucherOrder;
		this.amount = amount;
		this.settlementDate = settlementDate;
	}

	public TVoucherOrderSettLog(TVoucherOrder tVoucherOrder, String userId,
			String userName, Float amount, Date settlementDate, String remarks, String finalFlag) {
		this.tVoucherOrder = tVoucherOrder;
		this.userId = userId;
		this.userName = userName;
		this.amount = amount;
		this.settlementDate = settlementDate;
		this.remarks = remarks;
		this.finalFlag = finalFlag;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_ORDER_SETT_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_ORDER_SETT_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_ORDER_ID", insertable = false, updatable = false)
	public TVoucherOrder gettVoucherOrder() {
		return this.tVoucherOrder;
	}

	public void settVoucherOrder(TVoucherOrder tVoucherOrder) {
		this.tVoucherOrder = tVoucherOrder;
	}
	
	@Column(name = "VOUCHER_ORDER_ID")
	public Long getVoucherOrderId() {
		return voucherOrderId;
	}

	public void setVoucherOrderId(Long voucherOrderId) {
		this.voucherOrderId = voucherOrderId;
	}
	
	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", length = 40)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 10,scale=2)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Column(name = "SETTLEMENT_DATE", nullable = false, length = 7)
	public Date getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Date settlementDate) {
		this.settlementDate = settlementDate;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	@Column(name = "FINAL_FLAG", nullable = false, length = 1)
	public String getFinalFlag() {
		return finalFlag;
	}

	public void setFinalFlag(String finalFlag) {
		this.finalFlag = finalFlag;
	}

	@Column(name = "PAY_TYPE", length = 1)
	public String getPayType() {
		return payType;
	}

	@Column(name = "INVOICED", length = 1)
	public String getInvoiced() {
		return invoiced;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public void setInvoiced(String invoiced) {
		this.invoiced = invoiced;
	}
	
	@Column(name = "ORDER_SET_NUM")
	public String getOrderSetNum() {
		return orderSetNum;
	}

	public void setOrderSetNum(String orderSetNum) {
		this.orderSetNum = orderSetNum;
	}
	
	@Column(name = "RECEIPT_NUM")
	public Long getReceiptNum() {
		return receiptNum;
	}

	public void setReceiptNum(Long receiptNum) {
		this.receiptNum = receiptNum;
	}
}
