package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TVoucher generated by hbm2java
 * 券信息
 */
@Entity
@Table(name = "T_VOUCHER", uniqueConstraints = @UniqueConstraint(columnNames = "BAR_CODE"))
public class TVoucher extends VersionableEntity implements java.io.Serializable {

	private Long id;  //券序列号
	private TVoucherType tVoucherType; //券类序列号
	private TVoucherUseLog tVoucherUseLog; //券回兑记录编号
	private TVoucherOrder tVoucherOrder; //券所在的销售单
	private Integer sequenceInOrder; //券在订单中的序列号
	private String voucherStatus; //券状态 P等待打印或导出 、R打印失败、  W等待启用、 A启用、  F冻结、X作废、U已回兑
	private Long voucherOrderId;  //券销售单编号
	private Date expiryDate; //券的到期日期
	private String barCode; //券上的条码
	private String voucherNumber; //券号码 ，包含年、月、日、区域编码、影城编码等信息
	private String lockCode; //券使用过程中券被锁定时的锁定码
	private String printCode; //券的打印编码
	private Date useTime;    //券的回兑时间

	private Long voucherTypeId; 
	private Long voucherUseLogId;

	public TVoucher() {
	}

	public TVoucher(TVoucherType tVoucherType, String voucherStatus,
			Long voucherOrderId) {
		this.tVoucherType = tVoucherType;
		this.voucherStatus = voucherStatus;
		this.voucherOrderId = voucherOrderId;
	}

	public TVoucher(TVoucherType tVoucherType, TVoucherUseLog tVoucherUseLog,
			Integer sequenceInOrder, String voucherStatus,
			Long voucherOrderId, Date expiryDate, String barCode,
			String voucherNumber, String lockCode) {
		this.tVoucherType = tVoucherType;
		this.tVoucherUseLog = tVoucherUseLog;
		this.sequenceInOrder = sequenceInOrder;
		this.voucherStatus = voucherStatus;
		this.voucherOrderId = voucherOrderId;
		this.expiryDate = expiryDate;
		this.barCode = barCode;
		this.voucherNumber = voucherNumber;
		this.lockCode = lockCode;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return this.tVoucherType;
	}

	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_USE_LOG_ID", insertable = false, updatable = false)
	public TVoucherUseLog gettVoucherUseLog() {
		return this.tVoucherUseLog;
	}

	public void settVoucherUseLog(TVoucherUseLog tVoucherUseLog) {
		this.tVoucherUseLog = tVoucherUseLog;
	}

	@Column(name = "VOUCHER_USE_LOG_ID")
	public Long getVoucherUseLogId() {
		return voucherUseLogId;
	}

	public void setVoucherUseLogId(Long voucherUseLogId) {
		this.voucherUseLogId = voucherUseLogId;
	}
	
	@Column(name = "SEQUENCE_IN_ORDER", precision = 22, scale = 0)
	public Integer getSequenceInOrder() {
		return this.sequenceInOrder;
	}

	public void setSequenceInOrder(Integer sequenceInOrder) {
		this.sequenceInOrder = sequenceInOrder;
	}

	@Column(name = "VOUCHER_STATUS", nullable = false, length = 1)
	public String getVoucherStatus() {
		return this.voucherStatus;
	}

	public void setVoucherStatus(String voucherStatus) {
		this.voucherStatus = voucherStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_ORDER_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherOrder gettVoucherOrder() {
		return tVoucherOrder;
	}

	public void settVoucherOrder(TVoucherOrder tVoucherOrder) {
		this.tVoucherOrder = tVoucherOrder;
	}

	@Column(name = "VOUCHER_ORDER_ID")
	public Long getVoucherOrderId() {
		return this.voucherOrderId;
	}

	public void setVoucherOrderId(Long voucherOrderId) {
		this.voucherOrderId = voucherOrderId;
	}

	@Column(name = "EXPIRY_DATE", length = 7)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "BAR_CODE", unique = true, length = 30)
	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	@Column(name = "VOUCHER_NUMBER", length = 30)
	public String getVoucherNumber() {
		return this.voucherNumber;
	}

	public void setVoucherNumber(String voucherNumber) {
		this.voucherNumber = voucherNumber;
	}

	@Column(name = "LOCK_CODE", length = 30)
	public String getLockCode() {
		return this.lockCode;
	}

	public void setLockCode(String lockCode) {
		this.lockCode = lockCode;
	}
	
	@Column(name = "VOUCHER_TYPE_ID")
	public Long getVoucherTypeId() {
		return voucherTypeId;
	}

	public void setVoucherTypeId(Long voucherTypeId) {
		this.voucherTypeId = voucherTypeId;
	}
	
	@Column(name = "PRINT_CODE")
	public String getPrintCode() {
		return printCode;
	}

	public void setPrintCode(String printCode) {
		this.printCode = printCode;
	}
	
	@Column(name = "USE_TIME")
	public Date getUseTime() {
		return useTime;
	}

	public void setUseTime(Date useTime) {
		this.useTime = useTime;
	}
}
