package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TVoucherCustomer generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_CUSTOMER")
public class TVoucherCustomer extends VersionableEntity implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7370438675745032046L;
	private Long id;
	private TVoucherCustomerGroup tVoucherCustomerGroup;
	private TCinema tCinema; //客户所属影城
	private String ownerRegion;//客户所属区域
	private String customerLevel;//客户归属级别
	private String customerName;//客户姓名
	private String address;//客户地址
	private String postalCode;//客户邮编
	private String contactPerson;//联系人姓名
	private String contactEmail;//联系人邮箱
	private String contactPhone;//联系人电话
	private String contactCellphone;//联系人手机号
	private String bankName;//开户行名称
	private String bankAccount;//开户行账号
	private String remarks;//备注
	private String bankAddress;//开户行地址
	private String ownerUserId;//负责该客户的销售的登录id
	private String ownerUserName;//负责改客户的销售的姓名
	private Set<TVoucherOrder> tVoucherOrders = new HashSet<TVoucherOrder>(0);
	private Long cinemaId;
	private Long voucherCustomerGroupId;
	private String publicKey;//公钥
	private Long isDelete = 0L;//标识是否删除
	
	public TVoucherCustomer() {
	}

	public TVoucherCustomer(String customerLevel, String customerName,
			String ownerUserId, String ownerUserName) {
		this.customerLevel = customerLevel;
		this.customerName = customerName;
		this.ownerUserId = ownerUserId;
		this.ownerUserName = ownerUserName;
	}

	public TVoucherCustomer(TVoucherCustomerGroup tVoucherCustomerGroup,
			TCinema tCinema, String ownerRegion, String customerLevel,
			String customerName, String address, String postalCode,
			String contactPerson, String contactEmail, String contactPhone,
			String contactCellphone, String bankName, String bankAccount,
			String remarks, String bankAddress, String ownerUserId,
			String ownerUserName, Set<TVoucherOrder> tVoucherOrders,
			Long cinemaId,Long voucherCustomerGroupId,String publicKey,
			Long isDelete
			) {
		this.tVoucherCustomerGroup = tVoucherCustomerGroup;
		this.tCinema = tCinema;
		this.ownerRegion = ownerRegion;
		this.customerLevel = customerLevel;
		this.customerName = customerName;
		this.address = address;
		this.postalCode = postalCode;
		this.contactPerson = contactPerson;
		this.contactEmail = contactEmail;
		this.contactPhone = contactPhone;
		this.contactCellphone = contactCellphone;
		this.bankName = bankName;
		this.bankAccount = bankAccount;
		this.remarks = remarks;
		this.bankAddress = bankAddress;
		this.ownerUserId = ownerUserId;
		this.ownerUserName = ownerUserName;
		this.tVoucherOrders = tVoucherOrders;
		this.cinemaId = cinemaId;
		this.voucherCustomerGroupId = voucherCustomerGroupId;
		this.publicKey = publicKey;
		this.isDelete = isDelete;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_CUSTOMER")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_CUSTOMER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_CUSTOMER_GROUP_ID", insertable=false, updatable=false)
	public TVoucherCustomerGroup gettVoucherCustomerGroup() {
		return this.tVoucherCustomerGroup;
	}

	public void settVoucherCustomerGroup(
			TVoucherCustomerGroup tVoucherCustomerGroup) {
		this.tVoucherCustomerGroup = tVoucherCustomerGroup;
	}
	
	@Column(name = "VOUCHER_CUSTOMER_GROUP_ID")
	public Long getVoucherCustomerGroupId() {
		return voucherCustomerGroupId;
	}

	public void setVoucherCustomerGroupId(Long voucherCustomerGroupId) {
		this.voucherCustomerGroupId = voucherCustomerGroupId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_CINEMA", insertable=false, updatable=false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}
	
	@Column(name="OWNER_CINEMA")
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "OWER_REGION", length = 20)
	public String getOwnerRegion() {
		return this.ownerRegion;
	}

	public void setOwnerRegion(String ownerRegion) {
		this.ownerRegion = ownerRegion;
	}

	@Column(name = "CUSTOMER_LEVEL", nullable = false, length = 1)
	public String getCustomerLevel() {
		return this.customerLevel;
	}

	public void setCustomerLevel(String customerLevel) {
		this.customerLevel = customerLevel;
	}

	@Column(name = "CUSTOMER_NAME", nullable = false, length = 500)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "POSTAL_CODE", length = 20)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "CONTACT_PERSON", length = 50)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "CONTACT_EMAIL", length = 100)
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Column(name = "CONTACT_PHONE", length = 30)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "CONTACT_CELLPHONE", length = 30)
	public String getContactCellphone() {
		return this.contactCellphone;
	}

	public void setContactCellphone(String contactCellphone) {
		this.contactCellphone = contactCellphone;
	}

	@Column(name = "BANK_NAME", length = 200)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "BANK_ACCOUNT", length = 100)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "BANK_ADDRESS", length = 500)
	public String getBankAddress() {
		return this.bankAddress;
	}

	public void setBankAddress(String bankAddress) {
		this.bankAddress = bankAddress;
	}

	@Column(name = "OWNER_USER_ID", nullable = false, length = 20)
	public String getOwnerUserId() {
		return this.ownerUserId;
	}

	public void setOwnerUserId(String ownerUserId) {
		this.ownerUserId = ownerUserId;
	}

	@Column(name = "OWNER_USER_NAME", nullable = false, length = 40)
	public String getOwnerUserName() {
		return this.ownerUserName;
	}

	public void setOwnerUserName(String ownerUserName) {
		this.ownerUserName = ownerUserName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherCustomer")
	public Set<TVoucherOrder> gettVoucherOrders() {
		return this.tVoucherOrders;
	}

	public void settVoucherOrders(Set<TVoucherOrder> tVoucherOrders) {
		this.tVoucherOrders = tVoucherOrders;
	}
	@Column(name = "PUBLIC_KEY", length = 2000)
	public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}
	@Column(name = "IS_DELETE", length = 1)
	public Long getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Long isDelete) {
		this.isDelete = isDelete;
	}

}
