package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.SEQUENCE;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TVoucherOrder generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_ORDER", uniqueConstraints = @UniqueConstraint(columnNames = {
		"VOUCHER_ORDER_ID", "VOUCHER_TYPE_ID" }))
public class TVoucherOrder extends VersionableEntity implements
		java.io.Serializable {
	private static final long serialVersionUID = 8555950722951594896L;
	
	private Long id;
	private TVoucherType tVoucherType; // 券类型id
	private TVoucherCustomer tVoucherCustomer; // 客户id
	private TCinema tCinema; // 销售所在影城
	private Long numTotal; // 券的总数
	private String ownerRegion;// 销售所在的区域
	private String description; // 销售单备注
	private Float unitValue; // 每券价值
	private Float totalValue;// 销售单总额
	private Date saleDate; // 销售日期
	private Date expiryDate; // 到期日期
	private String salesId; // 销售用户登录id
	private String salesName; // 销售用户登录姓名
	private String regionApproverId; // 区域审核用户id
	private String regionApproverName;// 区域审核用户姓名
	private String groupApproverId; // 院线审核用户id
	private String groupApproverName;// 院线审核用户姓名
	private String appStatus;// 销售单审核状态 A待区域审核、P审核通过、E审核不通过，发回返修、F审核不通过，终止审核、X取消审核、G待院线审核
	private String isVirtual;// Y表示电子券 N表示实物券
	private Long numPrinted = 0L;// 已打印券数
	private Long numGenerated = 0L;// 已生码券数
	private Long numPrintFailed = 0L; // 打印失败的张数
	private String orderLevel;// 订单级别 G院线级 R区域级 C影城级
	private String orderStatus = "A";// 销售单状态：A正在审核 E启用 D禁用
	private Long numUsed = 0L;// 已回兑张数
	private String settlementType = "P";// 结算方式 P预付款、A后结算
	private Float settledValue = 0.0f;// 已结算金额
	private String settlementComplete = "N";// 是否结算完毕 Y结算完毕、N未结算完毕
	private String orderNum;// 系统自动生成的、供客户查看的订单编号，包括年、月、日、区域、影城、销售员等信息
	private Date regionApproveDate;// 区域审核时间
	private Date groupApproveDate;// 院线审核时间
	private String oaId;
	private String settleMold;//结算类型   T团体票、W微博、D代收代付、C测试赠票、F非内部结算
	private String printRemarks; //为财务对账方便而加的销售单的打印标识
	private String orderSort;//券分类     S代表销售类、R代表招待类
	private String setDetail;//套餐描述

	private Set<TVoucherOrderReviseLog> tVoucherOrderReviseLogs = new HashSet<TVoucherOrderReviseLog>(
			0);
	private Set<TVoucherOrderSettLog> tVoucherOrderSettLogs = new HashSet<TVoucherOrderSettLog>(
			0);
	private Set<TVoucherReviseLog> tVoucherReviseLogs = new HashSet<TVoucherReviseLog>(
			0);
	private Long cinemaId;
	private Long voucherTypeId;
	private Long voucherCustomerId;

	public TVoucherOrder() {
	}

	public TVoucherOrder(TVoucherType tVoucherType,
			TVoucherCustomer tVoucherCustomer, Long numTotal,
			Float unitValue, Float totalValue, Date saleDate, String salesId,
			String salesName, String appStatus, String isVirtual,
			Long numPrinted, Long numGenerated, String orderLevel,
			String orderStatus, Long numUsed, String settlementType, String printRemarks,
			Float settledValue, String settlementComplete, Date groupApproveDate) {
		this.tVoucherType = tVoucherType;
		this.tVoucherCustomer = tVoucherCustomer;
		this.numTotal = numTotal;
		this.unitValue = unitValue;
		this.totalValue = totalValue;
		this.saleDate = saleDate;
		this.salesId = salesId;
		this.salesName = salesName;
		this.appStatus = appStatus;
		this.isVirtual = isVirtual;
		this.numPrinted = numPrinted;
		this.numGenerated = numGenerated;
		this.orderLevel = orderLevel;
		this.orderStatus = orderStatus;
		this.numUsed = numUsed;
		this.settlementType = settlementType;
		this.printRemarks = printRemarks;
		this.settledValue = settledValue;
		this.settlementComplete = settlementComplete;
		this.groupApproveDate = groupApproveDate;
	}

	public TVoucherOrder(TVoucherType tVoucherType,
			TVoucherCustomer tVoucherCustomer, TCinema tCinema, Long numTotal,
			String ownerRegion, String description, Float unitValue,
			Float totalValue, Date saleDate, Date expiryDate, String salesId,
			String salesName, String regionApproverId,
			String regionApproverName, String groupApproverId,
			String groupApproverName, String appStatus, String isVirtual,
			Long numPrinted, Long numGenerated, String orderLevel,
			String orderStatus, Long numUsed, String settlementType, String printRemarks,
			Float settledValue, String settlementComplete, String orderNum,
			Date regionApproveDate, Date groupApproveDate,
			Set<TVoucherOrderReviseLog> tVoucherOrderReviseLogs,
			Set<TVoucherOrderSettLog> tVoucherOrderSettLogs,
			Set<TVoucherReviseLog> tVoucherReviseLogs) {
		this.tVoucherType = tVoucherType;
		this.tVoucherCustomer = tVoucherCustomer;
		this.tCinema = tCinema;
		this.numTotal = numTotal;
		this.ownerRegion = ownerRegion;
		this.description = description;
		this.unitValue = unitValue;
		this.totalValue = totalValue;
		this.saleDate = saleDate;
		this.expiryDate = expiryDate;
		this.salesId = salesId;
		this.salesName = salesName;
		this.regionApproverId = regionApproverId;
		this.regionApproverName = regionApproverName;
		this.groupApproverId = groupApproverId;
		this.groupApproverName = groupApproverName;
		this.appStatus = appStatus;
		this.isVirtual = isVirtual;
		this.numPrinted = numPrinted;
		this.numGenerated = numGenerated;
		this.orderLevel = orderLevel;
		this.orderStatus = orderStatus;
		this.numUsed = numUsed;
		this.settlementType = settlementType;
		this.printRemarks = printRemarks;
		this.settledValue = settledValue;
		this.settlementComplete = settlementComplete;
		this.orderNum = orderNum;
		this.regionApproveDate = regionApproveDate;
		this.groupApproveDate = groupApproveDate;
		this.tVoucherOrderReviseLogs = tVoucherOrderReviseLogs;
		this.tVoucherOrderSettLogs = tVoucherOrderSettLogs;
		this.tVoucherReviseLogs = tVoucherReviseLogs;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_REQUEST")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_ORDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return this.tVoucherType;
	}

	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}

	@Column(name = "VOUCHER_TYPE_ID")
	public Long getVoucherTypeId() {
		return voucherTypeId;
	}

	public void setVoucherTypeId(Long voucherTypeId) {
		this.voucherTypeId = voucherTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_CUSTOMER_ID", insertable = false, updatable = false)
	public TVoucherCustomer gettVoucherCustomer() {
		return this.tVoucherCustomer;
	}

	public void settVoucherCustomer(TVoucherCustomer tVoucherCustomer) {
		this.tVoucherCustomer = tVoucherCustomer;
	}

	@Column(name = "VOUCHER_CUSTOMER_ID")
	public Long getVoucherCustomerId() {
		return voucherCustomerId;
	}

	public void setVoucherCustomerId(Long voucherCustomerId) {
		this.voucherCustomerId = voucherCustomerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_CINEMA", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "OWNER_CINEMA")
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "NUM_TOTAL", nullable = false, precision = 22, scale = 0)
	public Long getNumTotal() {
		return this.numTotal;
	}

	public void setNumTotal(Long numTotal) {
		this.numTotal = numTotal;
	}

	@Column(name = "OWNER_REGION", length = 20)
	public String getOwnerRegion() {
		return this.ownerRegion;
	}

	public void setOwnerRegion(String ownerRegion) {
		this.ownerRegion = ownerRegion;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "UNIT_VALUE", nullable = false, precision = 5,scale=2)
	public Float getUnitValue() {
		return this.unitValue;
	}

	public void setUnitValue(Float unitValue) {
		this.unitValue = unitValue;
	}

	@Column(name = "TOTAL_VALUE", nullable = false, precision = 10,scale=2)
	public Float getTotalValue() {
		return this.totalValue;
	}

	public void setTotalValue(Float totalValue) {
		this.totalValue = totalValue;
	}

	@Column(name = "SALE_DATE", nullable = false, length = 7)
	public Date getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	@Column(name = "EXPIRY_DATE", length = 7)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		SimpleDateFormat fomat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		try {
			this.expiryDate = fomat.parse(new SimpleDateFormat("yyyy-MM-dd").format(expiryDate) + " 23:59:59");
		} catch (ParseException e) {
			e.printStackTrace();
		}
	}

	@Column(name = "SALES_ID", nullable = false, length = 20)
	public String getSalesId() {
		return this.salesId;
	}

	public void setSalesId(String salesId) {
		this.salesId = salesId;
	}

	@Column(name = "SALES_NAME", nullable = false, length = 40)
	public String getSalesName() {
		return this.salesName;
	}

	public void setSalesName(String salesName) {
		this.salesName = salesName;
	}

	@Column(name = "REGION_APPROVER_ID", length = 20)
	public String getRegionApproverId() {
		return this.regionApproverId;
	}

	public void setRegionApproverId(String regionApproverId) {
		this.regionApproverId = regionApproverId;
	}

	@Column(name = "REGION_APPROVER_NAME", length = 40)
	public String getRegionApproverName() {
		return this.regionApproverName;
	}

	public void setRegionApproverName(String regionApproverName) {
		this.regionApproverName = regionApproverName;
	}

	@Column(name = "GROUP_APPROVER_ID", length = 20)
	public String getGroupApproverId() {
		return this.groupApproverId;
	}

	public void setGroupApproverId(String groupApproverId) {
		this.groupApproverId = groupApproverId;
	}

	@Column(name = "GROUP_APPROVER_NAME", length = 40)
	public String getGroupApproverName() {
		return this.groupApproverName;
	}

	public void setGroupApproverName(String groupApproverName) {
		this.groupApproverName = groupApproverName;
	}

	@Column(name = "APP_STATUS", nullable = false, length = 1)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "IS_VIRTUAL", nullable = false, length = 1)
	public String getIsVirtual() {
		return this.isVirtual;
	}

	public void setIsVirtual(String isVirtual) {
		this.isVirtual = isVirtual;
	}

	@Transient
	public boolean getVirtual() {
		return "Y".equals(isVirtual);
	}

	public void setVirtual(boolean isVirtual) {
		this.isVirtual = isVirtual ? "Y" : "N";
	}

	@Column(name = "NUM_PRINTED", nullable = false, precision = 22, scale = 0)
	public Long getNumPrinted() {
		return this.numPrinted;
	}

	public void setNumPrinted(Long numPrinted) {
		this.numPrinted = numPrinted;
	}

	@Column(name = "NUM_GENERATED", nullable = false, precision = 22, scale = 0)
	public Long getNumGenerated() {
		return this.numGenerated;
	}

	public void setNumGenerated(Long numGenerated) {
		this.numGenerated = numGenerated;
	}

	@Column(name = "ORDER_LEVEL", nullable = false, length = 1)
	public String getOrderLevel() {
		return this.orderLevel;
	}

	public void setOrderLevel(String orderLevel) {
		this.orderLevel = orderLevel;
	}

	@Column(name = "ORDER_STATUS", nullable = false, length = 1)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "NUM_USED", nullable = false, precision = 22, scale = 0)
	public Long getNumUsed() {
		return this.numUsed;
	}

	public void setNumUsed(Long numUsed) {
		this.numUsed = numUsed;
	}

	@Column(name = "SETTLEMENT_TYPE", nullable = false, length = 1)
	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	@Column(name = "SETTLED_VALUE", nullable = false, precision = 10,scale=2)
	public Float getSettledValue() {
		return this.settledValue;
	}

	public void setSettledValue(Float settledValue) {
		this.settledValue = settledValue;
	}

	@Column(name = "SETTLEMENT_COMPLETE", nullable = false, length = 1)
	public String getSettlementComplete() {
		return this.settlementComplete;
	}

	public void setSettlementComplete(String settlementComplete) {
		this.settlementComplete = settlementComplete;
	}

	@Column(name = "ORDER_NUM", length = 20)
	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	@Column(name = "REGION_APPROVE_DATE", length = 7)
	public Date getRegionApproveDate() {
		return this.regionApproveDate;
	}

	public void setRegionApproveDate(Date regionApproveDate) {
		this.regionApproveDate = regionApproveDate;
	}

	@Column(name = "GROUP_APPROVE_DATE", nullable = false, length = 7)
	public Date getGroupApproveDate() {
		return this.groupApproveDate;
	}

	public void setGroupApproveDate(Date groupApproveDate) {
		this.groupApproveDate = groupApproveDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherOrder")
	public Set<TVoucherOrderReviseLog> gettVoucherOrderReviseLogs() {
		return this.tVoucherOrderReviseLogs;
	}

	public void settVoucherOrderReviseLogs(
			Set<TVoucherOrderReviseLog> tVoucherOrderReviseLogs) {
		this.tVoucherOrderReviseLogs = tVoucherOrderReviseLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherOrder")
	public Set<TVoucherOrderSettLog> gettVoucherOrderSettLogs() {
		return this.tVoucherOrderSettLogs;
	}

	public void settVoucherOrderSettLogs(
			Set<TVoucherOrderSettLog> tVoucherOrderSettLogs) {
		this.tVoucherOrderSettLogs = tVoucherOrderSettLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherOrder")
	public Set<TVoucherReviseLog> gettVoucherReviseLogs() {
		return this.tVoucherReviseLogs;
	}

	public void settVoucherReviseLogs(Set<TVoucherReviseLog> tVoucherReviseLogs) {
		this.tVoucherReviseLogs = tVoucherReviseLogs;
	}

	@Column(name = "NUM_PRINT_FAILED", nullable = false, precision = 22, scale = 0)
	public Long getNumPrintFailed() {
		return numPrintFailed;
	}

	public void setNumPrintFailed(Long numPrintFailed) {
		this.numPrintFailed = numPrintFailed;
	}
	
	@Column(name = "OA_ID", length = 100)
	public String getOaId() {
		return oaId;
	}

	public void setOaId(String oaId) {
		this.oaId = oaId;
	}
	
	@Column(name = "PRINT_REMARKS", length = 50)
	public String getPrintRemarks() {
		return printRemarks;
	}

	public void setPrintRemarks(String printRemarks) {
		this.printRemarks = printRemarks;
	}
	@Column(name = "SETTLE_MOLD")
	public String getSettleMold() {
		return settleMold;
	}

	public void setSettleMold(String settleMold) {
		this.settleMold = settleMold;
	}
	@Column(name = "ORDER_SORT")
	public String getOrderSort() {
		return orderSort;
	}

	public void setOrderSort(String orderSort) {
		this.orderSort = orderSort;
	}
	
	@Column(name = "SET_DETAIL")
	public String getSetDetail() {
		return setDetail;
	}

	public void setSetDetail(String setDetail) {
		this.setDetail = setDetail;
	}
	
}
