package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TVoucherCustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_CUSTOMER_GROUP")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class TVoucherCustomerGroup extends VersionableEntity implements
		java.io.Serializable {

	private Long id;
	private String groupName;
	private Set<TVoucherCustomer> tVoucherCustomers = new HashSet<TVoucherCustomer>(
			0);

	public TVoucherCustomerGroup() {
	}

	public TVoucherCustomerGroup(String groupName) {
		this.groupName = groupName;
	}

	public TVoucherCustomerGroup(String groupName,
			Set<TVoucherCustomer> tVoucherCustomers) {
		this.groupName = groupName;
		this.tVoucherCustomers = tVoucherCustomers;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_CUSTOMER_GROUP")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_CUSTOMER_GROUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "GROUP_NAME", nullable = false, length = 500)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tVoucherCustomerGroup")
	public Set<TVoucherCustomer> gettVoucherCustomers() {
		return this.tVoucherCustomers;
	}

	public void settVoucherCustomers(Set<TVoucherCustomer> tVoucherCustomers) {
		this.tVoucherCustomers = tVoucherCustomers;
	}

}
