package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TVoucherTypeDef generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_TYPE_DEF")
public class TVoucherTypeDef extends VersionableEntity implements
		java.io.Serializable, IRegionCode {
	private static final long serialVersionUID = 1135897263216708058L;
	
	private Long id;
	private TVoucherType tVoucherType; //券类id
	private Long voucherTypeId;
	private Integer showValue = 0; //票面价值  只有代金券使用该字段
	private Integer realValue = 0; //实际价值  兑换券和代金券使用该字段
	private Integer discount; //折扣比例 只有折扣券使用该字段
	private String regionCode; //区域代码  对于院线用户来说  为null
	private Boolean useDefault; //是否使用院线的缺省设置
	private Long seatLimit = 0l; //缺省每座可用张数，仅对代金券有效。 实际每座可用张数根据代金券的使用规则计算得出。 0表示不限
	private Long expiryMonth = 0l; //券按月计算的有效使用期
	private Long orderLimit = 0l; //缺省每场可用张数，仅对代金券有效。实际每场可用张数根据代金券的使用规则计算的书。0表示不限
	private String useOnGoods = "Y";//是否可用于卖品
	private Long minPrice = 0l;  //单张票价满多少元可使用
	
	public TVoucherTypeDef() {
		useDefault = true;
	}
	public void copy(TReqVoucherTypeDef req) {
		setShowValue(req.getShowValue());
		setRealValue(req.getRealValue());
		setDiscount(req.getDiscount());
		setUseDefault(req.getUseDefault());
		setSeatLimit(req.getSeatLimit());
		setExpiryMonth(req.getExpiryMonth());
		setOrderLimit(req.getOrderLimit());
		setUseOnGoods(req.getUseOnGoods());
		setMinPrice(req.getMinPrice());
	}
	public TVoucherTypeDef(TReqVoucherTypeDef req, TVoucherType voucherType) {
		this.setShowValue(req.getShowValue());
		this.setRealValue(req.getRealValue());
		this.setDiscount(req.getDiscount());
		this.setSeatLimit(req.getSeatLimit());
		this.setExpiryMonth(req.getExpiryMonth());
		this.setOrderLimit(req.getOrderLimit());
		this.setUseDefault(req.getUseDefault());
		this.setUseOnGoods(req.getUseOnGoods());
		this.setMinPrice(req.getMinPrice());
		if (voucherType != null) {
			this.settVoucherType(voucherType);
			this.setVoucherTypeId(voucherType.getId());
			this.setRegionCode(voucherType.getOwnerRegion());
		}
	}
	
	public TVoucherTypeDef(TVoucherType tVoucherType, boolean useDefault,
			Long seatLimit, Long expiryMonth, Long orderLimit, Long minPrice) {
		this.voucherTypeId = tVoucherType.getId();
		this.tVoucherType = tVoucherType;
		this.useDefault = useDefault;
		this.seatLimit = seatLimit;
		this.expiryMonth = expiryMonth;
		this.orderLimit = orderLimit;
		this.minPrice = minPrice;
	}

	public TVoucherTypeDef(TVoucherType tVoucherType, Integer showValue,
			Integer realValue, Integer discount, String regionCode,
			boolean useDefault, Long seatLimit, Long expiryMonth,
			Long orderLimit, Long minPrice) {
		this.tVoucherType = tVoucherType;
		this.showValue = showValue;
		this.realValue = realValue;
		this.discount = discount;
		this.regionCode = regionCode;
		this.useDefault = useDefault;
		this.seatLimit = seatLimit;
		this.expiryMonth = expiryMonth;
		this.orderLimit = orderLimit;
		this.minPrice = minPrice;
	}
	
	

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_TYPE_DEF")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_TYPE_DEF_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_TYPE_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherType gettVoucherType() {
		return this.tVoucherType;
	}

	public void settVoucherType(TVoucherType tVoucherType) {
		this.tVoucherType = tVoucherType;
	}
	
	@Column(name = "VOUCHER_TYPE_ID")
	public Long getVoucherTypeId() {
		return voucherTypeId;
	}

	public void setVoucherTypeId(Long voucherTypeId) {
		this.voucherTypeId = voucherTypeId;
	}
	
	@Column(name = "SHOW_VALUE", precision = 22, scale = 0)
	public Integer getShowValue() {
		return this.showValue;
	}

	public void setShowValue(Integer showValue) {
		this.showValue = showValue;
	}

	@Column(name = "REAL_VALUE", precision = 22, scale = 0)
	public Integer getRealValue() {
		return this.realValue;
	}

	public void setRealValue(Integer realValue) {
		this.realValue = realValue;
	}

	@Column(name = "DISCOUNT", precision = 5)
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Column(name = "REGION_CODE", length = 20)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "USE_DEFAULT", nullable = false, length = 1)
	public String getUseDefault() {
		return this.useDefault ? "Y" : "N";
	}

	public void setUseDefault(String str) {
		this.useDefault = str.equals("Y");
	}

	@Column(name = "SEAT_LIMIT", nullable = false, precision = 22, scale = 0)
	public Long getSeatLimit() {
		return this.seatLimit;
	}

	public void setSeatLimit(Long seatLimit) {
		this.seatLimit = seatLimit;
	}

	@Column(name = "EXPIRY_MONTH", nullable = false, precision = 22, scale = 0)
	public Long getExpiryMonth() {
		return this.expiryMonth;
	}

	public void setExpiryMonth(Long expiryMonth) {
		this.expiryMonth = expiryMonth;
	}

	@Column(name = "ORDER_LIMIT", nullable = false, precision = 22, scale = 0)
	public Long getOrderLimit() {
		return this.orderLimit;
	}

	public void setOrderLimit(Long orderLimit) {
		this.orderLimit = orderLimit;
	}
	
	@Column(name = "USE_ON_GOODS", nullable = false, length = 1)
	public String getUseOnGoods() {
		return useOnGoods;
	}

	public void setUseOnGoods(String useOnGoods) {
		this.useOnGoods = useOnGoods;
	}
	
	@Column(name = "MIN_PRICE", nullable = true, precision = 22, scale = 0)
	public Long getMinPrice() {
		return minPrice;
	}
	
	public void setMinPrice(Long minPrice) {
		this.minPrice = minPrice;
	}

}
