package com.wanda.ccs.model;

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xcesys.extras.core.dao.model.VersionableEntity;

//Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

/**
 * TVoucherOrderSettLog generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_ORDER_CODE_LOG")
public class TVoucherOrderCodeLog extends VersionableEntity implements
		java.io.Serializable{
	private Long id;
	private TVoucherOrder tVoucherOrder;
	private String userId;
	private String userName;
	private String logType;
	private Long fromSeq;
	private Long toSeq;
	private Long fromId;
	private Long toId;
	private Long voucherOrderId;
	
	public TVoucherOrderCodeLog() {
	}

	public TVoucherOrderCodeLog(TVoucherOrder tVoucherOrder,
			String logType) {
		this.tVoucherOrder = tVoucherOrder;
		this.logType = logType;
	}

	public TVoucherOrderCodeLog(TVoucherOrder tVoucherOrder,
			String logType,Long fromSeq,Long toSeq,Long fromId,Long toId) {
		this.tVoucherOrder = tVoucherOrder;
		this.logType = logType;
		this.fromSeq = fromSeq;
		this.toSeq = toSeq;
		this.fromId = fromId;
		this.toId = toId;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_ORDER_CODE_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_ORDER_CODE_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_ORDER_ID", insertable = false, updatable = false)
	public TVoucherOrder gettVoucherOrder() {
		return this.tVoucherOrder;
	}

	public void settVoucherOrder(TVoucherOrder tVoucherOrder) {
		this.tVoucherOrder = tVoucherOrder;
	}
	
	@Column(name = "VOUCHER_ORDER_ID")
	public Long getVoucherOrderId() {
		return voucherOrderId;
	}

	public void setVoucherOrderId(Long voucherOrderId) {
		this.voucherOrderId = voucherOrderId;
	}
	
	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String UserId) {
		this.userId = UserId;
	}

	@Column(name = "USER_NAME", length = 40)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String UserName) {
		this.userName = UserName;
	}

	@Column(name = "LOG_TYPE", nullable = false, length = 1)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "FROM_SEQ", nullable = false, precision = 38, scale = 0)
	public Long getFromSeq() {
		return this.fromSeq;
	}

	public void setFromSeq(Long fromSeq) {
		this.fromSeq = fromSeq;
	}

	@Column(name = "TO_SEQ", nullable = false, precision = 38, scale = 0)
	public Long getToSeq() {
		return this.toSeq;
	}

	public void setToSeq(Long toSeq) {
		this.toSeq = toSeq;
	}

	@Column(name = "FROM_ID", nullable = false, precision = 38, scale = 0)
	public Long getFromId() {
		return this.fromId;
	}

	public void setFromId(Long fromId) {
		this.fromId = fromId;
	}
	
	@Column(name = "TO_ID", nullable = false, precision = 38, scale = 0)
	public Long getToId() {
		return this.toId;
	}

	public void setToId(Long toId) {
		this.toId = toId;
	}
	
}
