package com.wanda.ccs.model;

// Generated 2011-12-12 16:55:46 by Hibernate Tools 3.2.4.GA

import com.xcesys.extras.core.dao.model.VersionableEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TVoucherOrderReviseLog generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_ORDER_REVISE_LOG")
public class TVoucherOrderReviseLog extends VersionableEntity implements
		java.io.Serializable {

	private Long id;
	private TVoucherOrder tVoucherOrder;
	private String revisedUserId;
	private String revisedUserName;
	private Date revisedTime;
	private String reviseType;
	private String fromStatus;
	private String toStatus;
	private Date fromDate;
	private Date toDate;
	private String remarks;
	private Long voucherOrderId;

	public TVoucherOrderReviseLog() {
	}

	public TVoucherOrderReviseLog(TVoucherOrder tVoucherOrder,
			Date revisedTime, String reviseType) {
		this.tVoucherOrder = tVoucherOrder;
		this.revisedTime = revisedTime;
		this.reviseType = reviseType;
	}

	public TVoucherOrderReviseLog(TVoucherOrder tVoucherOrder,
			String revisedUserId, String revisedUserName, Date revisedTime,
			String reviseType, String fromStatus, String toStatus,
			Date fromDate, Date toDate, String remarks) {
		this.tVoucherOrder = tVoucherOrder;
		this.revisedUserId = revisedUserId;
		this.revisedUserName = revisedUserName;
		this.revisedTime = revisedTime;
		this.reviseType = reviseType;
		this.fromStatus = fromStatus;
		this.toStatus = toStatus;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.remarks = remarks;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_ORDER_REVISE_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_ORDER_REVISE_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_ORDER_ID", insertable = false, updatable = false)
	public TVoucherOrder gettVoucherOrder() {
		return this.tVoucherOrder;
	}

	public void settVoucherOrder(TVoucherOrder tVoucherOrder) {
		this.tVoucherOrder = tVoucherOrder;
	}
	
	@Column(name = "VOUCHER_ORDER_ID")
	public Long getVoucherOrderId() {
		return voucherOrderId;
	}

	public void setVoucherOrderId(Long voucherOrderId) {
		this.voucherOrderId = voucherOrderId;
	}
	
	@Column(name = "REVISED_USER_ID", length = 20)
	public String getRevisedUserId() {
		return this.revisedUserId;
	}

	public void setRevisedUserId(String revisedUserId) {
		this.revisedUserId = revisedUserId;
	}

	@Column(name = "REVISED_USER_NAME", length = 40)
	public String getRevisedUserName() {
		return this.revisedUserName;
	}

	public void setRevisedUserName(String revisedUserName) {
		this.revisedUserName = revisedUserName;
	}

	@Column(name = "REVISED_TIME", nullable = false, length = 11)
	public Date getRevisedTime() {
		return this.revisedTime;
	}

	public void setRevisedTime(Date revisedTime) {
		this.revisedTime = revisedTime;
	}

	@Column(name = "REVISE_TYPE", nullable = false, length = 1)
	public String getReviseType() {
		return this.reviseType;
	}

	public void setReviseType(String reviseType) {
		this.reviseType = reviseType;
	}

	@Column(name = "FROM_STATUS", length = 1)
	public String getFromStatus() {
		return this.fromStatus;
	}

	public void setFromStatus(String fromStatus) {
		this.fromStatus = fromStatus;
	}

	@Column(name = "TO_STATUS", length = 1)
	public String getToStatus() {
		return this.toStatus;
	}

	public void setToStatus(String toStatus) {
		this.toStatus = toStatus;
	}

	@Column(name = "FROM_DATE", length = 7)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Column(name = "TO_DATE", length = 7)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	
	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}
