package com.wanda.ccs.model;


import com.xcesys.extras.core.dao.model.VersionableEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TVoucherPrintCFG generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_PRINT_CFG")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class TVoucherPrintCFG extends VersionableEntity implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5275179031370340178L;
	private Long id;
	private TCinema tCinema; // 配置所属影城
	private Long cinemaId;// 配置所属影城
	private Integer numPerPage;// 每页显示个数
	private String xStart;// 打印是显示的X坐标值
	private String yStart;// 打印是显示的Y坐标值
	private Integer fontSize;// 打印的字体大小
	private Integer height;// 每条打印券的上下间距
	private Integer rotate;// 旋转度数
	private Integer imgHeight;// 条码图片的高度
	private String regionCode;// 配置所属区域

	public TVoucherPrintCFG() {
	}

	public TVoucherPrintCFG(Long id, Long cinemaId,TCinema tCinema,
			Integer numPerPage, String xStart, String yStart, Integer fontSize,
			Integer height, Integer rotate, Integer imgHeight, String regionCode) {
		super();
		this.id = id;
		this.tCinema = tCinema;
		this.cinemaId = cinemaId;
		this.numPerPage = numPerPage;
		this.xStart = xStart;
		this.yStart = yStart;
		this.fontSize = fontSize;
		this.height = height;
		this.rotate = rotate;
		this.imgHeight = imgHeight;
		this.regionCode = regionCode;
	}

	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_PRINT_CFG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_PRINT_CFG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CINEMA_ID", insertable = false, updatable = false)
	public TCinema gettCinema() {
		return this.tCinema;
	}

	public void settCinema(TCinema tCinema) {
		this.tCinema = tCinema;
	}

	@Column(name = "CINEMA_ID", nullable = false)
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "NUM_PER_PAGE", nullable = false)
	public Integer getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Integer numPerPage) {
		this.numPerPage = numPerPage;
	}

	@Column(name = "XSTART", length = 512, nullable = false)
	public String getxStart() {
		return xStart;
	}

	public void setxStart(String xStart) {
		this.xStart = xStart;
	}

	@Column(name = "YSTART", length = 512, nullable = false)
	public String getyStart() {
		return yStart;
	}

	public void setyStart(String yStart) {
		this.yStart = yStart;
	}

	@Column(name = "FONT_SIZE", nullable = false)
	public Integer getFontSize() {
		return fontSize;
	}

	public void setFontSize(Integer fontSize) {
		this.fontSize = fontSize;
	}

	@Column(name = "HEIGHT", nullable = false)
	public Integer getHeight() {
		return height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "ROTATE", nullable = false)
	public Integer getRotate() {
		return rotate;
	}

	public void setRotate(Integer rotate) {
		this.rotate = rotate;
	}

	@Column(name = "IMG_HEIGHT", nullable = false)
	public Integer getImgHeight() {
		return imgHeight;
	}

	public void setImgHeight(Integer imgHeight) {
		this.imgHeight = imgHeight;
	}

	@Column(name = "REGION_CODE" , length = 20)
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

}
