package com.wanda.ccs.model;

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.xcesys.extras.core.dao.model.VersionableEntity;

/**
 * TVoucherUseLog generated by hbm2java
 */
@Entity
@Table(name = "T_VOUCHER_FILM_LOG")
public class TVoucherFilmLog extends VersionableEntity implements
		java.io.Serializable {
	private Long id;  //回兑ID
	private Long ticketNum;  //购票张数
	private String performId; //场次编号（影片标识代号 ）
	private String filmCode;  //影片代码
	private String filmName;  //影片名称
	private Integer filmPrice;	//出票价格
	private Date showTime;   //影片上映时间
	private String ticketTypeCode; //购票使用的票类编码
	private String ticketTypeName; //购票使用的票类名称
	private TVoucherUseLog tVoucherUseLog; //券回兑记录编号
	private Long voucherUseLogId;
	
	public TVoucherFilmLog(){
	}
	
	public TVoucherFilmLog(Long id, Long ticketNum, String performId,
			String filmCode,String filmName,Date showTime,String ticketTypeCode,
			String ticketTypeName,TVoucherUseLog tVoucherUseLog) {
		this.id = id;
		this.ticketNum = ticketNum;
		this.performId = performId;
		this.filmCode = filmCode;
		this.filmName = filmName;
		this.showTime = showTime;
		this.ticketTypeCode = ticketTypeCode;
		this.ticketTypeName = ticketTypeName;
		this.tVoucherUseLog = tVoucherUseLog;
	}
	
	@SequenceGenerator(name = "generator", sequenceName = "S_T_VOUCHER_FILM_LOG")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "VOUCHER_FILM_LOG_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "TICKET_NUM", precision = 22, scale = 0)
	public Long getTicketNum() {
		return this.ticketNum;
	}

	public void setTicketNum(Long ticketNum) {
		this.ticketNum = ticketNum;
	}

	@Column(name = "PERFORM_ID", length = 20)
	public String getPerformId() {
		return performId;
	}

	public void setPerformId(String performId) {
		this.performId = performId;
	}

	@Column(name = "FILM_CODE", length = 20)
	public String getFilmCode() {
		return filmCode;
	}

	public void setFilmCode(String filmCode) {
		this.filmCode = filmCode;
	}

	@Column(name = "FILM_NAME", length = 1024)
	public String getFilmName() {
		return filmName;
	}

	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}

	@Column(name = "SHOW_TIME", length = 11)
	public Date getShowTime() {
		return showTime;
	}

	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}

	@Column(name = "TICKET_TYPE_CODE", length = 50)
	public String getTicketTypeCode() {
		return ticketTypeCode;
	}

	public void setTicketTypeCode(String ticketTypeCode) {
		this.ticketTypeCode = ticketTypeCode;
	}

	@Column(name = "TICKET_TYPE_NAME", length = 1024)
	public String getTicketTypeName() {
		return ticketTypeName;
	}

	public void setTicketTypeName(String ticketTypeName) {
		this.ticketTypeName = ticketTypeName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_USE_LOG_ID", nullable = false, insertable = false, updatable = false)
	public TVoucherUseLog gettVoucherUseLog() {
		return tVoucherUseLog;
	}

	public void settVoucherUseLog(TVoucherUseLog tVoucherUseLog) {
		this.tVoucherUseLog = tVoucherUseLog;
	}

	@Column(name = "VOUCHER_USE_LOG_ID", nullable = false)
	public Long getVoucherUseLogId() {
		return voucherUseLogId;
	}

	public void setVoucherUseLogId(Long voucherUseLogId) {
		this.voucherUseLogId = voucherUseLogId;
	}

	@Column(name = "FILM_PRICE")
	public Integer getFilmPrice() {
		return filmPrice;
	}

	public void setFilmPrice(Integer filmPrice) {
		this.filmPrice = filmPrice;
	}

}
