package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:39 by Hibernate Tools 3.2.4.GA


import com.xcesys.extras.core.dao.model.AbstractEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VNcUsers generated by hbm2java
 */
@Entity
@Table(name = "V_CARD_TYPE_GOODS_DISCOUNT")
public class VCardTypeGoodsDiscount extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1167233884935360184L;
	
	private Long cardTypeId;
	private Long cinema;
	private String area;
	private Long discount;
	private String typeName;
	private String cinemaName;

	public VCardTypeGoodsDiscount() {
	}
	
	@Id
	@Column(name = "CARD_TYPE_ID")
	public Long getCardTypeId() {
		return cardTypeId;
	}

	public void setCardTypeId(Long cardTypeId) {
		this.cardTypeId = cardTypeId;
	}
	
	@Id
	@Column(name = "CINEMA")
	public Long getCinema() {
		return cinema;
	}

	public void setCinema(Long cinema) {
		this.cinema = cinema;
	}
	
	@Column(name = "AREA", length = 38)
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}
	
	@Column(name = "DISCOUNT")
	public Long getDiscount() {
		return discount;
	}

	public void setDiscount(Long discount) {
		this.discount = discount;
	}
	
	@Column(name = "TYPE_NAME")
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
	
	@Column(name = "CINEMA_NAME")
	public String getCinemaName() {
		return cinemaName;
	}

	public void setCinemaName(String cinemaName) {
		this.cinemaName = cinemaName;
	}


	@Override
	@Transient
	public Long getId() {
		return null;
	}

	@Override
	public void setId(Long arg0) {
		
	}
	
	
	
}
