package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:39 by Hibernate Tools 3.2.4.GA


import com.xcesys.extras.core.dao.model.AbstractEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VConItemCinema generated by hbm2java
 */
@Entity
@Table(name = "V_CON_ITEM_CINEMA")
public class VConItemCinema extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1167233884935360184L;
	private String area;
	private Long cinemaId;
	private Long conItemId;
	
	public VConItemCinema() {
	}
	
	@Column(name = "AREA")
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}
	
	@Column(name = "CINEMA_ID")
	public Long getCinemaId() {
		return cinemaId;
	}

	public void setCinemaId(Long cinemaId) {
		this.cinemaId = cinemaId;
	}
	@Id
	@Column(name = "CON_ITEM_ID")
	public Long getConItemId() {
		return conItemId;
	}

	public void setConItemId(Long conItemId) {
		this.conItemId = conItemId;
	}

	@Override
	@Transient
	public Long getId() {
		
		return null;
	}

	@Override
	public void setId(Long arg0) {
		
	}
	
	
}
