package com.wanda.ccs.model;

// Generated 2012-1-12 17:18:39 by Hibernate Tools 3.2.4.GA


import com.xcesys.extras.core.dao.model.AbstractEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VNcUsers generated by hbm2java
 */
@Entity
@Table(name = "V_NC_SM_USER")
public class VNcSmUser extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1167233884935360184L;
	private String userCode;
	private String userPassword;
	private String pkPsnbasdoc;
	private Integer pwdtype;
	private String pwdparam;
	private String authen_type;
	private String psnname;
	private String pkCorp;
	private String unitcode;
	private String unitName;
	
	public VNcSmUser() {
	}
	
	@Id
	@Column(name = "USER_CODE", nullable = false, length = 50)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	
	@Column(name = "PK_PSNBASDOC", length = 20)
	public String getPkPsnbasdoc() {
		return this.pkPsnbasdoc;
	}

	public void setPkPsnbasdoc(String pkPsnbasdoc) {
		this.pkPsnbasdoc = pkPsnbasdoc;
	}


	

	@Column(name = "PSNNAME",  length = 200)
	public String getPsnname() {
		return psnname;
	}

	public void setPsnname(String psnname) {
		this.psnname = psnname;
	}

	@Column(name = "USER_PASSWORD", length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "PWDTYPE", precision = 22, scale = 0)
	public Integer getPwdtype() {
		return this.pwdtype;
	}

	public void setPwdtype(Integer pwdtype) {
		this.pwdtype = pwdtype;
	}

	@Column(name = "PWDPARAM", length = 50)
	public String getPwdparam() {
		return this.pwdparam;
	}

	public void setPwdparam(String pwdparam) {
		this.pwdparam = pwdparam;
	}
	
	@Column(name = "AUTHEN_TYPE", length = 50)
	public String getAuthen_type() {
		return authen_type;
	}

	public void setAuthen_type(String authen_type) {
		this.authen_type = authen_type;
	}
	
	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}
	
	@Column(name = "UNITCODE", length = 40)
	public String getUnitcode() {
		return unitcode;
	}

	public void setUnitcode(String unitcode) {
		this.unitcode = unitcode;
	}
	
	@Column(name = "UNITNAME", length = 200)
	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}
	
	
	@Override
	@Transient
	public Long getId() {
		
		return null;
	}

	@Override
	public void setId(Long arg0) {
		
	}
	
	
}
