package com.wanda.member.upgrade.data;

import com.wanda.member.upgrade.data.TMember;
import com.wanda.member.upgrade.data.TMemberExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int countByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int deleteByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int insert(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int insertSelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    List<TMember> selectByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    TMember selectByPrimaryKey(String memberNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int updateByExampleSelective(@Param("record") TMember record, @Param("example") TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int updateByExample(@Param("record") TMember record, @Param("example") TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int updateByPrimaryKeySelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    int updateByPrimaryKey(TMember record);

	TMember selectByPrimaryKeyByMemberId(BigDecimal memberId);
}