CREATE OR REPLACE PROCEDURE P_SYS_MBR_DW_SYNC
(
in_sync_date in varchar2 --同步日期字符串YYYYMMDD
)
--同步会员相关信息
AS
on_flag NUMBER;
os_prompt varchar2(3000);
v_sync_date  varchar2(6); --同步日期字符串YYYYMMDD
BEGIN
-------------T_FILM--------------------
DELETE FROM T_FILM where SEQID in (
select SEQID from ccs_report.T_FILM@OPLDW
where update_date>=to_date(in_sync_date,'yyyymmdd') + 6/24 and update_date <to_date(in_sync_date,'yyyymmdd') + 30/24
);
insert into T_FILM
(SEQID,PUBLISHER_ID,FILM_TYPE,FILM_CODE,FILM_NAME,RUNNING_TIME,ENGLISH_NAME,PAI_CI_HAO,FILM_LEVEL,COUNTRY,SUBTITLE1,SUBTITLE2,FILM_SET,AUDIO_TYPE,YEAR_MONTH,PREMIERE_DATE,END_DATE,ACCOUNT_RATIO,TAX_RATIO,PUBLISHER_ID2,DISPLAY_NAME,PIN_CODE,SERIES_NAME,SHOW_SET,ACCOUNT_TYPE,FILM_ACCOUNT_TYPE,PRICE_BASE_ID,FILM_CATE,LANGUAGE,COPY_COUNT,DIGIT_COPY_COUNT,FILM_COMPANY,PRODUCER,DIRECTOR,MAIN_ACTORS,STORY_BRIEF,CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY,DELETED,DELETE_DATE,DELETE_BY,VERSION,RELEASE_TYPE,IS_DIGITAL,IS_3D,IS_FILM,IS_IMAX,IS_REALD,UNIQUE_FILM_ID,MODIFIED)
select SEQID,PUBLISHER_ID,FILM_TYPE,FILM_CODE,FILM_NAME,RUNNING_TIME,ENGLISH_NAME,PAI_CI_HAO,FILM_LEVEL,COUNTRY,SUBTITLE1,SUBTITLE2,FILM_SET,AUDIO_TYPE,YEAR_MONTH,PREMIERE_DATE,END_DATE,ACCOUNT_RATIO,TAX_RATIO,PUBLISHER_ID2,DISPLAY_NAME,PIN_CODE,SERIES_NAME,SHOW_SET,ACCOUNT_TYPE,FILM_ACCOUNT_TYPE,PRICE_BASE_ID,FILM_CATE,LANGUAGE,COPY_COUNT,DIGIT_COPY_COUNT,FILM_COMPANY,PRODUCER,DIRECTOR,MAIN_ACTORS,STORY_BRIEF,CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY,DELETED,DELETE_DATE,DELETE_BY,VERSION,RELEASE_TYPE,IS_DIGITAL,IS_3D,IS_FILM,IS_IMAX,IS_REALD,UNIQUE_FILM_ID,MODIFIED
from ccs_report.T_FILM@OPLDW
where update_date>=to_date(20130819,'yyyymmdd') + 6/24 and update_date <to_date(in_sync_date,'yyyymmdd') + 30/24 ;
COMMIT;
-------------T_FT_TYPE--------------------
DELETE FROM T_FT_TYPE ;
insert into T_FT_TYPE
(FILM_ID,TYPE,IDX)
select FILM_ID,TYPE,IDX
from ccs_mbr_dw.T_FT_TYPE@OPLDW
COMMIT;
/******************************同步完成******************************/
on_flag:=0;
os_prompt:='同步成功';
P_SYS_TASK_SCHEDULING_LOG('P_SYS_MBR_SYNC','P_SYS_MBR_SYNC',NULL,SYSDATE,on_flag,os_prompt);
COMMIT;

EXCEPTION
   WHEN NO_DATA_FOUND THEN
     P_SYS_SP_FN_ERR_LOG('P_SYS_MBR_SYNC',SYSDATE,'ERROR','数据库中NO_DATA_FOUND');
      WHEN TOO_MANY_ROWS THEN
      P_SYS_SP_FN_ERR_LOG('P_SYS_MBR_SYNC',SYSDATE,'ERROR','TOO_MANY_ROWS');
      WHEN OTHERS THEN
      on_flag := -1;
rollback;
P_SYS_TASK_SCHEDULING_LOG('P_SYS_MBR_SYNC','P_SYS_MBR_SYNC',NULL,SYSDATE,on_flag,SUBSTRB(SQLERRM,1,3000));
end;
