package com.wanda.mms.data;

import java.math.BigDecimal;
import java.util.Date;

public class TActResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.ACT_RESULT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal actResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CMN_ACTIVITY_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal cmnActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.VOUCHER_POOL_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal voucherPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.EXT_POINT_RULE_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal extPointRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CONTACT_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal contactCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.RES_CONFIG_TYPE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private String resConfigType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.RES_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal resSegmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.ALTER_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal alterSegmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CONTROL_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal controlResCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal resCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.ALTER_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal alterResCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CREATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CREATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.UPDATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.VERSION
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.STATUS
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_RESULT.CONTROL_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    private BigDecimal controlCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.ACT_RESULT_ID
     *
     * @return the value of T_ACT_RESULT.ACT_RESULT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getActResultId() {
        return actResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.ACT_RESULT_ID
     *
     * @param actResultId the value for T_ACT_RESULT.ACT_RESULT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setActResultId(BigDecimal actResultId) {
        this.actResultId = actResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CMN_ACTIVITY_ID
     *
     * @return the value of T_ACT_RESULT.CMN_ACTIVITY_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getCmnActivityId() {
        return cmnActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CMN_ACTIVITY_ID
     *
     * @param cmnActivityId the value for T_ACT_RESULT.CMN_ACTIVITY_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setCmnActivityId(BigDecimal cmnActivityId) {
        this.cmnActivityId = cmnActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.VOUCHER_POOL_ID
     *
     * @return the value of T_ACT_RESULT.VOUCHER_POOL_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getVoucherPoolId() {
        return voucherPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.VOUCHER_POOL_ID
     *
     * @param voucherPoolId the value for T_ACT_RESULT.VOUCHER_POOL_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setVoucherPoolId(BigDecimal voucherPoolId) {
        this.voucherPoolId = voucherPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.EXT_POINT_RULE_ID
     *
     * @return the value of T_ACT_RESULT.EXT_POINT_RULE_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getExtPointRuleId() {
        return extPointRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.EXT_POINT_RULE_ID
     *
     * @param extPointRuleId the value for T_ACT_RESULT.EXT_POINT_RULE_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setExtPointRuleId(BigDecimal extPointRuleId) {
        this.extPointRuleId = extPointRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CONTACT_COUNT
     *
     * @return the value of T_ACT_RESULT.CONTACT_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getContactCount() {
        return contactCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CONTACT_COUNT
     *
     * @param contactCount the value for T_ACT_RESULT.CONTACT_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setContactCount(BigDecimal contactCount) {
        this.contactCount = contactCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.RES_CONFIG_TYPE
     *
     * @return the value of T_ACT_RESULT.RES_CONFIG_TYPE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public String getResConfigType() {
        return resConfigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.RES_CONFIG_TYPE
     *
     * @param resConfigType the value for T_ACT_RESULT.RES_CONFIG_TYPE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setResConfigType(String resConfigType) {
        this.resConfigType = resConfigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.RES_SEGMENT_ID
     *
     * @return the value of T_ACT_RESULT.RES_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getResSegmentId() {
        return resSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.RES_SEGMENT_ID
     *
     * @param resSegmentId the value for T_ACT_RESULT.RES_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setResSegmentId(BigDecimal resSegmentId) {
        this.resSegmentId = resSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.ALTER_SEGMENT_ID
     *
     * @return the value of T_ACT_RESULT.ALTER_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getAlterSegmentId() {
        return alterSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.ALTER_SEGMENT_ID
     *
     * @param alterSegmentId the value for T_ACT_RESULT.ALTER_SEGMENT_ID
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setAlterSegmentId(BigDecimal alterSegmentId) {
        this.alterSegmentId = alterSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CONTROL_RES_COUNT
     *
     * @return the value of T_ACT_RESULT.CONTROL_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getControlResCount() {
        return controlResCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CONTROL_RES_COUNT
     *
     * @param controlResCount the value for T_ACT_RESULT.CONTROL_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setControlResCount(BigDecimal controlResCount) {
        this.controlResCount = controlResCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.RES_COUNT
     *
     * @return the value of T_ACT_RESULT.RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getResCount() {
        return resCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.RES_COUNT
     *
     * @param resCount the value for T_ACT_RESULT.RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setResCount(BigDecimal resCount) {
        this.resCount = resCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.ALTER_RES_COUNT
     *
     * @return the value of T_ACT_RESULT.ALTER_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getAlterResCount() {
        return alterResCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.ALTER_RES_COUNT
     *
     * @param alterResCount the value for T_ACT_RESULT.ALTER_RES_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setAlterResCount(BigDecimal alterResCount) {
        this.alterResCount = alterResCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CREATE_BY
     *
     * @return the value of T_ACT_RESULT.CREATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CREATE_BY
     *
     * @param createBy the value for T_ACT_RESULT.CREATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CREATE_DATE
     *
     * @return the value of T_ACT_RESULT.CREATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CREATE_DATE
     *
     * @param createDate the value for T_ACT_RESULT.CREATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.UPDATE_BY
     *
     * @return the value of T_ACT_RESULT.UPDATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.UPDATE_BY
     *
     * @param updateBy the value for T_ACT_RESULT.UPDATE_BY
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.UPDATE_DATE
     *
     * @return the value of T_ACT_RESULT.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.UPDATE_DATE
     *
     * @param updateDate the value for T_ACT_RESULT.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.VERSION
     *
     * @return the value of T_ACT_RESULT.VERSION
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.VERSION
     *
     * @param version the value for T_ACT_RESULT.VERSION
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.STATUS
     *
     * @return the value of T_ACT_RESULT.STATUS
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.STATUS
     *
     * @param status the value for T_ACT_RESULT.STATUS
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_RESULT.CONTROL_COUNT
     *
     * @return the value of T_ACT_RESULT.CONTROL_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public BigDecimal getControlCount() {
        return controlCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_RESULT.CONTROL_COUNT
     *
     * @param controlCount the value for T_ACT_RESULT.CONTROL_COUNT
     *
     * @mbggenerated Thu Sep 26 14:35:44 CST 2013
     */
    public void setControlCount(BigDecimal controlCount) {
        this.controlCount = controlCount;
    }
}