package com.wanda.member.upgrade.data;

import com.wanda.member.upgrade.data.TLevelHistory;
import com.wanda.member.upgrade.data.TLevelHistoryExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLevelHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int countByExample(TLevelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int deleteByExample(TLevelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int deleteByPrimaryKey(BigDecimal levelHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int insert(TLevelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int insertSelective(TLevelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    List<TLevelHistory> selectByExample(TLevelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    TLevelHistory selectByPrimaryKey(BigDecimal levelHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") TLevelHistory record, @Param("example") TLevelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int updateByExample(@Param("record") TLevelHistory record, @Param("example") TLevelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int updateByPrimaryKeySelective(TLevelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LEVEL_HISTORY
     *
     * @mbggenerated Wed Oct 30 21:16:09 CST 2013
     */
    int updateByPrimaryKey(TLevelHistory record);
}