package com.wanda.member.upgrade.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public TMemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(BigDecimal value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(BigDecimal value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<BigDecimal> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<BigDecimal> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andRegistTypeIsNull() {
            addCriterion("REGIST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRegistTypeIsNotNull() {
            addCriterion("REGIST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRegistTypeEqualTo(BigDecimal value) {
            addCriterion("REGIST_TYPE =", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeNotEqualTo(BigDecimal value) {
            addCriterion("REGIST_TYPE <>", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeGreaterThan(BigDecimal value) {
            addCriterion("REGIST_TYPE >", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REGIST_TYPE >=", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeLessThan(BigDecimal value) {
            addCriterion("REGIST_TYPE <", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REGIST_TYPE <=", value, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeIn(List<BigDecimal> values) {
            addCriterion("REGIST_TYPE in", values, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeNotIn(List<BigDecimal> values) {
            addCriterion("REGIST_TYPE not in", values, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGIST_TYPE between", value1, value2, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGIST_TYPE not between", value1, value2, "registType");
            return (Criteria) this;
        }

        public Criteria andRegistChnidIsNull() {
            addCriterion("REGIST_CHNID is null");
            return (Criteria) this;
        }

        public Criteria andRegistChnidIsNotNull() {
            addCriterion("REGIST_CHNID is not null");
            return (Criteria) this;
        }

        public Criteria andRegistChnidEqualTo(String value) {
            addCriterion("REGIST_CHNID =", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidNotEqualTo(String value) {
            addCriterion("REGIST_CHNID <>", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidGreaterThan(String value) {
            addCriterion("REGIST_CHNID >", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidGreaterThanOrEqualTo(String value) {
            addCriterion("REGIST_CHNID >=", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidLessThan(String value) {
            addCriterion("REGIST_CHNID <", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidLessThanOrEqualTo(String value) {
            addCriterion("REGIST_CHNID <=", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidLike(String value) {
            addCriterion("REGIST_CHNID like", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidNotLike(String value) {
            addCriterion("REGIST_CHNID not like", value, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidIn(List<String> values) {
            addCriterion("REGIST_CHNID in", values, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidNotIn(List<String> values) {
            addCriterion("REGIST_CHNID not in", values, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidBetween(String value1, String value2) {
            addCriterion("REGIST_CHNID between", value1, value2, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistChnidNotBetween(String value1, String value2) {
            addCriterion("REGIST_CHNID not between", value1, value2, "registChnid");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoIsNull() {
            addCriterion("REGIST_OP_NO is null");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoIsNotNull() {
            addCriterion("REGIST_OP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoEqualTo(String value) {
            addCriterion("REGIST_OP_NO =", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoNotEqualTo(String value) {
            addCriterion("REGIST_OP_NO <>", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoGreaterThan(String value) {
            addCriterion("REGIST_OP_NO >", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoGreaterThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_NO >=", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoLessThan(String value) {
            addCriterion("REGIST_OP_NO <", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoLessThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_NO <=", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoLike(String value) {
            addCriterion("REGIST_OP_NO like", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoNotLike(String value) {
            addCriterion("REGIST_OP_NO not like", value, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoIn(List<String> values) {
            addCriterion("REGIST_OP_NO in", values, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoNotIn(List<String> values) {
            addCriterion("REGIST_OP_NO not in", values, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoBetween(String value1, String value2) {
            addCriterion("REGIST_OP_NO between", value1, value2, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNoNotBetween(String value1, String value2) {
            addCriterion("REGIST_OP_NO not between", value1, value2, "registOpNo");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameIsNull() {
            addCriterion("REGIST_OP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameIsNotNull() {
            addCriterion("REGIST_OP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameEqualTo(String value) {
            addCriterion("REGIST_OP_NAME =", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameNotEqualTo(String value) {
            addCriterion("REGIST_OP_NAME <>", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameGreaterThan(String value) {
            addCriterion("REGIST_OP_NAME >", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameGreaterThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_NAME >=", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameLessThan(String value) {
            addCriterion("REGIST_OP_NAME <", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameLessThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_NAME <=", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameLike(String value) {
            addCriterion("REGIST_OP_NAME like", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameNotLike(String value) {
            addCriterion("REGIST_OP_NAME not like", value, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameIn(List<String> values) {
            addCriterion("REGIST_OP_NAME in", values, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameNotIn(List<String> values) {
            addCriterion("REGIST_OP_NAME not in", values, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameBetween(String value1, String value2) {
            addCriterion("REGIST_OP_NAME between", value1, value2, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistOpNameNotBetween(String value1, String value2) {
            addCriterion("REGIST_OP_NAME not between", value1, value2, "registOpName");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdIsNull() {
            addCriterion("REGIST_CINEMA_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdIsNotNull() {
            addCriterion("REGIST_CINEMA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdEqualTo(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID =", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdNotEqualTo(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID <>", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdGreaterThan(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID >", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID >=", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdLessThan(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID <", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REGIST_CINEMA_ID <=", value, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdIn(List<BigDecimal> values) {
            addCriterion("REGIST_CINEMA_ID in", values, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdNotIn(List<BigDecimal> values) {
            addCriterion("REGIST_CINEMA_ID not in", values, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGIST_CINEMA_ID between", value1, value2, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andRegistCinemaIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGIST_CINEMA_ID not between", value1, value2, "registCinemaId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(BigDecimal value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(BigDecimal value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(BigDecimal value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(BigDecimal value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<BigDecimal> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<BigDecimal> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("ISDELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("ISDELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(BigDecimal value) {
            addCriterion("ISDELETE =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(BigDecimal value) {
            addCriterion("ISDELETE >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(BigDecimal value) {
            addCriterion("ISDELETE <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<BigDecimal> values) {
            addCriterion("ISDELETE in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<BigDecimal> values) {
            addCriterion("ISDELETE not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(BigDecimal value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(BigDecimal value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(BigDecimal value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(BigDecimal value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<BigDecimal> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<BigDecimal> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIscontactableIsNull() {
            addCriterion("ISCONTACTABLE is null");
            return (Criteria) this;
        }

        public Criteria andIscontactableIsNotNull() {
            addCriterion("ISCONTACTABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIscontactableEqualTo(BigDecimal value) {
            addCriterion("ISCONTACTABLE =", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableNotEqualTo(BigDecimal value) {
            addCriterion("ISCONTACTABLE <>", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableGreaterThan(BigDecimal value) {
            addCriterion("ISCONTACTABLE >", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISCONTACTABLE >=", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableLessThan(BigDecimal value) {
            addCriterion("ISCONTACTABLE <", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISCONTACTABLE <=", value, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableIn(List<BigDecimal> values) {
            addCriterion("ISCONTACTABLE in", values, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableNotIn(List<BigDecimal> values) {
            addCriterion("ISCONTACTABLE not in", values, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISCONTACTABLE between", value1, value2, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andIscontactableNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISCONTACTABLE not between", value1, value2, "iscontactable");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdIsNull() {
            addCriterion("FAV_CINEMA_ID is null");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdIsNotNull() {
            addCriterion("FAV_CINEMA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdEqualTo(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID =", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdNotEqualTo(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID <>", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdGreaterThan(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID >", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID >=", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdLessThan(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID <", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FAV_CINEMA_ID <=", value, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdIn(List<BigDecimal> values) {
            addCriterion("FAV_CINEMA_ID in", values, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdNotIn(List<BigDecimal> values) {
            addCriterion("FAV_CINEMA_ID not in", values, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAV_CINEMA_ID between", value1, value2, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andFavCinemaIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAV_CINEMA_ID not between", value1, value2, "favCinemaId");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("SOURCE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("SOURCE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeEqualTo(String value) {
            addCriterion("SOURCE_TYPE =", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotEqualTo(String value) {
            addCriterion("SOURCE_TYPE <>", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThan(String value) {
            addCriterion("SOURCE_TYPE >", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_TYPE >=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThan(String value) {
            addCriterion("SOURCE_TYPE <", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_TYPE <=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLike(String value) {
            addCriterion("SOURCE_TYPE like", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotLike(String value) {
            addCriterion("SOURCE_TYPE not like", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIn(List<String> values) {
            addCriterion("SOURCE_TYPE in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotIn(List<String> values) {
            addCriterion("SOURCE_TYPE not in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeBetween(String value1, String value2) {
            addCriterion("SOURCE_TYPE between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotBetween(String value1, String value2) {
            addCriterion("SOURCE_TYPE not between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNull() {
            addCriterion("REGIST_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNotNull() {
            addCriterion("REGIST_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegistDateEqualTo(Date value) {
            addCriterion("REGIST_DATE =", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotEqualTo(Date value) {
            addCriterion("REGIST_DATE <>", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThan(Date value) {
            addCriterion("REGIST_DATE >", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThanOrEqualTo(Date value) {
            addCriterion("REGIST_DATE >=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThan(Date value) {
            addCriterion("REGIST_DATE <", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThanOrEqualTo(Date value) {
            addCriterion("REGIST_DATE <=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateIn(List<Date> values) {
            addCriterion("REGIST_DATE in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotIn(List<Date> values) {
            addCriterion("REGIST_DATE not in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateBetween(Date value1, Date value2) {
            addCriterion("REGIST_DATE between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotBetween(Date value1, Date value2) {
            addCriterion("REGIST_DATE not between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionIsNull() {
            addCriterion("CHANGE_STATUS_RESION is null");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionIsNotNull() {
            addCriterion("CHANGE_STATUS_RESION is not null");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionEqualTo(String value) {
            addCriterion("CHANGE_STATUS_RESION =", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionNotEqualTo(String value) {
            addCriterion("CHANGE_STATUS_RESION <>", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionGreaterThan(String value) {
            addCriterion("CHANGE_STATUS_RESION >", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionGreaterThanOrEqualTo(String value) {
            addCriterion("CHANGE_STATUS_RESION >=", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionLessThan(String value) {
            addCriterion("CHANGE_STATUS_RESION <", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionLessThanOrEqualTo(String value) {
            addCriterion("CHANGE_STATUS_RESION <=", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionLike(String value) {
            addCriterion("CHANGE_STATUS_RESION like", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionNotLike(String value) {
            addCriterion("CHANGE_STATUS_RESION not like", value, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionIn(List<String> values) {
            addCriterion("CHANGE_STATUS_RESION in", values, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionNotIn(List<String> values) {
            addCriterion("CHANGE_STATUS_RESION not in", values, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionBetween(String value1, String value2) {
            addCriterion("CHANGE_STATUS_RESION between", value1, value2, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andChangeStatusResionNotBetween(String value1, String value2) {
            addCriterion("CHANGE_STATUS_RESION not between", value1, value2, "changeStatusResion");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoIsNull() {
            addCriterion("HIS_MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoIsNotNull() {
            addCriterion("HIS_MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoEqualTo(String value) {
            addCriterion("HIS_MEMBER_NO =", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoNotEqualTo(String value) {
            addCriterion("HIS_MEMBER_NO <>", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoGreaterThan(String value) {
            addCriterion("HIS_MEMBER_NO >", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("HIS_MEMBER_NO >=", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoLessThan(String value) {
            addCriterion("HIS_MEMBER_NO <", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoLessThanOrEqualTo(String value) {
            addCriterion("HIS_MEMBER_NO <=", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoLike(String value) {
            addCriterion("HIS_MEMBER_NO like", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoNotLike(String value) {
            addCriterion("HIS_MEMBER_NO not like", value, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoIn(List<String> values) {
            addCriterion("HIS_MEMBER_NO in", values, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoNotIn(List<String> values) {
            addCriterion("HIS_MEMBER_NO not in", values, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoBetween(String value1, String value2) {
            addCriterion("HIS_MEMBER_NO between", value1, value2, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andHisMemberNoNotBetween(String value1, String value2) {
            addCriterion("HIS_MEMBER_NO not between", value1, value2, "hisMemberNo");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearIsNull() {
            addCriterion("BIRTHDAY_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearIsNotNull() {
            addCriterion("BIRTHDAY_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearEqualTo(String value) {
            addCriterion("BIRTHDAY_YEAR =", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearNotEqualTo(String value) {
            addCriterion("BIRTHDAY_YEAR <>", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearGreaterThan(String value) {
            addCriterion("BIRTHDAY_YEAR >", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_YEAR >=", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearLessThan(String value) {
            addCriterion("BIRTHDAY_YEAR <", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_YEAR <=", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearLike(String value) {
            addCriterion("BIRTHDAY_YEAR like", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearNotLike(String value) {
            addCriterion("BIRTHDAY_YEAR not like", value, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearIn(List<String> values) {
            addCriterion("BIRTHDAY_YEAR in", values, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearNotIn(List<String> values) {
            addCriterion("BIRTHDAY_YEAR not in", values, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_YEAR between", value1, value2, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayYearNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_YEAR not between", value1, value2, "birthdayYear");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthIsNull() {
            addCriterion("BIRTHDAY_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthIsNotNull() {
            addCriterion("BIRTHDAY_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthEqualTo(String value) {
            addCriterion("BIRTHDAY_MONTH =", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthNotEqualTo(String value) {
            addCriterion("BIRTHDAY_MONTH <>", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthGreaterThan(String value) {
            addCriterion("BIRTHDAY_MONTH >", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_MONTH >=", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthLessThan(String value) {
            addCriterion("BIRTHDAY_MONTH <", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_MONTH <=", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthLike(String value) {
            addCriterion("BIRTHDAY_MONTH like", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthNotLike(String value) {
            addCriterion("BIRTHDAY_MONTH not like", value, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthIn(List<String> values) {
            addCriterion("BIRTHDAY_MONTH in", values, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthNotIn(List<String> values) {
            addCriterion("BIRTHDAY_MONTH not in", values, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_MONTH between", value1, value2, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayMonthNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_MONTH not between", value1, value2, "birthdayMonth");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayIsNull() {
            addCriterion("BIRTHDAY_DAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayIsNotNull() {
            addCriterion("BIRTHDAY_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayEqualTo(String value) {
            addCriterion("BIRTHDAY_DAY =", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayNotEqualTo(String value) {
            addCriterion("BIRTHDAY_DAY <>", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayGreaterThan(String value) {
            addCriterion("BIRTHDAY_DAY >", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_DAY >=", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayLessThan(String value) {
            addCriterion("BIRTHDAY_DAY <", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY_DAY <=", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayLike(String value) {
            addCriterion("BIRTHDAY_DAY like", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayNotLike(String value) {
            addCriterion("BIRTHDAY_DAY not like", value, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayIn(List<String> values) {
            addCriterion("BIRTHDAY_DAY in", values, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayNotIn(List<String> values) {
            addCriterion("BIRTHDAY_DAY not in", values, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_DAY between", value1, value2, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andBirthdayDayNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY_DAY not between", value1, value2, "birthdayDay");
            return (Criteria) this;
        }

        public Criteria andIsHistoryIsNull() {
            addCriterion("IS_HISTORY is null");
            return (Criteria) this;
        }

        public Criteria andIsHistoryIsNotNull() {
            addCriterion("IS_HISTORY is not null");
            return (Criteria) this;
        }

        public Criteria andIsHistoryEqualTo(String value) {
            addCriterion("IS_HISTORY =", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryNotEqualTo(String value) {
            addCriterion("IS_HISTORY <>", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryGreaterThan(String value) {
            addCriterion("IS_HISTORY >", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("IS_HISTORY >=", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryLessThan(String value) {
            addCriterion("IS_HISTORY <", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryLessThanOrEqualTo(String value) {
            addCriterion("IS_HISTORY <=", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryLike(String value) {
            addCriterion("IS_HISTORY like", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryNotLike(String value) {
            addCriterion("IS_HISTORY not like", value, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryIn(List<String> values) {
            addCriterion("IS_HISTORY in", values, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryNotIn(List<String> values) {
            addCriterion("IS_HISTORY not in", values, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryBetween(String value1, String value2) {
            addCriterion("IS_HISTORY between", value1, value2, "isHistory");
            return (Criteria) this;
        }

        public Criteria andIsHistoryNotBetween(String value1, String value2) {
            addCriterion("IS_HISTORY not between", value1, value2, "isHistory");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysIsNull() {
            addCriterion("REGIST_OP_SYS is null");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysIsNotNull() {
            addCriterion("REGIST_OP_SYS is not null");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysEqualTo(String value) {
            addCriterion("REGIST_OP_SYS =", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysNotEqualTo(String value) {
            addCriterion("REGIST_OP_SYS <>", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysGreaterThan(String value) {
            addCriterion("REGIST_OP_SYS >", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysGreaterThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_SYS >=", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysLessThan(String value) {
            addCriterion("REGIST_OP_SYS <", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysLessThanOrEqualTo(String value) {
            addCriterion("REGIST_OP_SYS <=", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysLike(String value) {
            addCriterion("REGIST_OP_SYS like", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysNotLike(String value) {
            addCriterion("REGIST_OP_SYS not like", value, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysIn(List<String> values) {
            addCriterion("REGIST_OP_SYS in", values, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysNotIn(List<String> values) {
            addCriterion("REGIST_OP_SYS not in", values, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysBetween(String value1, String value2) {
            addCriterion("REGIST_OP_SYS between", value1, value2, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andRegistOpSysNotBetween(String value1, String value2) {
            addCriterion("REGIST_OP_SYS not between", value1, value2, "registOpSys");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeIsNull() {
            addCriterion("BIRTHDAY_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeIsNotNull() {
            addCriterion("BIRTHDAY_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeEqualTo(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME =", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeNotEqualTo(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME <>", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeGreaterThan(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME >", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME >=", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeLessThan(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME <", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BIRTHDAY_UPDATE_TIME <=", value, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeIn(List<BigDecimal> values) {
            addCriterion("BIRTHDAY_UPDATE_TIME in", values, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeNotIn(List<BigDecimal> values) {
            addCriterion("BIRTHDAY_UPDATE_TIME not in", values, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BIRTHDAY_UPDATE_TIME between", value1, value2, "birthdayUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayUpdateTimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BIRTHDAY_UPDATE_TIME not between", value1, value2, "birthdayUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 05 18:37:36 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue Nov 05 18:37:36 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}