package com.wanda.member.upgrade.data;

import com.wanda.member.upgrade.data.TMemberUpgradeTask;
import com.wanda.member.upgrade.data.TMemberUpgradeTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberUpgradeTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int countByExample(TMemberUpgradeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int deleteByExample(TMemberUpgradeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int deleteByPrimaryKey(String taskDay);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int insert(TMemberUpgradeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int insertSelective(TMemberUpgradeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    List<TMemberUpgradeTask> selectByExample(TMemberUpgradeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    TMemberUpgradeTask selectByPrimaryKey(String taskDay);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") TMemberUpgradeTask record, @Param("example") TMemberUpgradeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int updateByExample(@Param("record") TMemberUpgradeTask record, @Param("example") TMemberUpgradeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int updateByPrimaryKeySelective(TMemberUpgradeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_UPGRADE_TASK
     *
     * @mbggenerated Wed Nov 06 16:47:06 CST 2013
     */
    int updateByPrimaryKey(TMemberUpgradeTask record);
}