package com.wanda.member.upgrade.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMemberLevelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public TMemberLevelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("LEVEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("LEVEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLevelIdEqualTo(BigDecimal value) {
            addCriterion("LEVEL_ID =", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotEqualTo(BigDecimal value) {
            addCriterion("LEVEL_ID <>", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThan(BigDecimal value) {
            addCriterion("LEVEL_ID >", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVEL_ID >=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThan(BigDecimal value) {
            addCriterion("LEVEL_ID <", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVEL_ID <=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIn(List<BigDecimal> values) {
            addCriterion("LEVEL_ID in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotIn(List<BigDecimal> values) {
            addCriterion("LEVEL_ID not in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVEL_ID between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVEL_ID not between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(BigDecimal value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(BigDecimal value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<BigDecimal> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<BigDecimal> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemLevelIsNull() {
            addCriterion("MEM_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMemLevelIsNotNull() {
            addCriterion("MEM_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMemLevelEqualTo(String value) {
            addCriterion("MEM_LEVEL =", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelNotEqualTo(String value) {
            addCriterion("MEM_LEVEL <>", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelGreaterThan(String value) {
            addCriterion("MEM_LEVEL >", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelGreaterThanOrEqualTo(String value) {
            addCriterion("MEM_LEVEL >=", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelLessThan(String value) {
            addCriterion("MEM_LEVEL <", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelLessThanOrEqualTo(String value) {
            addCriterion("MEM_LEVEL <=", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelLike(String value) {
            addCriterion("MEM_LEVEL like", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelNotLike(String value) {
            addCriterion("MEM_LEVEL not like", value, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelIn(List<String> values) {
            addCriterion("MEM_LEVEL in", values, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelNotIn(List<String> values) {
            addCriterion("MEM_LEVEL not in", values, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelBetween(String value1, String value2) {
            addCriterion("MEM_LEVEL between", value1, value2, "memLevel");
            return (Criteria) this;
        }

        public Criteria andMemLevelNotBetween(String value1, String value2) {
            addCriterion("MEM_LEVEL not between", value1, value2, "memLevel");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNull() {
            addCriterion("EXPIRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNotNull() {
            addCriterion("EXPIRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpireDateEqualTo(Date value) {
            addCriterion("EXPIRE_DATE =", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotEqualTo(Date value) {
            addCriterion("EXPIRE_DATE <>", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThan(Date value) {
            addCriterion("EXPIRE_DATE >", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXPIRE_DATE >=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThan(Date value) {
            addCriterion("EXPIRE_DATE <", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThanOrEqualTo(Date value) {
            addCriterion("EXPIRE_DATE <=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIn(List<Date> values) {
            addCriterion("EXPIRE_DATE in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotIn(List<Date> values) {
            addCriterion("EXPIRE_DATE not in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateBetween(Date value1, Date value2) {
            addCriterion("EXPIRE_DATE between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotBetween(Date value1, Date value2) {
            addCriterion("EXPIRE_DATE not between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andOrgLevelIsNull() {
            addCriterion("ORG_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andOrgLevelIsNotNull() {
            addCriterion("ORG_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andOrgLevelEqualTo(String value) {
            addCriterion("ORG_LEVEL =", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelNotEqualTo(String value) {
            addCriterion("ORG_LEVEL <>", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelGreaterThan(String value) {
            addCriterion("ORG_LEVEL >", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_LEVEL >=", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelLessThan(String value) {
            addCriterion("ORG_LEVEL <", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelLessThanOrEqualTo(String value) {
            addCriterion("ORG_LEVEL <=", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelLike(String value) {
            addCriterion("ORG_LEVEL like", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelNotLike(String value) {
            addCriterion("ORG_LEVEL not like", value, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelIn(List<String> values) {
            addCriterion("ORG_LEVEL in", values, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelNotIn(List<String> values) {
            addCriterion("ORG_LEVEL not in", values, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelBetween(String value1, String value2) {
            addCriterion("ORG_LEVEL between", value1, value2, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andOrgLevelNotBetween(String value1, String value2) {
            addCriterion("ORG_LEVEL not between", value1, value2, "orgLevel");
            return (Criteria) this;
        }

        public Criteria andSetTimeIsNull() {
            addCriterion("SET_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSetTimeIsNotNull() {
            addCriterion("SET_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSetTimeEqualTo(Date value) {
            addCriterion("SET_TIME =", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotEqualTo(Date value) {
            addCriterion("SET_TIME <>", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeGreaterThan(Date value) {
            addCriterion("SET_TIME >", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SET_TIME >=", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeLessThan(Date value) {
            addCriterion("SET_TIME <", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeLessThanOrEqualTo(Date value) {
            addCriterion("SET_TIME <=", value, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeIn(List<Date> values) {
            addCriterion("SET_TIME in", values, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotIn(List<Date> values) {
            addCriterion("SET_TIME not in", values, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeBetween(Date value1, Date value2) {
            addCriterion("SET_TIME between", value1, value2, "setTime");
            return (Criteria) this;
        }

        public Criteria andSetTimeNotBetween(Date value1, Date value2) {
            addCriterion("SET_TIME not between", value1, value2, "setTime");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIsNull() {
            addCriterion("TARGET_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIsNotNull() {
            addCriterion("TARGET_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLevelEqualTo(String value) {
            addCriterion("TARGET_LEVEL =", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotEqualTo(String value) {
            addCriterion("TARGET_LEVEL <>", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelGreaterThan(String value) {
            addCriterion("TARGET_LEVEL >", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_LEVEL >=", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelLessThan(String value) {
            addCriterion("TARGET_LEVEL <", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelLessThanOrEqualTo(String value) {
            addCriterion("TARGET_LEVEL <=", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelLike(String value) {
            addCriterion("TARGET_LEVEL like", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotLike(String value) {
            addCriterion("TARGET_LEVEL not like", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIn(List<String> values) {
            addCriterion("TARGET_LEVEL in", values, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotIn(List<String> values) {
            addCriterion("TARGET_LEVEL not in", values, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelBetween(String value1, String value2) {
            addCriterion("TARGET_LEVEL between", value1, value2, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotBetween(String value1, String value2) {
            addCriterion("TARGET_LEVEL not between", value1, value2, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetIsNull() {
            addCriterion("LEVEL_POINT_OFFSET is null");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetIsNotNull() {
            addCriterion("LEVEL_POINT_OFFSET is not null");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetEqualTo(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET =", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetNotEqualTo(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET <>", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetGreaterThan(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET >", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET >=", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetLessThan(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET <", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVEL_POINT_OFFSET <=", value, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetIn(List<BigDecimal> values) {
            addCriterion("LEVEL_POINT_OFFSET in", values, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetNotIn(List<BigDecimal> values) {
            addCriterion("LEVEL_POINT_OFFSET not in", values, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVEL_POINT_OFFSET between", value1, value2, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andLevelPointOffsetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVEL_POINT_OFFSET not between", value1, value2, "levelPointOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetIsNull() {
            addCriterion("TICKET_OFFSET is null");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetIsNotNull() {
            addCriterion("TICKET_OFFSET is not null");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetEqualTo(BigDecimal value) {
            addCriterion("TICKET_OFFSET =", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetNotEqualTo(BigDecimal value) {
            addCriterion("TICKET_OFFSET <>", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetGreaterThan(BigDecimal value) {
            addCriterion("TICKET_OFFSET >", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TICKET_OFFSET >=", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetLessThan(BigDecimal value) {
            addCriterion("TICKET_OFFSET <", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TICKET_OFFSET <=", value, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetIn(List<BigDecimal> values) {
            addCriterion("TICKET_OFFSET in", values, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetNotIn(List<BigDecimal> values) {
            addCriterion("TICKET_OFFSET not in", values, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TICKET_OFFSET between", value1, value2, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andTicketOffsetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TICKET_OFFSET not between", value1, value2, "ticketOffset");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoIsNull() {
            addCriterion("CHANGE_LEVEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoIsNotNull() {
            addCriterion("CHANGE_LEVEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoEqualTo(String value) {
            addCriterion("CHANGE_LEVEL_NO =", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoNotEqualTo(String value) {
            addCriterion("CHANGE_LEVEL_NO <>", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoGreaterThan(String value) {
            addCriterion("CHANGE_LEVEL_NO >", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoGreaterThanOrEqualTo(String value) {
            addCriterion("CHANGE_LEVEL_NO >=", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoLessThan(String value) {
            addCriterion("CHANGE_LEVEL_NO <", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoLessThanOrEqualTo(String value) {
            addCriterion("CHANGE_LEVEL_NO <=", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoLike(String value) {
            addCriterion("CHANGE_LEVEL_NO like", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoNotLike(String value) {
            addCriterion("CHANGE_LEVEL_NO not like", value, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoIn(List<String> values) {
            addCriterion("CHANGE_LEVEL_NO in", values, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoNotIn(List<String> values) {
            addCriterion("CHANGE_LEVEL_NO not in", values, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoBetween(String value1, String value2) {
            addCriterion("CHANGE_LEVEL_NO between", value1, value2, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andChangeLevelNoNotBetween(String value1, String value2) {
            addCriterion("CHANGE_LEVEL_NO not between", value1, value2, "changeLevelNo");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("ISDELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("ISDELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(BigDecimal value) {
            addCriterion("ISDELETE =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(BigDecimal value) {
            addCriterion("ISDELETE >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(BigDecimal value) {
            addCriterion("ISDELETE <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<BigDecimal> values) {
            addCriterion("ISDELETE in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<BigDecimal> values) {
            addCriterion("ISDELETE not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(BigDecimal value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(BigDecimal value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(BigDecimal value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(BigDecimal value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<BigDecimal> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<BigDecimal> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdIsNull() {
            addCriterion("MEMBER_LEVEL_HISTORY_ID is null");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdIsNotNull() {
            addCriterion("MEMBER_LEVEL_HISTORY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdEqualTo(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID =", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdNotEqualTo(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID <>", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdGreaterThan(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID >", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID >=", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdLessThan(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID <", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID <=", value, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdIn(List<BigDecimal> values) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID in", values, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdNotIn(List<BigDecimal> values) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID not in", values, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID between", value1, value2, "memberLevelHistoryId");
            return (Criteria) this;
        }

        public Criteria andMemberLevelHistoryIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MEMBER_LEVEL_HISTORY_ID not between", value1, value2, "memberLevelHistoryId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 29 10:31:21 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEMBER_LEVEL
     *
     * @mbggenerated Tue Oct 29 10:31:21 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}